### PR TITLE
Fix currently scrolling layer id  caching

### PR DESCRIPTION
**Pull request by gterzian**
Fix for https://github.com/servo/servo/issues/15251

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/800)

### CODE REVIEW

**Comment by gterzian** [comment]
@jdm So I am still unable to reproduce the panic. If you can do so consistently, could I please ask you to test if this fixes it? This one requires building with https://github.com/servo/servo/pull/15111

**Comment by glennw** [comment]
This seems OK to me - but let's double check with @mrobinson first.

**Comment by gterzian** [comment]
@glennw Thank you. I changed the variables names a bit for clarity...

**Comment by mrobinson** [comment]
I think that we will need to change the API in order to let WebRender know when a batch of scroll layers doesn't have any correspondence with the previous one. I need that for a PR that I'm working on, but a decent fallback here makes sense as well. Thanks!

**Comment by mrobinson** [comment]
The new API is here: https://github.com/servo/webrender/pull/806

This patch should work fine in tandem with that.

**Comment by gterzian** [comment]
@glennw @mrobinson Thanks for your help, I will also take a look at the new API, and the scroll testing capabilities of Wrench. Sorry I didn't squash that one extra commit, I guess it's not the end of the world...

**Comment by glennw** [comment]
No worries, thanks for the fix!

**Pull request merged**
