### PR TITLE
modified configuration lines to specify windows, linux, and mac

### PR DESCRIPTION
**Pull request by alanamramjit**

### CODE REVIEW

**Comment by jdm** [comment]
Travis says that there are unclosed delimiters in the Cargo.toml file now.

**Comment by larsbergstrom** [comment]
Nice work, Lana! I'm excited to see your first PR and sorry that everything has been so chaotic around here with the push to get the Servo Nightlies out this week.

**Comment by glennw** [comment]
@alanamramjit Looks good - could you squash these two commits and then we'll get this merged? Thanks

**Comment by larsbergstrom** [comment]
Lana, feel free to reach out to any of us if using git to squash changes goes awry for you. There are some tips here:
https://github.com/servo/servo/wiki/Github-workflow

But in general, one possible command that you're looking for is `git rebase -i HEAD~2`.

**Comment by alanamramjit** [comment]
I think it did go awry :[

**Comment by larsbergstrom** [comment]
OK, try this locally:

```
[larsberg@larsberg webrender]$ git checkout -b modify_config
Switched to a new branch 'modify_config'
[larsberg@larsberg webrender]$ git cherry-pick 9eede7b
[modify_config cf93178] modified configuration lines to specify windows, linux, and mac
 Author: lana <alanamramjit@gmail.com>
 Date: Thu Jun 30 12:26:49 2016 -0700
 2 files changed, 4 insertions(+), 4 deletions(-)
[larsberg@larsberg webrender]$ git cherry-pick 9d6bb0e
[modify_config 897d2b5] fixed parantheses
 Author: lana <alanamramjit@gmail.com>
 Date: Thu Jun 30 13:27:21 2016 -0700
 1 file changed, 3 insertions(+), 3 deletions(-)
[larsberg@larsberg webrender]$ git rebase -i HEAD~2
[detached HEAD 5a0d4fd] modified configuration lines to specify windows, linux, and mac
 Author: lana <alanamramjit@gmail.com>
 Date: Thu Jun 30 12:26:49 2016 -0700
 2 files changed, 4 insertions(+), 4 deletions(-)
Successfully rebased and updated refs/heads/modify_config.
```

In the `git rebase` command, it will open up an editor with the two commits you just cherry-pick'd. On the line with the second one, change the first word to "fixup", save and exit. At this point you can then push this branch up to your github repo. Change the `larsberg` below to whatever the name of your personal github repo is. You can get it by looking at the out put of `git remote -v`:
```
[larsberg@larsberg webrender]$ git push larsberg modify_config
Counting objects: 134, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (52/52), done.
Writing objects: 100% (134/134), 24.25 KiB | 0 bytes/s, done.
Total 134 (delta 99), reused 115 (delta 81)
To https://github.com/larsbergstrom/webrender
 * [new branch]      modify_config -> modify_config
[larsberg@larsberg webrender]$ 
```

At that point, you can go back to the GitHub UI for https://github.com/servo/webrender and it should say that there is a potential PR to open from your repository. You can go ahead and do so, commenting with an "r? @larsbergstrom" and close this one.

**Comment by alanamramjit** [comment]
@larsbergstrom hm I tried fixing it this way and several other couple of ways but it's still trying to create a pull request with > 4 commits so I think I'm going to take the burn it with fire approach

**Pull request closed without merging**
