### PR TITLE
Add a sticky frame to the scrolling example

### PR DESCRIPTION
**Pull request by staktrace**
r? @mrobinson 

Trivial example but enough to help me figure out what all the values mean.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1652)

### CODE REVIEW

**Comment by mrobinson** [comment]
Thanks! Sorry that I haven't uploaded my example yet. I'll see if I can use it to improve your example sometime later when I have more free time.

**Comment by staktrace** [comment]
No worries. It turned out to be pretty straightforward anyway :)

**Pull request merged**
