### PR TITLE
Sync changes from mozilla-central

### PR DESCRIPTION
**Pull request by moz-gfx**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/3735)

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo r-

 * Bors ist tot.

**Comment by SimonSapin** [comment]
On macOS:

```
    Checking image v0.22.1
     Running `rustc --crate-name image /Users/worker/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.22.1/./src/lib.rs --color never --crate-type lib --emit=dep-info,metadata -C panic=abort -C debuginfo=2 --cfg 'feature="bmp"' --cfg 'feature="default"' --cfg 'feature="dxt"' --cfg 'feature="gif"' --cfg 'feature="gif_codec"' --cfg 'feature="hdr"' --cfg 'feature="ico"' --cfg 'feature="jpeg"' --cfg 'feature="jpeg-decoder"' --cfg 'feature="jpeg_rayon"' --cfg 'feature="png"' --cfg 'feature="png_codec"' --cfg 'feature="pnm"' --cfg 'feature="scoped_threadpool"' --cfg 'feature="tga"' --cfg 'feature="tiff"' --cfg 'feature="webp"' -C metadata=d3e3c10f50641fb2 -C extra-filename=-d3e3c10f50641fb2 --out-dir /Users/worker/generic-worker/generic-worker-taskdir/task_1565864548/webrender/target/debug/deps -L dependency=/Users/worker/generic-worker/generic-worker-taskdir/task_1565864548/webrender/target/debug/deps --extern byteorder=/Users/worker/generic-worker/generic-worker-taskdir/task_1565864548/webrender/target/debug/deps/libbyteorder-0bc3734dffb00430.rmeta --extern gif=/Users/worker/generic-worker/generic-worker-taskdir/task_1565864548/webrender/target/debug/deps/libgif-525e72a487bf66ba.rmeta --extern jpeg_decoder=/Users/worker/generic-worker/generic-worker-taskdir/task_1565864548/webrender/target/debug/deps/libjpeg_decoder-ea3da78a04148120.rmeta --extern lzw=/Users/worker/generic-worker/generic-worker-taskdir/task_1565864548/webrender/target/debug/deps/liblzw-869ea2693557ef47.rmeta --extern num_iter=/Users/worker/generic-worker/generic-worker-taskdir/task_1565864548/webrender/target/debug/deps/libnum_iter-1f6ae22905e05213.rmeta --extern num_rational=/Users/worker/generic-worker/generic-worker-taskdir/task_1565864548/webrender/target/debug/deps/libnum_rational-5c4c33a29bcf128e.rmeta --extern num_traits=/Users/worker/generic-worker/generic-worker-taskdir/task_1565864548/webrender/target/debug/deps/libnum_traits-a8678d6107b27403.rmeta --extern png=/Users/worker/generic-worker/generic-worker-taskdir/task_1565864548/webrender/target/debug/deps/libpng-d8fa1d6733f834c1.rmeta --extern scoped_threadpool=/Users/worker/generic-worker/generic-worker-taskdir/task_1565864548/webrender/target/debug/deps/libscoped_threadpool-0a922434184f6469.rmeta --extern tiff=/Users/worker/generic-worker/generic-worker-taskdir/task_1565864548/webrender/target/debug/deps/libtiff-f9266a7f17f862a8.rmeta --cap-lints allow --deny warnings`
rustc(69948,0x7000094cd000) malloc: *** error for object 0xda1943b0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
error: Could not compile `image`.
```

On Windows:

```
Reftests with unexpected results:
	reftests\text\split-batch.yaml == reftests\text\split-batch-ref.yaml
```
```
WARN: rx::HLSLCompiler::compileToBinary(228): 
C:\fakepath(1766,14-129): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
C:\fakepath(1772,58-112): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
C:\fakepath(1789,67-72): warning X3556: integer divides may be much slower, try using uints if possible.
C:\fakepath(1792,46-51): warning X3556: integer modulus may be much slower, try using uints if possible.
C:\fakepath(1812,29-78): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
C:\fakepath(1642,1-6): warning X4000: use of potentially uninitialized variable (dyn_index_vec4_float4)
C:\fakepath(1927,25-29): error X4576: Input array signature parameter SV_Position cannot be indexed dynamically.
WARN: rx::HLSLCompiler::compileToBinary(228): 
C:\fakepath(1766,14-129): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
C:\fakepath(1772,58-112): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
C:\fakepath(1789,67-72): warning X3556: integer divides may be much slower, try using uints if possible.
C:\fakepath(1792,46-51): warning X3556: integer modulus may be much slower, try using uints if possible.
C:\fakepath(1812,29-78): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
C:\fakepath(1642,1-6): warning X4000: use of potentially uninitialized variable (dyn_index_vec4_float4)
C:\fakepath(1927,25-29): error X4576: Input array signature parameter SV_Position cannot be indexed dynamically.
WARN: rx::HLSLCompiler::compileToBinary(228): 
C:\fakepath(1789,67-72): warning X3556: integer divides may be much slower, try using uints if possible.
C:\fakepath(1792,46-51): warning X3556: integer modulus may be much slower, try using uints if possible.
C:\fakepath(1642,1-6): warning X4000: use of potentially uninitialized variable (dyn_index_vec4_float4)
C:\fakepath(1693,1): warning X4000: use of potentially uninitialized variable (f_distance_aa)
C:\fakepath(1730,1): warning X4000: use of potentially uninitialized variable (f_do_clip)
WARN: rx::HLSLCompiler::compileToBinary(228): 
C:\fakepath(1968,58-112): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
C:\fakepath(1962,14-129): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
C:\fakepath(1991,79-84): warning X3556: integer divides may be much slower, try using uints if possible.
C:\fakepath(1994,46-51): warning X3556: integer modulus may be much slower, try using uints if possible.
C:\fakepath(2010,29-78): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
C:\fakepath(1667,1-6): warning X4000: use of potentially uninitialized variable (dyn_index_vec4_float4)
```

**Comment by staktrace** [comment]
The Windows failure is intermittent, it showed up a few times before. Dunno about the macOS one.

**Comment by staktrace** [comment]
I guess updating rustc on the macOS worker is probably a good idea and might fix the issue.

**Pull request merged**
