### PR TITLE
Port YUV primitive to be a brush.

### PR DESCRIPTION
**Pull request by glennw**
Also refactor and optimize the YUV shader implementation to do
less per-pixel work.

Support segment building for YUV primitive - this is a large
performance win for any YUV images with a complex clip on them.

This is part of the prep work to allow selection of whether
a stacking context is rasterized in local or screen-space.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2424)

### CODE REVIEW

**Comment by glennw** [comment]
r? @nical and/or @kvark 

If someone else on Gecko knows the YUV code better, please get them to take a look too as we don't have a huge amount of test coverage in-tree for YUV images.

Pending try:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=0c5b905907fb40875452aa702cd9ff0d8cc90a96

**Comment by glennw** [comment]
There are a couple of failures in some of the MP4 tests, which are probably related to this. I'll investigate those and see if I can reproduce locally.

**Comment by glennw** [comment]
Fixed a typo - was using the ```uv_bounds.z``` for the texture layer index instead of the ```uv.z```. Another gecko try coming shortly to confirm it's all fixed.

**Comment by glennw** [comment]
Pending try with typo fix:

https://hg.mozilla.org/try/rev/e36a9175fff173fa054e24cdc972d0980c67ee77
https://treeherder.mozilla.org/#/jobs?repo=try&revision=e36a9175fff173fa054e24cdc972d0980c67ee77

**Comment by glennw** [comment]
Try looks good now, I think - just the expected failure in R8 from previous PR, and an unrelated intermittent in R4 (that test has no YUV images).

**Comment by kvark** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[webrender/res/brush_yuv_image.glsl, line 146 at r1](https://reviewable.io:443/reviews/servo/webrender/2424#-L5PzFwnyR24G2y3VpX4:-L5PzFwo9-55Mh-9k08a:b-1mxjtu) ([raw file](https://github.com/servo/webrender/blob/e6dc591ce1cef195378fb53f4573e5d21646b66d/webrender/res/brush_yuv_image.glsl#L146)):*
> ```GLSL
>     vec2 uv_u = clamp(vUv_U.xy, vUvBounds_U.xy, vUvBounds_U.zw);
>     vec2 uv_v = clamp(vUv_V.xy, vUvBounds_V.xy, vUvBounds_V.zw);
>     yuv_value.x = TEX_SAMPLE(sColor0, vec3(uv_y, vUv_Y.z)).r;
> ```

it almost feels like our `TEX_SAMPLE` macro should get an extra parameter of UV bounds and do the clamping

---

*[webrender/res/brush_yuv_image.glsl, line 159 at r1](https://reviewable.io:443/reviews/servo/webrender/2424#-L5PzjruRs2JkQQpJMLK:-L5PzjruRs2JkQQpJMLL:b-igq48a) ([raw file](https://github.com/servo/webrender/blob/e6dc591ce1cef195378fb53f4573e5d21646b66d/webrender/res/brush_yuv_image.glsl#L159)):*
> ```GLSL
>     // https://www.khronos.org/registry/OpenGL/extensions/APPLE/APPLE_rgb_422.txt
>     vec2 uv_y = clamp(vUv_YUV.xy, vUvBounds_YUV.xy, vUvBounds_YUV.zw);
>     yuv_value = TEX_SAMPLE(sColor0, vec3(uv_y, vUv_YUV.z)).gbr;
> ```

uh, the `gbr` order here is confusing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/2424#-:-L5Q-00xzzR-uqudV4iz:bnfp4nl)*

**Comment by staktrace** [comment]
This PR seems to have introduced shader compilation failures on Windows. See https://treeherder.mozilla.org/logviewer.html#?job_id=162670488&repo=try&lineNumber=1823

This also probably explains the orange windows test jobs in the try push noted earlier in this PR. Those jobs should be green.

**Comment by kvark** [comment]
@staktrace sorry about that! I'm fixing this.

**Pull request merged**
