### PR TITLE
Remove BorderWidthsAu

### PR DESCRIPTION
**Pull request by pyfisch**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/3084)

### CODE REVIEW

**Comment by gw3583** [comment]
If possible, could we hold off on merging this until https://github.com/servo/webrender/pull/3075 lands?

I'd like to get that PR merged very soon, and this will cause it to conflict and need another rebase. Sorry!

**Comment by gw3583** [comment]
#3075 has landed now, thanks! This will need rebasing and some (hopefully) small changes, then it should be good to merge.

**Comment by pyfisch** [comment]
rebased

**Pull request merged**
