### PR TITLE
Make sure we un-premultiply alpha before applying filters.

### PR DESCRIPTION
**Pull request by demo99**
This should fix gecko [bug 1408116](https://bugzilla.mozilla.org/show_bug.cgi?id=1408116).

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2048)

### CODE REVIEW

**Comment by kvark** [comment]
Could you provide a gecko try push please?

**Comment by demo99** [comment]
Sure. Gecko try push: https://treeherder.mozilla.org/#/jobs?repo=try&revision=bb72dc8c7fb41f2ee805ff0d32c0c59d97e1aa5f

**Comment by glennw** [comment]
@bors-servo r+

Thanks!

**Pull request merged**
