### PR TITLE
Prevent segmented primitives from reading outdated clip tasks.

### LINKED ISSUE #2531: Large element with 2d transform disappears sometimes
When scrolling up and down on [this testcase](https://bug1446129.bmoattachments.org/attachment.cgi?id=8959296), the blue box sometimes disappears.

Here's a recording of a frame where the element is missing: http://tests.themasta.com/webrender-transformed-large-box-disappears-capture.zip

### PR DESCRIPTION
**Pull request by nical**
Fixes #2531.

Brush segments store handles to their own clip tasks. If segmentation heuristics change we need to either clear the segment information or update it to ensure the clip tasks they point to are requested (this commit does the latter).

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2564)

### CODE REVIEW

**Comment by nical** [comment]
r? @glennw 

This is I think the simplest way to fix #2531, although I suspect that we might want to instead un-segment primitives in some case to allow the most optimized path when segmentiation heuristics change between frames, or maybe it is enough/correct to go through the segments and clear the clip task ids.
Un-segmenting means we need to differentiate between segments created automatically during frame building and segments created explicitly when flattening the scene, plus probably a bunch of other edge cases I don't know about.
Perhaps we can land the simple fix first and then look for the best solution?

**Comment by nical** [comment]
Yeah, I know this isn't optimal since we hang on to a heuristic that was good for a previous frame but not the current one. I was unsure whether clearing the render task ids would be enough, since the new frame might not even create segments (in fact in this case I am pretty sure it wouldn't) and so we'd still be in a half-unexpected configuration, but if you think it will do, sounds good to me. I'll give this a go on Monday.

**Comment by glennw** [comment]
The segments should always be constant for a given scene, since they rely only on clips in the same reference frame (local space) as the primitive, and therefore shouldn't change with scrolling. So I think it should be fine to just clear the task IDs in this case. Thanks!

**Comment by nical** [comment]
Closing in favor of #2568.

**Pull request closed without merging**
