### PR TITLE
Unrevert #1758, fix the target allocation size to be at least 1

### PR DESCRIPTION
**Pull request by kvark**
This is an alternative to #1782
r? @glennw

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1783)

### CODE REVIEW

**Comment by kvark** [comment]
@glennw I believe the reason was [mentioned here](https://github.com/servo/webrender/pull/1758#issuecomment-333234083). If you can see a clean way to prevent 0x0 coming through, I'd be happy to agree with it ;)

**Comment by glennw** [comment]
Yep - I think we should be able to find out which render task results in a 0 sized allocation and handle that case. I'll take a look this week at the test failures.

**Comment by glennw** [comment]
I traced this in the failing Gecko test. We end up in a situation where a stacking context is considered visible, even though the screen bounding rect for the stacking context is zero. This means we create a dynamic alpha batch task with zero size, which triggers the assertion. We'll need to find why the SC is considered visible in this case.

**Comment by glennw** [comment]
I'll close this for now - since the original patch causes a test failure in Servo too, that I haven't investigated yet. We can re-open once these issues are sorted out.

**Pull request closed without merging**
