### PR TITLE
Fixed snap rectangle for the glyph runs

### PR DESCRIPTION
**Pull request by kvark**
r? @glennw 
cc @mrobinson

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1441)

### CODE REVIEW

**Comment by staktrace** [comment]
@kvark This PR caused a gecko reftest regression in `layout/reftests/stylesheet-cloning/counter-style-rule-clone.html`. Links to [reftest analyzer](https://hg.mozilla.org/mozilla-central/raw-file/tip/layout/tools/reftest/reftest-analyzer.xhtml#logurl=https://queue.taskcluster.net/v1/task/YedCkBJ_Qu-sGuqSI_kXWg/runs/0/artifacts/public/logs/live_backing.log&only_show_unexpected=1) and [try push](https://treeherder.mozilla.org/#/jobs?repo=try&revision=cd73663553559628dcd77c1b14f74b3163bbd97d)

**Comment by kvark** [comment]
@staktrace 
Interesting! Perhaps, we should be snapping to something else then the primitive rect.
Created #1451 to investigate

**Comment by kvark** [comment]
@staktrace I verified that it's not  #1441 that broke the test. I suspect it's the mix of  #1441 with #1375

**Pull request merged**
