### PR TITLE
Support ahem reftests in wrench.

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1793)

### CODE REVIEW

**Comment by glennw** [comment]
r? @kvark or @nical 

@Gankro Once I disabled subpx AA in the tests, the results are pixel perfect (on Linux at least, pending CI on mac) :)

**Comment by Gankro** [comment]
Wow, super surprising that the difference is that high!

I assume the path forward for gecko reftests is to wait for @lsalzman's FontInfo patches to land?

**Comment by glennw** [comment]
If Gecko already reads information from FontConfig as to whether subpixel AA is enabled, you could potentially modify where Gecko calls ```add_font_instance``` to create fonts without subpixel AA (or even just pass through the global enable subpixel AA option in ```RendererOptions``` at init time).

Otherwise, waiting for the patches @lsalzman is working on should resolve the issue.

**Pull request merged**
