### PR TITLE
Switch opacity bindings to array, and optimize size of BrushPrimitive.

### PR DESCRIPTION
**Pull request by gw3583**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/3336)

### CODE REVIEW

**Comment by gw3583** [comment]
r? @nical or @kvark or anyone

There are two patches here.

The first moves opacity binding from being inline in the brush primitive to being a separate array. This makes things easier once I intern images and rectangles.

The second patch makes the border segments be a vec instead of a smallvec. I noticed that the size of the BrushPrimitive was very large, which is fixed by this. This is a temporary fix, it won't be needed once the primitives are interned, but it is a big enough win that it's worth having for now. It drops the size of each ```BrushKind``` from 1632 bytes down to 168 bytes. This drops the ```dl_mutate``` talos test from ~5300 to ~4700, which is a significant win.

**Comment by gw3583** [comment]
Pending try:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=7160b048de4bc64e76bee67a8b8401b5ec46217d

**Comment by gw3583** [comment]
Try run looks good.

**Comment by nical** [comment]
It'd be nice to sotre segments in a separate vec (or segmented vec) in the primitive store or some per-cluster data structure and refer to them by ids like this PR does with opacity bindings.

@bors-servo r+

**Pull request merged**
