### PR TITLE
Update glutin to 0.21, winit to 0.19

### LINKED ISSUE #3612: Update to Glutin 0.21.0
Hey folks. Glutin v0.21.0 is out.

### PR DESCRIPTION
**Pull request by jplatte**
Resolves #3612
Supersedes #3546

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/3690)

### CODE REVIEW

**Comment by jplatte** [comment]
Do I need to fix the duplicate dependencies (crossbeam etc) as reported by Taskcluster? That would make this PR a bit more complex (I don't know how much).

**Comment by atouchet** [comment]
> Do I need to fix the duplicate dependencies (crossbeam etc) as reported by Taskcluster? That would make this PR a bit more complex (I don't know how much), but I'd be happy to look into updating them as well.

I don't know if they'll care about those duplicates but for now you could add them to [servo-tidy.toml](https://github.com/servo/webrender/blob/master/servo-tidy.toml).

**Comment by jplatte** [comment]
Ah, thanks for pointing me to that file. It says that one of the files I touched is copied from glutin; I should probably copy over glutin 0.21's version of that file (or import the module if it is more public).

**Comment by jplatte** [comment]
So I looked at that file and it's not as easy as copying egl.rs, it [imports private items from glutin][1]. I'll leave the file as it is until I get further feedback.

[1]: https://github.com/rust-windowing/glutin/blob/master/glutin/src/api/egl/mod.rs#L15

**Comment by jplatte** [comment]
Rebased and put the duplicate deps in the ignore list in servo-tidy.toml

Like I said before, I'd be happy to investigate how to get rid of the duplicate dependencies instead, if that is preferred.

**Comment by kvark** [comment]
@jplatte AppVeyor isn't happy. Could you fix this?
 https://ci.appveyor.com/project/servo/webrender/builds/25746570#L803

**Comment by jplatte** [comment]
@kvark: done

**Comment by kvark** [comment]
Imported as https://phabricator.services.mozilla.com/D36978

**Comment by atouchet** [comment]
This was merged in #3699. Thanks!

**Pull request closed without merging**
