### PR TITLE
Revert "Cache .cargo on travis"

### PR DESCRIPTION
**Pull request by glennw**
This reverts commit e1a33cd3758aa17e160b48f44bb737d4f8b76d75.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/827)

### CODE REVIEW

**Comment by glennw** [comment]
This appears to break the test code that searches for OSMesa. Reverting until we can find a better solution.

**Comment by jrmuizel** [comment]
Ah right. That makes some sense. I'll try to come up with a better solution.

**Comment by jrmuizel** [comment]
I think the best thing might be to statically link with osmesa.

**Comment by jrmuizel** [comment]
Though that might conflict with the system library so maybe that's not a great approach either.

**Pull request merged**
