### PR TITLE
Implement wrench font_key_from_name on mac and linux.

### PR DESCRIPTION
**Pull request by nical**
The code was actually written by Jeff (see issue #1254).

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1257)

### CODE REVIEW

**Comment by kvark** [comment]
Shouldn't this line be changed as well? https://github.com/servo/webrender/pull/1257/files#diff-1821d8a90ad50120b2720d853355623dR248

**Comment by glennw** [comment]
I think we'll need to either (a) include "android" in the list of target config for that function, or (b) keep a panic version of the function around for android.

An external contributor also got WR working on BSD a while ago - instead of using the linux/mac OS strings, something like ```#[cfg(any(target_os = "android", all(unix, not(target_os = "macos"))))]``` would be more appropriate - depending on whether we need a separate function for android.

**Comment by glennw** [comment]
Actually, in this case just using ```unix``` would be fine, I guess - since we want it on both mac, linux and BSD. And then whatever is appropriate for android.

**Pull request merged**
