### PR TITLE
Separate interning Image & YuvImage

### PR DESCRIPTION
**Pull request by djg**
In support of #3385, extract Image and YUVImage. This patch is based up PR #3392 and requires that to land first.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/3393)

### CODE REVIEW

**Comment by djg** [comment]
Try & talos: https://treeherder.mozilla.org/#/jobs?repo=try&revision=27cbd66f358a757efa654b7b6804e95610b207a0

**Comment by gw3583** [comment]
Could you rebase this to remove the patches that have landed now?

**Comment by djg** [comment]
> Could you rebase this to remove the patches that have landed now?

Done

**Comment by djg** [comment]
It appears that the `osx-release` taskcluster job failed to start. I've restarted it.

**Comment by gw3583** [comment]
That last commit seems a bit more complex (esp. the ```cache``` fn) than I was thinking it would be, but I haven't looked in detail yet - I might just be missing something.

The general idea of the GpuCacheRequest being a by-value type is that it should work around the borrowck issues that way. I'll pull the branch today and see if I can provide some more useful comments than the vague details above, sorry!

**Comment by djg** [comment]
> That last commit seems a bit more complex (esp. the `cache` fn) than I was thinking it would be, but I haven't looked in detail yet - I might just be missing something.
> 
> The general idea of the GpuCacheRequest being a by-value type is that it should work around the borrowck issues that way. I'll pull the branch today and see if I can provide some more useful comments than the vague details above, sorry!

@gw3583, in the previous incarnation of the code there was a split borrow of the prim fields and the borrowck was happy. It's unhappy with:

```
if Some(foo) = gpu_cache.bar(&self.common.gpu_handle) {
    ...
    self.write_prim_gpu_blocks(...);
    ...
}
```

because it can't see that `fn write_prim_gpu_blocks()` doesn't access `self.common`.

I welcome a second set of 👀 on the code.

**Comment by gw3583** [comment]
This is roughly what I was thinking [1] - does that seem like it should achieve the same outcome and work for the rest of the prim types?

[1] https://github.com/gw3583/webrender/commit/a6910bceb599458169fab746f1ef5a3fad91c5df

**Comment by djg** [comment]
@gw3583 Are we good to proceed with these changes?

**Comment by gw3583** [comment]
Yup, I think so - do we need another try / talos run or should this be good to go?

**Comment by djg** [comment]
Try push: https://treeherder.mozilla.org/#/jobs?repo=try&revision=5b13864afb0efce11588f4427603cc5c73cbf31c

**Pull request merged**
