### PR TITLE
Switch box shadows to render to A8 cache instead of RGBA8.

### PR DESCRIPTION
**Pull request by glennw**
Box shadows are just an alpha mask - we may as well save GPU
bandwidth by drawing them into the A8 cache target.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1635)

### CODE REVIEW

**Comment by Gankro** [comment]
I binary searched this to be the change that is causing https://bugzilla.mozilla.org/show_bug.cgi?id=1395982 (mac is constantly flickering).

**Comment by Gankro** [comment]
Correction: this seems to just expose an older issue (see linked discussion in previous comment).

**Comment by glennw** [comment]
@Gankro fix is here https://github.com/servo/webrender/pull/1666

**Pull request merged**
