### PR TITLE
Make automatic mipmap generation opt-in.

### PR DESCRIPTION
**Pull request by glennw**
Gecko downscales images before passing them to WR, so typically
doesn't want automatic mipmap generation enabled, which can be
slow on some platforms / drivers.

Mipmaps can still be enabled on a per-image basis, by setting the
allow_mipmaps field in the ImageDescriptor.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2555)

### CODE REVIEW

**Comment by glennw** [comment]
r? @jrmuizel 

This should help with https://github.com/servo/webrender/issues/2519.

**Comment by glennw** [comment]
@staktrace Heads up that this adds a new ```bool``` to the ```ImageDescriptor``` public struct, which will affect Gecko bindings.

**Comment by staktrace** [comment]
@glennw Thanks for the heads-up. It looks like I need to set allow_mipmaps to true on the Gecko side to preserve current behaviour in the WR update, and then we can make additional changes on the Gecko side if we want to switch it to false for certain cases or all the time.

**Comment by staktrace** [comment]
@glennw It looks like turning off mipmaps also reduced memory usage quite a bit, see https://bugzilla.mozilla.org/show_bug.cgi?id=1448006#c6 - if that's not expected it might indicate a leak in the mipmap code.

**Comment by glennw** [comment]
It would be expected to reduce (GPU-side) texture memory by ~33% in cases where mipmaps are being enabled. I'm not sure if that would be counted by the memory reporting system though. I guess it's possible that the driver was maintaining the mipmaps internally in CPU memory too.

**Pull request merged**
