### PR TITLE
Bump rayon to 1.0

### PR DESCRIPTION
**Pull request by Eijebong**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2431)

### CODE REVIEW

**Comment by glennw** [comment]
From CI it looks like some of the unit tests need to be updated too. You can check by running ```cargo test``` from the root workspace directory.

**Comment by Eijebong** [comment]
Oh woups, my bad for not running that :p

**Comment by staktrace** [comment]
This breaks the gecko build, if you can provide a patch to fix it that would be much appreciated.

https://treeherder.mozilla.org/logviewer.html#?job_id=162576263&repo=try

**Comment by glennw** [comment]
I'll work on a patch now.

**Comment by glennw** [comment]
@staktrace Attached two patches to https://bugzilla.mozilla.org/show_bug.cgi?id=1437572 - one for the webrender_bindings/ directory, and one for toolkit/ (which I assume your build script generates automatically, but included just in case). Let me know if that covers what you need.

**Comment by staktrace** [comment]
Thanks for the patches!

**Pull request merged**
