### PR TITLE
Fix AA edges on border segments.

### LINKED ISSUE #2112: Visible seams on transformed borders
You can see them if you zoom into ![example](https://raw.githubusercontent.com/glennw/webrender/86348b29b49b316fb816c49a7b816544a1099609/wrench/reftests/transforms/prim-suite.png]

#2016 fixed the split code to not have T-junctions, also forced AA to be applied to the correct rectangle. #2102 improves those edges, but apparently this is not enough?

We should fix the geometry extrusion to take the edge mask into account. But that still doesn't explain why the seams are currently visible.

cc @glennw

### PR DESCRIPTION
**Pull request by glennw**
Set the correct edge AA flags for border corner and edge
segments.

Also add support for zoom parameter on reftests and when
running wrench.

Add a reftest with zoomed, transformend border.

Fixes #2112.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2335)

### CODE REVIEW

**Comment by glennw** [comment]
r? anyone who knows the edge AA code

**Comment by glennw** [comment]
Pending gecko try:

https://hg.mozilla.org/try/rev/fd1956c3acb13b95cf75ae2c15d97c8a0bb16b3a
https://treeherder.mozilla.org/#/jobs?repo=try&revision=fd1956c3acb13b95cf75ae2c15d97c8a0bb16b3a

**Comment by glennw** [comment]
Try looks good. r? @kvark

**Comment by kvark** [comment]
> r? anyone who knows the edge AA code

Ah, I haven't set up notificaitons for this pattern yet 😆

**Pull request merged**
