### PR TITLE
Introduce border corner and edge shader path.

### PR DESCRIPTION
**Pull request by glennw**
This introduces the new border shader path, and uses it for all
solid border segments. It fixes a lot of cases that weren't previously
handled correctly. Specifically,

* AA on edge color transitions in corners.
* Correct elliptical border radii and AA.
* Improved AA for circular radii.
* Handle AA correctly for pinch zoom / perspective transforms.
* Correct angle for color transitions in corners.

The next step is to port the other border styles over to this new
code path.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1106)

### CODE REVIEW

**Comment by glennw** [comment]
Examples of the handled border cases and AA when zooming:

aa2
borders1
borders2
borders3
borders4
borders5
borders6
borders7

**Comment by kvark** [comment]
Merging now, can be continued in follow-ups.
@bors-servo r+

**Comment by staktrace** [comment]
@glennw I believe this patch caused a reftest failure in gecko - see https://bugzilla.mozilla.org/show_bug.cgi?id=1355475#c4

**Comment by glennw** [comment]
@staktrace  This is fixed by https://github.com/servo/webrender/pull/1120.

**Comment by staktrace** [comment]
Verified that #1120 fixed the regression, thanks!

**Pull request merged**
