### PR TITLE
Work around OSX/Intel shader bug with integer comparison

### LINKED ISSUE #2754: Regression in the rendering of rounded borders
There seems to have been a recent regression in the way rounded borders are rendered. Here is a [test case](https://rawgit.com/Zirro/c72becdcd5c05eb6547ad2cc9e5638aa/raw/dc6439f1d86c12430bc15c64afc914a68b32cc14/rounded-border.html), with screenshots below.

Without WebRender:

Without WebRender

With WebRender:

With WebRender

This seems to have changed within the last month, as the circle can be seen rendering properly in [this issue](https://github.com/servo/webrender/issues/2590) created at the end of March.

### LINKED ISSUE #2862: Bottom left border radius isn't drawn correctly (on macOS 10.12)
Hi, I'm trying to use webrender as a window renderer.

So, here is an example I use to render a square window with the transparent rounded borders (corners):

https://github.com/qezz/webrender-bottom-left-border-issue/blob/master/src/main.rs

It appears to happen on mac only.

**Expected output:**

* all borders are rounded

**Actual output:**

* Bottom left border isn't rounded

screen shot 2018-07-02 at 17 34 03

(The black background is a terminal window provided just for the demonstration. Top-left, top-right, and bottom-right borders are rounded and the corners are transparent)

**Configuration**

* MacBook Pro (Retina, 13-inch, Early 2015)
* macOS 10.12.6 (Sierra)
* Intel Iris Graphics 6100 1536 MB
* webrender std output:
```
OpenGL version 4.1 INTEL-10.25.19
Shader resource path: None
Device pixel ratio: 2
```
* **EDIT2**: webrender version: `rev = "34a498f7e46c385a189299e7369e204e1cb2060c"`

**EDIT:** Probably related issues: 

* #2754 
* https://github.com/servo/servo/issues/20922

### PR DESCRIPTION
**Pull request by kvark**
Fixes #2862
Fixes #2754

Oh OSX GL drivers, so rough, such cruel, no remorse.
r? anyone

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2864)

### CODE REVIEW

**Comment by pcwalton** [comment]
Needs a comment explaining what's going on and linking to the issues.

**Comment by kvark** [comment]
https://github.com/servo/webrender/wiki/Driver-issues#2864---mac-glsl-compiler-bug-with-integer-comparisons

**Comment by Darkspirit** [comment]
This will also fix [bug 1423087](https://bugzilla.mozilla.org/show_bug.cgi?id=1423087), right?

**Comment by kvark** [comment]
@Darkspirit yes, sounds like it:
> x86_64
> Mac OS X

@pcwalton r?

**Pull request merged**
