### PR TITLE
snap the text run offset and glyph offsets separately

### PR DESCRIPTION
**Pull request by lsalzman**
This fixes issues introduced by #2738. Since the transform offset was snapped separately from the text/glyph offsets, this led to problems where certain Servo reftests might migrate a subpixel offset between the transform and the text offset.

As a compromise, Glenn and I agreed it would be best to combine the transform and text offset for snapping, then separately base the subpixel positioning off of only the glyph offset. This both keeps the resolution of Gecko's scrolling issue while addressing the Servo issue.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2830)

### CODE REVIEW

**Comment by lsalzman** [comment]
Try run: https://treeherder.mozilla.org/#/jobs?repo=try&revision=e494ef861d68050b897139e23abf43a248faf1e1

**Comment by gw3583** [comment]
This looks good to me! Could we add a reftest for it?

**Comment by lsalzman** [comment]
Fixes shadow-transforms and add a new reftest

**Pull request merged**
