### PR TITLE
Remove the need to sort use/mod statements alphabetically.

### LINKED ISSUE #2486: Can we *please* remove the need to sort use statements alphabetically?
This lint gets in my way all the time. I find it pointless, and whatever sorting the lint requires is neither of sublime text's two alphabetical line sorting methods.

### PR DESCRIPTION
**Pull request by nical**
This should work now. Fixes #2486.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2498)

### CODE REVIEW

**Comment by nical** [comment]
> This should work now.

Apparently not, looks like the new servo-tidy hasn't been published yet.

**Comment by glennw** [comment]
@nical What's the status of this now?

**Comment by nical** [comment]
Sorry I think I just need to ping someone who has the access to publish a fresh version of servo-tidy from the servo repo.

**Comment by nical** [comment]
Closing in favor of #2527.

**Pull request closed without merging**
