### PR TITLE
Switch to GLSL 1.30 on Linux.

### PR DESCRIPTION
**Pull request by glennw**
This should allow us to run under xvfb for CI testing.

### CODE REVIEW

**Comment by samlh** [comment]
```
src\device.rs:856:20: 856:34 error: unresolved name `SHADER_VERSION` [E0425]
src\device.rs:856         s.push_str(SHADER_VERSION);
                                     ^~~~~~~~~~~~~~
src\device.rs:856:20: 856:34 help: run `rustc --explain E0425` to see a detailed explanation
src\device.rs:856:20: 856:34 error: unresolved name `SHADER_VERSION` [E0425]
src\device.rs:856         s.push_str(SHADER_VERSION);
                                     ^~~~~~~~~~~~~~
src\device.rs:856:20: 856:34 help: run `rustc --explain E0425` to see a detailed explanation
error: aborting due to previous error
```

Missing the Windows case

**Comment by glennw** [comment]
@bors-servo retry

 * Travis issues

**Pull request merged**
