### PR TITLE
Add a command to list the resources used by a yaml file

### PR DESCRIPTION
**Pull request by jrmuizel**
I'd like to split this up into commits but am putting it here for now in case someone else wants it.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1764)

### CODE REVIEW

**Comment by kvark** [comment]
> ./wrench/src/yaml_frame_reader.rs:288: Line is longer than 120 characters
./wrench/src/yaml_frame_reader.rs:20: encountered whitespace following a use statement

**Comment by glennw** [comment]
It seems fine to merge this as a single commit - probably good to have it in the repo. Will need a rebase though.

**Comment by kvark** [comment]
Thank you!
@bors-servo r+

**Pull request merged**
