### PR TITLE
Text UV clamping

### LINKED ISSUE #2252: zoomed in blurred text shadows generate garbage bounding box fragments
Try zooming in and out on this page:

```
data:text/html,<meta charset="utf-8"><span style="text-shadow: 2px 2px 1px red"><div>Blur<span style="color: blue">%F0%9F%8E%89</span><span style="color: rgba(0,0,0,0.7)">%F0%9F%8E%89</span><span style="color: rgba(0,0,255,0.4)">%F0%9F%8E%89</span><span style="color: transparent">%F0%9F%8E%89</span><span style="text-shadow: 2px 2px 2px red"></span></div><div>Blur<span style="color: blue">A</span><span style="color: rgba(0,0,0,0.7)">A</span><span style="color: rgba(0,0,255,0.4)">A</span><span style="color: transparent">A</span></div></span>
```

screen shot 2018-01-03 at 4 10 48 pm

### PR DESCRIPTION
**Pull request by kvark**
Fixes #2252

Delivered to you with help of the new [capture infrastructure](http://kvark.github.io/webrender/debug/ron/2018/01/23/wr-capture-infra.html).

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2338)

### CODE REVIEW

**Comment by glennw** [comment]
Is there any way we could add a reftest for this when https://github.com/servo/webrender/pull/2335 lands (which has support for zoom reftests in wrench)?

@bors-servo r+

**Comment by kvark** [comment]
> Is there any way we could add a reftest for this when #2335 lands (which has support for zoom reftests in wrench)?

Technically possible. Trouble comes from the fact the bug depends on the contents of the texture cache, which is an internal mechanism we have, and we don't control it by the reftests... Well, unless we start collecting WR captures for reftesting ;)

**Comment by glennw** [comment]
We'd have to be a bit careful to clear each valid render task rect after the debug clear, I guess.

**Comment by kvark** [comment]
@glennw sounds good

**Pull request merged**
