### PR TITLE
Stop using `glBlitFramebuffer()` for scaling tasks.

### LINKED ISSUE #3088: Stop using glBlitFramebuffer() for downsampling
If the source and destination sizes are different, then the implementation is allowed to read outside the source uv rect. See the spec verbiage:

> If a linear filter is selected and sampling would be required outside the bounds of the specified source region, but within the bounds of a source buffer, the implementation may choose to clamp while sampling or not.

I believe that this is causing stray pixels to appear when I make changes to the blur filter. The solution should be to use a custom fragment shader for this that properly clamps to the source region.

### PR DESCRIPTION
**Pull request by pcwalton**
The driver is allowed to read outside of the source rect, and this can cause
incorrect results.

This patch makes `preserve-3d.png` test have some minor rounding differences in
its colors from the previous implementation, so I regenerated the reference
image.

Closes #3088.

r? @gw3583

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/3098)

### CODE REVIEW

**Comment by gw3583** [comment]
CI warnings error:

```
error: unused import: `ScalingInfo`
  --> webrender/src/renderer.rs:74:53
   |
74 | use tiling::{Frame, RenderTarget, RenderTargetKind, ScalingInfo, TextureCacheRenderTarget};
   |                                                     ^^^^^^^^^^^
   |
   = note: `-D unused-imports` implied by `-D warnings`

```

**Comment by pcwalton** [comment]
@gw3583 OK, I fixed that issue. I still can't push to try yet because my hg access was disabled for inactivity, though.

**Comment by nical** [comment]
try push: https://treeherder.mozilla.org/#/jobs?repo=try&revision=b15f823f8cb73908e770d973b90316a5b4689d6b

**Comment by pcwalton** [comment]
I don't understand what's going on on try.

**Comment by pcwalton** [comment]
Kicked off a try build: https://treeherder.mozilla.org/#/jobs?repo=try&revision=2ef0e6a9b321a1197d5eeee9aac514b4ab960f85

I verified that the browser works, so I'm not sure why the previous build failed.

**Comment by pcwalton** [comment]
@gw3583 This is the most recent try: https://treeherder.mozilla.org/#/jobs?repo=try&revision=bc356ef3f3f4b15b324607b374e285052b95c0d2&selectedJob=200912030

**Comment by gw3583** [comment]
CI failures:

```
REFTEST INFO | 308 passing, 3 failing
Reftests with unexpected results:
	reftests/boxshadow/inset-border-radius.yaml == reftests/boxshadow/inset-border-radius.png
	reftests/filters/filter-blur.yaml == reftests/filters/filter-blur.png
	reftests/snap/preserve-3d.yaml == reftests/snap/preserve-3d.png

```

**Pull request merged**
