### PR TITLE
Fix box shadow regression.

### PR DESCRIPTION
**Pull request by glennw**
The box shadow shader vertex format was incorrectly being set
to primitive instances instead of the new vertex format.

On some implementations, this happened to work correctly. On
mac, the default vertex attribute binding meant that this bug
showed up there.

This change removes the vertex format enum, which is redundant
with the vertex array kind enum, and fixes the box shadow shader
to bind to the correct vertex format.

As a follow up, I'll make the shader compilation code assert
if a vertex attribute binding fails.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1666)

### CODE REVIEW

**Comment by glennw** [comment]
r? @kvark 

cc @Gankro @jrmuizel

**Comment by glennw** [comment]
This fixes the recent box shadow issues on mac. It was a genuine bug, but the default attribute binding order meant the bug didn't show up on Linux/Intel or Mesa.

**Comment by kvark** [comment]
Thanks for tracking this down!
@bors-servo r+

**Comment by glennw** [comment]
I ... don't know how we ended up with two enums. Must have been asleep that day :)

**Pull request merged**
