### PR TITLE
Basic Memory Reporting for WebRender

### PR DESCRIPTION
**Pull request by bholley**
Reviewed by gw in https://bugzilla.mozilla.org/show_bug.cgi?id=1480293

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/3057)

### CODE REVIEW

**Comment by kvark** [comment]
@bholley I don't see gw there. Did you mean @jrmuizel ?

**Comment by bholley** [comment]
> @bholley I don't see gw there. Did you mean @jrmuizel ?

No, @gw3583 reviewed as well. Check the phabricator revision (mirroring between phabricator review status and bugzilla review flags is buggy and being removed, per recent email to dev-platform).

**Comment by kvark** [comment]
bors delegate+

**Comment by kvark** [comment]
I mean
@bors-servo delegate+

**Pull request merged**
