### PR TITLE
Add config for Travis CI.

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by larsbergstrom** [comment]
@frewsxcv The fix for this doc bug is described here:
https://github.com/servo/servo/issues/9704#issuecomment-186383858

**Comment by frewsxcv** [comment]
Latest force push

```diff
diff --git a/src/batch_builder.rs b/src/batch_builder.rs
index d340d9a..a259b4b 100644
--- a/src/batch_builder.rs
+++ b/src/batch_builder.rs
@@ -1168,14 +1168,14 @@ impl<'a> BatchBuilder<'a> {
     /// The following diagram attempts to explain the parameters to this function. It's an enlarged
     /// version of a border corner that looks like this:
     ///
-    /// ```
+    /// ```ignore
     /// ╭─
     /// │
     /// ```
     ///
     /// The parameters are as follows:
     ///
-    /// ```
+    /// ```ignore
     /// ⤹ corner_bounds.origin
     /// ∙┈┈┈┈┈┬┈┈┈┈┈┬┈┈┈┈┈
     /// ┊   ╱ ┊     ┊
```

**Pull request merged**
