### PR TITLE
Update euclid to 0.18

### PR DESCRIPTION
**Pull request by Eijebong**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2904)

### CODE REVIEW

**Comment by staktrace** [comment]
This PR seems to have caused some panics in Firefox CI, see https://bugzilla.mozilla.org/show_bug.cgi?id=1476636#c1

**Comment by staktrace** [comment]
Here's a sample log: https://treeherder.mozilla.org/logviewer.html#?job_id=188772693&repo=try&lineNumber=1438

**Comment by nical** [comment]
The panic is because this https://github.com/servo/webrender/pull/2904/files#diff-9c1d8b23da9e37ae3377086804c5aaf2L588 used to always have `Some(transformed rect)` and now can have `None` since transforming a rect is fallible in the latest euclid, since https://github.com/servo/euclid/pull/291.

cc @kvark 

I suppose that in this case we could cull out entirely the rects that we couldn't project.

**Pull request merged**
