### PR TITLE
Clip stack collapse path

### PR DESCRIPTION
**Pull request by kvark**
Based on #581
Implements the 3rd option explained in https://github.com/servo/webrender/pull/581#issuecomment-262657539 as an optional code path, controlled by `CLIP_TASK_COLLAPSE`, enabled by default.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/595)

### CODE REVIEW

**Comment by glennw** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[webrender/src/tiling.rs, line 616 at r1](https://reviewable.io:443/reviews/servo/webrender/595#-KXd8M3BsVBvUV6QRiTI:-KXd8M3CgqKoZ7Vd2hxA:bveidhm) ([raw file](https://github.com/servo/webrender/blob/8db149b2be80504ed78dce4153b60e8be2f63fc5/webrender/src/tiling.rs#L616)):*
> ```Rust
>                         let mask_task_index = match ctx.layer_masks_tasks.get(&(task.tile_id, sc_index)) {
>                             Some(ref mask_task_id) => render_tasks.get_task_index(mask_task_id, child_pass_index),
>                             None => RenderTaskIndex(i32::MAX as usize), // special sentinel value recognized by the shader
> ```

This should be OPAQUE_TASK_INDEX I think.

---

*[webrender/src/tiling.rs, line 1750 at r1](https://reviewable.io:443/reviews/servo/webrender/595#-KXd92vnHfQiPgk8bCAI:-KXd92vocDRj1Q5rVvnO:bt4caig) ([raw file](https://github.com/servo/webrender/blob/8db149b2be80504ed78dce4153b60e8be2f63fc5/webrender/src/tiling.rs#L1750)):*
> ```Rust
> 
>     fn build(self, passes: &mut Vec<RenderPass>) {
>         //println!("{:#?}", self.main_render_task);
> ```

Can be removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/595)*

**Comment by glennw** [comment]
@kvark This looks great! Two very minor nits, then it looks good to me.

Before merging, I'd like to just get @mrobinson to make sure the stacking context interface change is OK. Instead of having an overflow rect in the stacking context, the method to push a new stacking context now takes a clip region, which can be a normal rect, but could include an image mask etc. Does this interface change have any implications for the scroll root code?

**Comment by kvark** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[webrender/src/tiling.rs, line 616 at r1](https://reviewable.io:443/reviews/servo/webrender/595#-KXd8M3BsVBvUV6QRiTI:-KXflC_d9hvCWE9CnpyT:b-gs9178) ([raw file](https://github.com/servo/webrender/blob/8db149b2be80504ed78dce4153b60e8be2f63fc5/webrender/src/tiling.rs#L616)):*
<details><summary><i>Previously, glennw (Glenn Watson) wrote…</i></summary><blockquote>

This should be OPAQUE_TASK_INDEX I think.
</blockquote></details>

That was added when I needed it on multiple occasions, but it was removed later on. Anyway, I re-added it back now :)

---

*[webrender/src/tiling.rs, line 1750 at r1](https://reviewable.io:443/reviews/servo/webrender/595#-KXd92vnHfQiPgk8bCAI:-KXflKi5JoodEUSDd7tP:b32wtd) ([raw file](https://github.com/servo/webrender/blob/8db149b2be80504ed78dce4153b60e8be2f63fc5/webrender/src/tiling.rs#L1750)):*
<details><summary><i>Previously, glennw (Glenn Watson) wrote…</i></summary><blockquote>

Can be removed
</blockquote></details>

ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/595)*

**Comment by kvark** [comment]
All concerns are addressed, and the PR is rebased now.

**Pull request merged**
