### PR TITLE
Bump bitflags to 1.0

### PR DESCRIPTION
**Pull request by Eijebong**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1879)

### CODE REVIEW

**Comment by glennw** [comment]
Why do we need to allow duplicate packages in the ```servo-tidy``` script?

**Comment by Eijebong** [comment]
Because of clap which still depends on 0.9 :/ https://github.com/kbknapp/clap-rs/pull/1063

**Comment by glennw** [comment]
@Eijebong Ah, thanks for the info. ```clap``` is only used by wrench, so I guess this should be fine for Servo.

@bors-servo r+

**Comment by glennw** [comment]
@Eijebong Oh, wait - is the rustc stable version requirement going to cause an issue for Gecko compiling against WR?

**Comment by Eijebong** [comment]
https://github.com/servo/servo/pull/18809#issuecomment-336662383 Shouldn't be an issue anymore no :)

**Comment by glennw** [comment]
@bors-servo r+

:+1:

**Pull request merged**
