### PR TITLE
Separate out debug and release builds.

### PR DESCRIPTION
**Pull request by jrmuizel**
This should let us run them in parallel.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/882)

### CODE REVIEW

**Comment by glennw** [comment]
Looks good to me - let's see what travis makes of it and check the reported build times.

**Comment by jrmuizel** [comment]
Looks like this needs some modification to not fail

**Comment by glennw** [comment]
@jrmuizel I guess the potential problem with this is that we now need 2 mac builds per run, which might be a problem since there is often a mac builder backlog? Happy to merge this anyway and see how it goes, if you like?

**Comment by jrmuizel** [comment]
Yeah, let's merge it and see how things go.

**Pull request merged**
