### PR TITLE
Box shadow with border radius properly clips

### PR DESCRIPTION
**Pull request by changm**
Fixes issue https://github.com/servo/webrender/issues/189

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/950)

### CODE REVIEW

**Comment by changm** [comment]
I'm not sure how you feel about having the display list builder auto generate the clip versus having users explicitly provide a clip for the border-radius. I can move the clip building generation into the display list builder if you'd prefer.

**Comment by glennw** [comment]
I'm a bit unsure about merging this.

It fixes the common case for box shadows, where there is only a single (complex) clip, which is an improvement on what we have now.

On the other hand, inverting the clip mask is a hack that won't work correctly if the box shadow happens to intersect with any other complex clips. Making this work correctly will require proper support for clip in / clip out, or achieving it in a different way.

What do you think @kvark ?

**Comment by glennw** [comment]
@kvark @changm I wonder if we could add support to the clip mask generation to handle clip in / out fairly simply. I haven't thought about the details much yet, but we have multiple color channels available in the render task for clip masks. Perhaps we could accumulate clip in separately from clip out in two channels, and then the do_clip() shader code can sample both the clip in/out channels and combine them?

**Comment by kvark** [comment]
> On the other hand, inverting the clip mask is a hack that won't work correctly if the box shadow happens to intersect with any other complex clips. Making this work correctly will require proper support for clip in / clip out, or achieving it in a different way.

The clip mask output by `do_clip` is final, it hides all combining and inversion that happens during the mask generation. So I consider it safe to invert it for the box shadow case, given that it needs to clip "out" as opposed to clip "in".

> but we have multiple color channels available in the render task for clip masks.

I'd rather not use the other channels. Instead, I'd want the clip stuff to go into a single-channel render target, which would reduce the bandwidth cost and improve the texture cache performance upon sampling from it.

My only small-ish concern about the PR that it introduces another shader. If the box shadows are not omnipresent on the pages, we could just enable the clip logic for all of them.

**Comment by kvark** [comment]
I regress, @glennw concern is valid. We should add a mode to clip mask generation that would invert it. We should not invert it in the client (ps_box_shadow) shader.

**Comment by glennw** [comment]
Closing this (for now). We'll add support to clip mask generation for in/out, and then the box shadow change should be straightforward.

**Pull request closed without merging**
