### PR TITLE
Update core-foundation and core-graphics

### PR DESCRIPTION
**Pull request by jrmuizel**
I don't think we want to land this yet, but I'm posting it to avoid anybody duplicating the work.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2728)

### CODE REVIEW

**Comment by kvark** [comment]
Looks fine by me.
> I don't think we want to land this yet

what are the concerns?

**Comment by jrmuizel** [comment]
I want to let some other dependencies update first. That way we don't end up with lots of versions of core-graphics.

**Comment by jrmuizel** [comment]
Also, we could wait for https://github.com/servo/core-foundation-rs/pull/213 which will make this patch use even less unsafe.

**Comment by gw3583** [comment]
@jrmuizel Should we keep this open?

**Pull request closed without merging**
