### PR TITLE
Assert that depth targets are bound when depth features are used

### PR DESCRIPTION
**Pull request by bholley**
Dzmitry asked for this during review on another PR.

Differential Revision: https://phabricator.services.mozilla.com/D9954

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/3243)

### CODE REVIEW

**Comment by bholley** [comment]
> error[E0658]: use of unstable library feature 'libc': use `libc` from crates.io (see issue #27783)

**Comment by bholley** [comment]
@kvark needs a clobber or something?

**Comment by bholley** [comment]
Huh. I guess we're not gating on the OSX jobs then?

**Comment by staktrace** [comment]
We do gate on OSX. All the tests passed on the merge commit though: https://tools.taskcluster.net/groups/elQ-bVgVQiubofBZo1sL5A

**Comment by bholley** [comment]
Huh. I wonder what the difference is with the job I was looking at (one of the ones displayed at the bottom of the PR while it's pending). That one had compile bustage in a dependent crate (rand IIUC).

**Comment by gw3583** [comment]
Somehow we seem to have a compile error intermittent - I've seen it on three PRs now, I think. :astonished:

**Comment by gw3583** [comment]
(I wonder if there is a different rustc version on some CI machines or something like that?)

**Comment by staktrace** [comment]
Looks like the failure was on the CI for the PR (as opposed to the merge commit that homu makes): https://tools.taskcluster.net/groups/cXFabj8VShOh073dXzZe5A

In this case, yes, the failure is non-blocking. FWIW the failed run happened on the wr-toronto-1 mac mini and I'm not sure offhand which version of rust is on that, if that's the problem.

**Comment by staktrace** [comment]
According to https://tools.taskcluster.net/provisioners/localprovisioner/worker-types/webrender-ci-osx/workers/wr-toronto/wr-toronto-1 the worker doesn't seem to be failing everything, so there's some nondeterminism coming from somewhere.

**Pull request merged**
