### PR TITLE
Create DisplayListFlattener and move all flattening code there

### PR DESCRIPTION
**Pull request by mrobinson**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2468)

### CODE REVIEW

**Comment by mrobinson** [comment]
This is a reduction in the amount of code, but the line count is almost neutral to the additional documentation.

**Comment by nical** [comment]
It's too bad git couldn't figure out that frame.rs was renamed and destroyed/recreated all of its code (making digging in the history harder).

**Comment by mrobinson** [comment]
@nical This is two commits and it seems if you look just at the first commit the rename is detected properly: https://github.com/servo/webrender/pull/2468/commits/559f8c334cc8a6a4a5715fe2dbc103e7a42e1bac

**Pull request merged**
