### PR TITLE
Inline serialize_fast

### PR DESCRIPTION
**Pull request by jrmuizel**
Currently we get an implementation of serialize_fast specialized for
DisplayItem. If we inline serialize_fast we'll hopefully be able to
specialize for each individual display item. This should also save
some copying of DisplayItem around.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2151)

### CODE REVIEW

**Comment by Gankro** [comment]
I don't understand, there is only one display item (SpecificDisplayItem)?

**Comment by Gankro** [comment]
Oh wait I see. This is a case where it could literally pessimize our codegen, I’d like to see some actual profiling for this one (might also need to inline push_item)

**Comment by jrmuizel** [comment]
So it seems like inline(always) doesn't actually. Note the call to serialize_fast below:
```asm
+0x00	pushq               %rbp
+0x01	movq                %rsp, %rbp
+0x04	pushq               %r15
+0x06	pushq               %r14
+0x08	pushq               %r13
+0x0a	pushq               %r12
+0x0c	pushq               %rbx
+0x0d	subq                $728, %rsp
+0x14	movq                %r8, -56(%rbp)
+0x18	movq                %rcx, %r8
+0x1b	movq                %rdx, %r15
+0x1e	movq                %rsi, -48(%rbp)
+0x22	movq                %rdi, %r12
+0x25	movq                (%r9), %rax
+0x28	movq                8(%r9), %rcx
+0x2c	movq                %rcx, -96(%rbp)
+0x30	movq                %rax, -104(%rbp)
+0x34	testq               %r8, %r8
+0x37	je                  "webrender_api::display_list::DisplayListBuilder::push_text::h7f34d99ab7c7122b+0x2dd"
+0x3d	leaq                -304(%rbp), %r9
+0x44	leaq                -640(%rbp), %r13
+0x4b	nopl                (%rax,%rax)
+0x50	cmpq                $2038, %r8
+0x57	movl                $2038, %ebx
+0x5c	cmovbq              %r8, %rbx
+0x60	testq               %r15, %r15
+0x63	je                  "webrender_api::display_list::DisplayListBuilder::push_text::h7f34d99ab7c7122b+0x2dd"
+0x69	movq                -104(%rbp), %rax
+0x6d	movq                -96(%rbp), %rcx
+0x71	movq                %rcx, -112(%rbp)
+0x75	movq                %rax, -120(%rbp)
+0x79	movl                $31, %ecx
+0x7e	movq                %r9, %rdi
+0x81	leaq                -764(%rbp), %rsi
+0x88	rep
+0x89	movsl               (%rsi), %es:(%rdi)
+0x8a	movq                40(%r12), %rax
+0x8f	testq               %rax, %rax
+0x92	je                  "webrender_api::display_list::DisplayListBuilder::push_text::h7f34d99ab7c7122b+0x2ef"
+0x98	leaq                (%rbx,%rbx,2), %r14
+0x9c	movq                24(%r12), %rcx
+0xa1	imulq               $56, %rax, %rax
+0xa5	movq                -8(%rcx,%rax), %rdx
+0xaa	movq                %rdx, -128(%rbp)
+0xae	movq                -16(%rcx,%rax), %rdx
+0xb3	movq                %rdx, -136(%rbp)
+0xba	movq                -24(%rcx,%rax), %rdx
+0xbf	movq                %rdx, -144(%rbp)
+0xc6	movq                -32(%rcx,%rax), %rdx
+0xcb	movq                %rdx, -152(%rbp)
+0xd2	movq                -40(%rcx,%rax), %rdx
+0xd7	movq                %rdx, -160(%rbp)
+0xde	movq                -56(%rcx,%rax), %rdx
+0xe3	movq                -48(%rcx,%rax), %rax
+0xe8	leaq                (%r15,%r14,4), %rcx
+0xec	movq                %rcx, -64(%rbp)
+0xf0	subq                %rbx, %r8
+0xf3	movq                %r8, -72(%rbp)
+0xf7	movq                %rax, -168(%rbp)
+0xfe	movq                %rdx, -176(%rbp)
+0x105	movl                $6, -640(%rbp)
+0x10f	movq                -56(%rbp), %rax
+0x113	movq                %rax, -636(%rbp)
+0x11a	movq                -120(%rbp), %rax
+0x11e	movq                -112(%rbp), %rcx
+0x122	leaq                -628(%rbp), %rdx
+0x129	movq                %rcx, 8(%rdx)
+0x12d	movq                %rax, (%rdx)
+0x130	movq                16(%rbp), %rax
+0x134	movq                %rax, -612(%rbp)
+0x13b	movl                $31, %ecx
+0x140	leaq                -604(%rbp), %rdi
+0x147	movq                %r9, %rsi
+0x14a	rep
+0x14b	movsl               (%rsi), %es:(%rdi)
+0x14c	movq                -128(%rbp), %rax
+0x150	movq                %rax, 196(%rdx)
+0x157	movq                -136(%rbp), %rax
+0x15e	movq                %rax, 188(%rdx)
+0x165	movq                -144(%rbp), %rax
+0x16c	movq                %rax, 180(%rdx)
+0x173	movq                -152(%rbp), %rax
+0x17a	movq                %rax, 172(%rdx)
+0x181	movq                -160(%rbp), %rax
+0x188	movq                %rax, 164(%rdx)
+0x18f	movq                -176(%rbp), %rax
+0x196	movq                -168(%rbp), %rcx
+0x19d	movq                %rcx, 156(%rdx)
+0x1a4	movq                %rax, 148(%rdx)
+0x1ab	movl                $15, %ecx
+0x1b0	leaq                -424(%rbp), %rdi
+0x1b7	movq                -48(%rbp), %rsi
+0x1bb	rep
+0x1bc	movsq               (%rsi), %es:(%rdi)
+0x1be	movq                %r12, %rdi
+0x1c1	movq                %r13, %rsi
+0x1c4	callq               "webrender_api::display_list::serialize_fast::h5ef0d49efa5a26b9"
+0x1c9	leaq                (%r15,%r14,4), %r13
+0x1cd	movq                16(%r12), %rax
+0x1d2	movq                %rax, -88(%rbp)
+0x1d6	movl                $8, %esi
+0x1db	movq                %r12, %rdi
+0x1de	callq               "_$LT$alloc..vec..Vec$LT$T$GT$$GT$::reserve::h356970f63983d5aa"
+0x1e3	movq                (%r12), %rax
+0x1e7	movq                16(%r12), %rcx
+0x1ec	movq                $0, (%rax,%rcx)
+0x1f4	addq                $8, %rcx
+0x1f8	movq                %rcx, 16(%r12)
+0x1fd	movl                $8, %esi
+0x202	movq                %r12, %rdi
+0x205	callq               "_$LT$alloc..vec..Vec$LT$T$GT$$GT$::reserve::h356970f63983d5aa"
+0x20a	movq                (%r12), %rax
+0x20e	movq                16(%r12), %rcx
+0x213	movq                %rbx, (%rax,%rcx)
+0x217	addq                $8, %rcx
+0x21b	movq                %rcx, -80(%rbp)
+0x21f	movq                %rcx, 16(%r12)
+0x224	leaq                -12(%r15,%r14,4), %rax
+0x229	subq                %r15, %rax
+0x22c	movabsq             $-6148914691236517205, %rcx
+0x236	mulq                %rcx
+0x239	shrq                $3, %rdx
+0x23d	leaq                (%rdx,%rdx,2), %rax
+0x241	leaq                12(,%rax,4), %r14
+0x249	movq                %r12, %rdi
+0x24c	movq                %r14, %rsi
+0x24f	callq               "_$LT$alloc..vec..Vec$LT$T$GT$$GT$::reserve::h356970f63983d5aa"
+0x254	movq                16(%r12), %rax
+0x259	movq                (%r12), %rcx
+0x25d	addq                %rax, %rcx
+0x260	movl                (%r15), %edx
+0x263	movl                %edx, (%rcx)
+0x265	movl                4(%r15), %edx
+0x269	movl                %edx, 4(%rcx)
+0x26c	movl                8(%r15), %edx
+0x270	movl                %edx, 8(%rcx)
+0x273	addq                $12, %r15
+0x277	addq                $12, %rcx
+0x27b	cmpq                %r13, %r15
+0x27e	jne                 "webrender_api::display_list::DisplayListBuilder::push_text::h7f34d99ab7c7122b+0x260"
+0x280	addq                %rax, %r14
+0x283	movq                %r14, 16(%r12)
+0x288	movq                %r14, %rbx
+0x28b	movq                -88(%rbp), %rdi
+0x28f	subq                %rdi, %rbx
+0x292	jb                  "webrender_api::display_list::DisplayListBuilder::push_text::h7f34d99ab7c7122b+0x2fb"
+0x294	subq                -80(%rbp), %r14
+0x298	addq                (%r12), %rdi
+0x29c	movq                %r14, -640(%rbp)
+0x2a3	cmpq                $8, %rbx
+0x2a7	movl                $8, %edx
+0x2ac	cmovbq              %rbx, %rdx
+0x2b0	leaq                -640(%rbp), %r13
+0x2b7	movq                %r13, %rsi
+0x2ba	callq               "DYLD-STUB$$memcpy"
+0x2bf	cmpq                $7, %rbx
+0x2c3	jbe                 "webrender_api::display_list::DisplayListBuilder::push_text::h7f34d99ab7c7122b+0x303"
+0x2c5	movq                -72(%rbp), %r8
+0x2c9	testq               %r8, %r8
+0x2cc	movq                -64(%rbp), %r15
+0x2d0	leaq                -304(%rbp), %r9
+0x2d7	jne                 "webrender_api::display_list::DisplayListBuilder::push_text::h7f34d99ab7c7122b+0x50"
+0x2dd	addq                $728, %rsp
+0x2e4	popq                %rbx
+0x2e5	popq                %r12
+0x2e7	popq                %r13
+0x2e9	popq                %r14
+0x2eb	popq                %r15
+0x2ed	popq                %rbp
+0x2ee	retq
+0x2ef	leaq                24397210(%rip), %rdi
+0x2f6	callq               "core::panicking::panic::h22082048e6f7992e"
+0x2fb	movq                %r14, %rsi
+0x2fe	callq               "core::slice::slice_index_order_fail::hb42c451ff17a8029"
+0x303	leaq                7789766(%rip), %rdi
+0x30a	movl                $28, %esi
+0x30f	callq               "std::error::_$LT$impl$u20$core..convert..From$LT$$RF$$u27$b$u20$str$GT$$u20$for$u20$alloc..boxed..Box$LT$std..error..Error$u20$$u2b$$u20$core..marker..Send$u20$$u2b$$u20$core..marker..Sync$u20$$u2b$$u20$$u27$a$GT$$GT$::from::hf5e2e291aebf44e6"
+0x314	movq                %rdx, %rcx
+0x317	leaq                -304(%rbp), %rdi
+0x31e	movl                $14, %esi
+0x323	movq                %rax, %rdx
+0x326	callq               "std::io::error::Error::_new::hcc6678c9a6c86322"
+0x32b	movq                -304(%rbp), %rax
+0x332	movq                -296(%rbp), %rcx
+0x339	movq                %rcx, -632(%rbp)
+0x340	movq                %rax, -640(%rbp)
+0x347	leaq                -640(%rbp), %rdi
+0x34e	callq               "bincode::internal::_$LT$impl$u20$core..convert..From$LT$std..io..error..Error$GT$$u20$for$u20$alloc..boxed..Box$LT$bincode..internal..ErrorKind$GT$$GT$::from::h651950071e4cba44"
+0x353	leaq                7789894(%rip), %rdi
+0x35a	movl                $43, %esi
+0x35f	movq                %rax, %rdx
+0x362	callq               "core::result::unwrap_failed::hfa54fdc8d0fef653"
```

**Comment by jrmuizel** [comment]
So upon investigation, inlining serialize_fast then requires push_item to be inlined but after they're both inlined we get a codegen disaster that will require some investigation.

**Pull request closed without merging**
