### PR TITLE
Add a .taskcluster.yml file to run CI using taskcluster

### PR DESCRIPTION
**Pull request by staktrace**
This is a test PR to see if (a) taskcluster correctly picks up the PR and schedules the CI jobs and (b) to see how bors/homu deal with this extra CI job.

This is related to #1724

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1746)

### CODE REVIEW

**Comment by staktrace** [comment]
Ok, that was anticlimactic. I'm not sure what's the best way forward here. Somebody who knows more about how the CI checks work with the bors/homu bots should chime in. Otherwise I'd say we should merge this PR but be ready to back it out if it causes problems. In theory the taskcluster jobs should always be green for good PRs so it should be safe to run them side-by-side with the travis CI until we're confident it doesn't break stuff.

**Comment by glennw** [comment]
@staktrace I'm fine with merging this - we can back it out if required. But why the change to fuzzy results in one of the reftests?

**Comment by staktrace** [comment]
@glennw On the taskcluster Linux machines that reftest gives slightly different
results so I had to tweak the reftest.list to make the test pass.

**Comment by staktrace** [comment]
I continued looking into what we need to complete the integration and posted to https://github.com/servo/webrender/issues/1724#issuecomment-331917517. Even without the integration complete, I think it would be valuable to merge this PR, because we'll get taskcluster running CI and can get results faster than via Travis. Even if bors/homu don't yet recognize those results, the human doing the PR can get feedback faster which would be valuable.

**Pull request merged**
