### PR TITLE
Add gradient border support.

### PR DESCRIPTION
**Pull request by mephisto41**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/953)

### CODE REVIEW

**Comment by glennw** [comment]
The CI-related failures to this are due to the sample / wrench code not being updated.

**Comment by glennw** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[webrender/res/ps_gradient.vs.glsl, line 19 at r1](https://reviewable.io:443/reviews/servo/webrender/953#-KeWT9nHfHrZvRTNQjJ4:-KeWT9nIc1oOjcAd0aP6:bo3syjr) ([raw file](https://github.com/servo/webrender/blob/654d589a0b7a8de221e0d64afb992179d42d5773/webrender/res/ps_gradient.vs.glsl#L19)):*
> ```GLSL
>                        gradient.start_end_point.z,
>                        g0.offset.x);
>         x0 = clamp(x0, prim.local_rect.p0.x, prim.local_rect.p0.x + prim.local_rect.size.x);
> ```

Could you add a comment explaining why the clamp is required here?

---

*[webrender/res/ps_gradient.vs.glsl, line 57 at r1](https://reviewable.io:443/reviews/servo/webrender/953#-KeWTF5RrmtovDjLqa4T:-KeWTF5RrmtovDjLqa4U:b-loteqs) ([raw file](https://github.com/servo/webrender/blob/654d589a0b7a8de221e0d64afb992179d42d5773/webrender/res/ps_gradient.vs.glsl#L57)):*
> ```GLSL
>                                  prim.task);
> 
>     vec2 f = (vi.local_pos - gradient.start_end_point.xy) / (gradient.start_end_point.zw - gradient.start_end_point.xy);
> ```

Why does this need to change?

---

*[webrender_traits/src/display_list.rs, line 190 at r1](https://reviewable.io:443/reviews/servo/webrender/953#-KeWTcDdfqbHBpPEGa1f:-KeWTcDeQhjtNamsn29B:bmt2fx7) ([raw file](https://github.com/servo/webrender/blob/654d589a0b7a8de221e0d64afb992179d42d5773/webrender_traits/src/display_list.rs#L190)):*
> ```Rust
>                        widths: BorderWidths,
>                        details: BorderDetails,
>                        stops: Option<Vec<GradientStop>>) {
> ```

I think we should remove stops here and just have it passed as part of the border details enum - that way, stops can only be provided for the gradient types.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/953)*

**Comment by glennw** [comment]
It would also be good to add some wrench reftests for this new functionality.

**Comment by mephisto41** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[webrender_traits/src/display_list.rs, line 190 at r1](https://reviewable.io:443/reviews/servo/webrender/953#-KeWTcDdfqbHBpPEGa1f:-KeX8iOe-0mmMKLdntLo:blq9z1) ([raw file](https://github.com/servo/webrender/blob/654d589a0b7a8de221e0d64afb992179d42d5773/webrender_traits/src/display_list.rs#L190)):*
<details><summary><i>Previously, glennw (Glenn Watson) wrote…</i></summary><blockquote>

I think we should remove stops here and just have it passed as part of the border details enum - that way, stops can only be provided for the gradient types.
</blockquote></details>

If I added stops in border details enum, the border details enum would become non-Copyable. But we need it to be copyable for all display item data structure. I have 2 options for solved this.

1. Add a BorderParameters which contains stop info and push_border take this as parameter. which means we add a struct
```rust
pub enum BorderParameter {
    Normal(NormalBorder),
    Image(ImageBorder),
    Gradient(GradientBorder, Vec<GradientStop>),
    RadialGradient(RadialGradientBorder, Vec<GradientStop>),
}
```
and push_border modified as follow
```rust
pub fn push_border(&mut self, clip: ClipRegion, widths: BorderWidths, details: BorderParameter)
```

2. Or add an function such as ```create_gradient``` and pass all gradient info included stops in ```DisplayListBuilder```. And this function will return a Gradient and we construct border details using this Gradient.

```rust
pub fn create_gradient(start_point: LayoutPoint, end_point: LayoutPoint, stops: Vec<GradientStop>, extend_mode: ExtendMode) -> Gradient
```

Or any other better ideas?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/953)*

**Comment by glennw** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[webrender_traits/src/display_list.rs, line 190 at r1](https://reviewable.io:443/reviews/servo/webrender/953#-KeWTcDdfqbHBpPEGa1f:-KeXEk78C5K0e3WRjBYl:b1rfy6f) ([raw file](https://github.com/servo/webrender/blob/654d589a0b7a8de221e0d64afb992179d42d5773/webrender_traits/src/display_list.rs#L190)):*
<details><summary><i>Previously, mephisto41 (Morris Tseng) wrote…</i></summary><blockquote>

If I added stops in border details enum, the border details enum would become non-Copyable. But we need it to be copyable for all display item data structure. I have 2 options for solved this.

1. Add a BorderParameters which contains stop info and push_border take this as parameter. which means we add a struct
```rust
pub enum BorderParameter {
    Normal(NormalBorder),
    Image(ImageBorder),
    Gradient(GradientBorder, Vec<GradientStop>),
    RadialGradient(RadialGradientBorder, Vec<GradientStop>),
}
```
and push_border modified as follow
```rust
pub fn push_border(&mut self, clip: ClipRegion, widths: BorderWidths, details: BorderParameter)
```

2. Or add an function such as ```create_gradient``` and pass all gradient info included stops in ```DisplayListBuilder```. And this function will return a Gradient and we construct border details using this Gradient.

```rust
pub fn create_gradient(start_point: LayoutPoint, end_point: LayoutPoint, stops: Vec<GradientStop>, extend_mode: ExtendMode) -> Gradient
```

Or any other better ideas?

</blockquote></details>

Ah yes, this is slightly trickier than I thought. Option (2) sounds like the right idea to me - it fits in similarly to how the other display items that involve ranges work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/953)*

**Comment by mephisto41** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[webrender/res/ps_gradient.vs.glsl, line 19 at r1](https://reviewable.io:443/reviews/servo/webrender/953#-KeWT9nHfHrZvRTNQjJ4:-KegO3vWN1Tch7P6tx3o:b-896fix) ([raw file](https://github.com/servo/webrender/blob/654d589a0b7a8de221e0d64afb992179d42d5773/webrender/res/ps_gradient.vs.glsl#L19)):*
<details><summary><i>Previously, glennw (Glenn Watson) wrote…</i></summary><blockquote>

Could you add a comment explaining why the clamp is required here?
</blockquote></details>

Done.

---

*[webrender/res/ps_gradient.vs.glsl, line 57 at r1](https://reviewable.io:443/reviews/servo/webrender/953#-KeWTF5RrmtovDjLqa4T:-KegO5jFJGJyFXA1ZAPQ:b-g50jt8) ([raw file](https://github.com/servo/webrender/blob/654d589a0b7a8de221e0d64afb992179d42d5773/webrender/res/ps_gradient.vs.glsl#L57)):*
<details><summary><i>Previously, glennw (Glenn Watson) wrote…</i></summary><blockquote>

Why does this need to change?
</blockquote></details>

I modified the code in newer patch to make this more clear.

---

*[webrender_traits/src/display_list.rs, line 190 at r1](https://reviewable.io:443/reviews/servo/webrender/953#-KeWTcDdfqbHBpPEGa1f:-KegOLp_s8VEgQdy0Bhg:b-896fix) ([raw file](https://github.com/servo/webrender/blob/654d589a0b7a8de221e0d64afb992179d42d5773/webrender_traits/src/display_list.rs#L190)):*
<details><summary><i>Previously, glennw (Glenn Watson) wrote…</i></summary><blockquote>

Ah yes, this is slightly trickier than I thought. Option (2) sounds like the right idea to me - it fits in similarly to how the other display items that involve ranges work.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/953)*

**Comment by mephisto41** [comment]
Should I bump the api version for this?

**Pull request merged**
