### PR TITLE
add a cache of all seen glyphs to the end of the display list

### PR DESCRIPTION
**Pull request by Gankro**
This lets the backend call `display_list.glyphs()` to get an iterator of every glyph seen (broken down by font/color) so that the backend can prepare glyph atlases or whatever in parallel.

This is for @glennw to build off of for #1503

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1518)

### CODE REVIEW

**Comment by glennw** [comment]
Nice!

@bors-servo r+

**Comment by kvark** [comment]
Needs a rebase

**Comment by Gankro** [comment]
Whoops, missed this. Fixed.

**Comment by glennw** [comment]
@Gankro Having recently done some testing and benchmarking of Sip / Fnv / Fx hash, this comment is a bit of a concern now:

```
FIXME: audit whether fast hashers (FNV?) are safe here
```

What would we need to do to find out if we can use FxHash here?

**Comment by glennw** [comment]
I have zero relevant security knowledge, but given we use ```FxHash``` internally now for the glyph and texture cache, we're probably no worse off using it during display list construction :)

Given that - are you happy to change this to use FxHash for the hasher type and we'll get this landed?

**Comment by Gankro** [comment]
Yeah sure.

**Comment by glennw** [comment]
Thanks, no rush on this from my end by the way - sorry if that wasn't clear from the comment above.

**Comment by Gankro** [comment]
Ok done. It didn't seem right to have webrender_api publically vendor this, so I just duplicated it in lib.rs.

**Comment by glennw** [comment]
CI failure:

```
error: `pub(restricted)` syntax is experimental (see issue #32409)

  --> webrender_api/src/lib.rs:58:5

   |

58 | pub(crate) type FastHashMap<K, V> = HashMap<K, V, BuildHasherDefault<fxhash::FxHasher>>;

   |     ^^^^^

error: `pub(restricted)` syntax is experimental (see issue #32409)

  --> webrender_api/src/lib.rs:59:5

   |

59 | pub(crate) type FastHashSet<T> = HashSet<T, BuildHasherDefault<fxhash::FxHasher>>;

   |     ^^^^^

error: aborting due to 2 previous errors

error: Could not compile `webrender_api`.
```

We are compiling against 1.17 which, I think, is the required rustc version for Gecko.

**Comment by Gankro** [comment]
Fixed. Forgot submodules can see private members of parents.

**Pull request merged**
