### PR TITLE
[WIP] Add coverage recording

### PR DESCRIPTION
**Pull request by jrmuizel**
Testing out coverage recording

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1229)

### CODE REVIEW

**Comment by jrmuizel** [comment]
This looks like it has the same segfault problem that I get when running locally. I wonder why https://github.com/codecov/example-rust/blob/master/.travis.yml works

**Comment by glennw** [comment]
@jrmuizel Do you want this kept open for now?

**Comment by jrmuizel** [comment]
Yeah, let's just keep it open until it works if you don't mind.

**Comment by jrmuizel** [comment]
It looks like the --verify flag was needed to get this working

**Comment by kvark** [comment]
> ./wrench/headless.py:70: Line is longer than 120 characters

**Comment by kvark** [comment]
Why do we have two identical `coverage` notifications?

**Comment by glennw** [comment]
@jrmuizel Do we still want this open? It will need to be rebased if we do...

**Comment by jrmuizel** [comment]
Yeah, though I wasn't getting the most useful data. I think it should probably be run on a debug build to get better information.

**Comment by glennw** [comment]
@jrmuizel semi-regular question on if you still want this open?

**Comment by jrmuizel** [comment]
Yeah, I'll try again at it when I care about it.

**Comment by glennw** [comment]
Closing since it hasn't been rebased for a long time. We can re-open when planning to work on this again.

**Pull request closed without merging**
