### PR TITLE
Sync changes from mozilla-central

### PR DESCRIPTION
**Pull request by moz-gfx**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/3695)

### CODE REVIEW

**Comment by jdm** [comment]
@staktrace Something is wrong the the taskcluster mac workers.

**Comment by staktrace** [comment]
@jrmuizel can you check on the Mac Mini?

**Comment by jrmuizel** [comment]
I'm not in the office today. I can look tomorrow.

**Pull request merged**
