### PR TITLE
Fix double border's border width.

### PR DESCRIPTION
**Pull request by demo99**
The double border seems to be broke. Maybe I should add a wrench test?

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/981)

### CODE REVIEW

**Comment by jrmuizel** [comment]
> Maybe I should add a wrench test?

Yes please.

**Comment by demo99** [comment]
@glennw r?

**Comment by glennw** [comment]
I'm not sure why these need to be a fuzzy reftest. Shouldn't they be exactly the same pixels? It seems like there is an issue in the double border drawing causing the fuzziness?

**Comment by demo99** [comment]
The fuzzy is due to the AA processing. Solid border calls 'draw_solid_border' and there is no AA processing for top/bottom/right/left. And double border uses 'alpha_for_solid_border' which has AA processing since we need to do some calculations to make it have two lines.

**Comment by glennw** [comment]
OK, so there's two problems here.

The initial bug is solved by this patch, but that then shows a bug in how the AA is working. If I reproduce this same test in Gecko, there's no AA on the double with border.

If we fix the AA up, then we won't need it to be a fuzzy reftest. But that is really a separate issue, so let's merge this and fix that as a follow up.

**Pull request merged**
