### PR TITLE
Query feature

### LINKED ISSUE #1860: Feature gate GPU queries
Would help #1755 and #1802

### PR DESCRIPTION
**Pull request by kvark**
Fixes #1860

Feature is disabled by default, but building is CI-tested. Not sure how to make it enabled for, say, debug on desktop?..

This PR comes with an assumption that Gecko will know when to build with it (e.g. for developer builds) and when to not (on ARM).

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1861)

### CODE REVIEW

**Comment by glennw** [comment]
Looks good, thanks!

@bors-servo r+

**Comment by glennw** [comment]
CI failures:

```
error: associated constants are experimental (see issue #29646)

   --> src/device.rs:557:5

    |

557 |     const MAX_TIMERS_PER_FRAME: usize = 256;

    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: associated constants are experimental (see issue #29646)

   --> src/device.rs:560:5

    |

560 |     const MAX_SAMPLERS_PER_FRAME: usize = 0;

    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error(s)
```

**Comment by kvark** [comment]
We have a rust update in #1829.
@bors-servo retry

**Comment by glennw** [comment]
@kvark Did some performance tests of this change.

With query timers enabled:
 Wikipedia compositor CPU time 2.0ms
 HN compositor CPU time 2.4ms

Without query timers enabled:
 Wikipedia compositor CPU time 1.3ms
 HN compositor CPU time 1.8ms

That's a nice, free performance win!

**Comment by staktrace** [comment]
@kvark for some reason this PR is causing cbindgen to fail when parsing the webrender crate. It looks more like a cbindgen problem than a problem with your patch but just a heads-up anyway. Details at https://bugzilla.mozilla.org/show_bug.cgi?id=1408461#c8 onwards.

**Comment by staktrace** [comment]
Filed #1887 with a possible fix

**Pull request merged**
