### PR TITLE
Glyph key scratch store

### PR DESCRIPTION
**Pull request by djg**
Implement scratch storage of GlyphKeys for #3324

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/3325)

### CODE REVIEW

**Comment by djg** [comment]
Try run result for first version: https://treeherder.mozilla.org/#/jobs?repo=try&revision=2a1353c60b3cedfea396330beab65b825170b821&selectedJob=212544428

**Comment by gw3583** [comment]
It'd be interesting to get some separate profiles of the change to use a scratch buffer vs. using the chunked storage. It may well be that a normal ```Vec``` with a reasonable ```reserve``` estimate up front is actually faster than the chunked storage?

Running ```benchmarks/text-rendering.yaml``` is a reasonable stress test of drawing a lot of text that is easy to profile within wrench. You'd need to run with ```-r``` though to replay the display list each time you hit right-arrow.

**Comment by kvark** [comment]
@djg try looks good, and my concerns are addressed (for the most part). Could you check that benchmark mentioned by @gw3583 before we go?

**Comment by djg** [comment]
I'll run the benchmark that @gw3583 mentioned once I get my current interning work to a good point.

@gw3583, I was thinking that sizing the initial storage to ~64KB

**Comment by gw3583** [comment]
(Discussed on IRC - I was initially misreading how the storage type works. This should be a simple win, and we'll extend it with recycle functionality as a follow up).

**Pull request merged**
