### PR TITLE
Make the pinch-zoom API a frame message instead of a scene message.

### LINKED ISSUE #3202: Adjusting the pinch zoom should be a frame operation, not a scene operation
Pinch zooming, like async scrolling, should be done on frames and should not require a scene rebuild. Right now both `set_page_zoom` and `set_pinch_zoom` are scene ops.

### PR DESCRIPTION
**Pull request by staktrace**
Fixes #3202.

There might be other issues that are exposed by this, not sure yet. But it's a start.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/3203)

### CODE REVIEW

**Comment by nical** [comment]
I think that it makes sense to move the pinch zoom to a frame message since `DisplayListFlattener::create_frame_builder` doesn't seem to access it. We should probably split the `DocumentView` struct into things that scene building needs and things that only matter for frame building.

**Comment by staktrace** [comment]
Note that `create_frame_builder` does use the `accumulated_scale_factor()` here: https://searchfox.org/mozilla-central/rev/c9272ef398954288525e37196eada1e5a93d93bf/gfx/webrender/src/display_list_flattener.rs#212 which includes the pinch zoom value. I don't really understand the purpose of that though.

**Comment by nical** [comment]
D'oh! You are right I spoke too fast. This affects `resolved_transform` in `SpatialNodeType::ReferenceFrame` which itself looks like it isn't affecting scene building (I think?). the `resolved_transform` member doesn't seem to need to be persisted at all. I tried removing the member and adapting the code in `SpatialNode::update_transform` to use a variable on the stack instead of overwriting the removed member and it compiles.

**Comment by staktrace** [comment]
Ah yes, I remember seeing that `resolved_transform` thing when I was working on the parallax bug. I think the only place it's used as a member variable is in `print_node` and I don't know how important it is there, seems like just debugging output.

**Comment by kvark** [comment]
> I tried removing the member and adapting the code in SpatialNode::update_transform to use a variable on the stack instead of overwriting the removed member and it compiles.

Should we do it first (or as a part of this PR) then before merging?

**Comment by staktrace** [comment]
Sure, if you're ok with me taking it out of the `print_node` code I can add it to this PR.

**Comment by staktrace** [comment]
Patches updated ^

**Comment by kvark** [comment]
@bors-servo delegate+
(leaving a chance for a try push, if needed)

**Comment by kvark** [comment]
Try isn't needed (as per IRC discussion).
@bors-servo r+

**Pull request merged**
