### PR TITLE
Remove the tiling code.

### PR DESCRIPTION
**Pull request by glennw**
We now have solutions for all the parts of the renderer that previously relied on tiling for
efficiency.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/750)

### CODE REVIEW

**Comment by kvark** [comment]
Review status: 0 of 20 files reviewed at latest revision, 10 unresolved discussions.

---

*[webrender/res/prim_shared.glsl, line 150 at r1](https://reviewable.io:443/reviews/servo/webrender/750#-KbEAdKoX6sVGjg73xAW:-KbEAdKpucqihUXqy9CQ:b-ddvonm) ([raw file](https://github.com/servo/webrender/blob/d8424dd7174431f35edf26b287bb9a666680f82a/webrender/res/prim_shared.glsl#L150)):*
> ```GLSL
> 
> struct AlphaBatchTask {
>     vec2 screen_space_origin;
> ```

nicely done!

---

*[webrender/res/prim_shared.glsl, line 502 at r1](https://reviewable.io:443/reviews/servo/webrender/750#-KbEC1ddipmW0SDWNCaG:-KbEC1ddipmW0SDWNCaH:beo6jsc) ([raw file](https://github.com/servo/webrender/blob/d8424dd7174431f35edf26b287bb9a666680f82a/webrender/res/prim_shared.glsl#L502)):*
> ```GLSL
> 
>     // apply the task offset
>     vec2 final_pos = device_pos - task.screen_space_origin + task.render_target_origin;
> ```

this is way clearer now, :+1: 

---

*[webrender/res/ps_composite.vs.glsl, line 12 at r1](https://reviewable.io:443/reviews/servo/webrender/750#-KbED1Bn_45yGRPgE1QB:-KbED1Bn_45yGRPgE1QC:b-mion0m) ([raw file](https://github.com/servo/webrender/blob/d8424dd7174431f35edf26b287bb9a666680f82a/webrender/res/ps_composite.vs.glsl#L12)):*
> ```GLSL
>     AlphaBatchTask src_task = fetch_alpha_batch_task(pi.user_data.y);
> 
>     vec2 dest_origin = dest_task.render_target_origin -
> ```

hmm, this seem to diverge from the old code:
Was: `dest.task_origin`
Now: `dest.task_origin - dest.screen_origin + src.screen_origin`

---

*[webrender/res/ps_composite.vs.glsl, line 22 at r1](https://reviewable.io:443/reviews/servo/webrender/750#-KbEDrFr-vso5FevtBbs:-KbEDrFr-vso5FevtBbt:bk6c50b) ([raw file](https://github.com/servo/webrender/blob/d8424dd7174431f35edf26b287bb9a666680f82a/webrender/res/ps_composite.vs.glsl#L22)):*
> ```GLSL
>     vec2 texture_size = vec2(textureSize(sCache, 0));
> 
>     vec2 st0 = (backdrop_task.render_target_origin + vec2(0.0, backdrop_task.size.y)) / texture_size;
> ```

these `st0` and `st1` have also diverged from the original. You are essentially Y-flipping the `backdrop_task` UVs. Is this intentional?

---

*[webrender/src/renderer.rs, line 1062 at r1](https://reviewable.io:443/reviews/servo/webrender/750#-KbEGFNQxZMom7iBrglV:-KbEGFNQxZMom7iBrglW:bgpft8) ([raw file](https://github.com/servo/webrender/blob/d8424dd7174431f35edf26b287bb9a666680f82a/webrender/src/renderer.rs#L1062)):*
> ```Rust
>                 self.device.bind_draw_target(Some(cache_draw_target), Some(cache_texture_dimensions));
> 
>                 let src_x = backdrop.data[0] - backdrop.data[4] + source.data[4];
> ```

ok, yes, this is a bit (too much) hacky

---

*[webrender/src/renderer.rs, line 1115 at r1](https://reviewable.io:443/reviews/servo/webrender/750#-KbEGMkiNrJRgCfajiqQ:-KbEGMkiNrJRgCfajiqR:b-75ywm7) ([raw file](https://github.com/servo/webrender/blob/d8424dd7174431f35edf26b287bb9a666680f82a/webrender/src/renderer.rs#L1115)):*
> ```Rust
>         let projection = {
>             let _gm = self.gpu_profile.add_marker(GPU_TAG_SETUP_TARGET);
>             self.device.bind_read_target(render_target);
> ```

why is this needed?

---

*[webrender/src/tiling.rs, line 182 at r1](https://reviewable.io:443/reviews/servo/webrender/750#-KbEGi6Ddn0g9emjSIy4:-KbEGi6EFPi3VIJfmiCj:b-7mtcfk) ([raw file](https://github.com/servo/webrender/blob/d8424dd7174431f35edf26b287bb9a666680f82a/webrender/src/tiling.rs#L182)):*
> ```Rust
>         batch.items.push(PrimitiveBatchItem::StackingContext(layer_index));
> 
>         match &mut batch.data {
> ```

pretty sure you can get away without `&mut` here and the line below

---

*[webrender/src/tiling.rs, line 430 at r1](https://reviewable.io:443/reviews/servo/webrender/750#-KbEGzJRuqE94cBn4Ali:-KbEGzJSWbo-oZ3E3dzV:bxykf2j) ([raw file](https://github.com/servo/webrender/blob/d8424dd7174431f35edf26b287bb9a666680f82a/webrender/src/tiling.rs#L430)):*
> ```Rust
>     /// Apply a horizontal blur pass of given radius for this primitive.
>     HorizontalBlur(i32, PrimitiveIndex),
>     /// Allocate a block of space in target for framebuffer readback.
> ```

I think using `readback` term here is confusing. Perhaps, change it to `backup` or even `copy`?

---

*[webrender/src/tiling.rs, line 652 at r1](https://reviewable.io:443/reviews/servo/webrender/750#-KbEHxEo-q0sJ7tztDYd:-KbEHxEpkmDrtrc9MMIb:bp5z21v) ([raw file](https://github.com/servo/webrender/blob/d8424dd7174431f35edf26b287bb9a666680f82a/webrender/src/tiling.rs#L652)):*
> ```Rust
> 
>                         if intersects {
>                             break 'outer;
> ```

what is the point of early-out here? I don't see any side effects in this inner loop body, so it doesn't seem like anything changes at all if we drop out early. Perhaps, you forgot to assign `alpha_batch_index` after the loop?

---

*[webrender/src/tiling.rs, line 2605 at r1](https://reviewable.io:443/reviews/servo/webrender/750#-KbEKFqNfje6_2frb6aI:-KbEKFqO6ABE_ajcjkxP:bl36vtr) ([raw file](https://github.com/servo/webrender/blob/d8424dd7174431f35edf26b287bb9a666680f82a/webrender/src/tiling.rs#L2605)):*
> ```Rust
>                         let prim_index = PrimitiveIndex(first_prim_index.0 + i);
> 
>                         if let Some(..) = self.prim_store.cpu_bounding_rects[prim_index.0] {
> ```

nit: could just check for `is_some()` instead of a pattern match

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/750)*

**Comment by kvark** [comment]
Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/750)*

**Comment by kvark** [comment]
The change looks fantastic! I've got a few concerns to clarify before proceeding.

---

Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/750#-:-KbEKtPAX18VA1P4xTDU:b-5635at)*

**Comment by glennw** [comment]
Thanks for the review! I'll fix these up in the morning and push an updated / rebased version then.

**Comment by glennw** [comment]
Review status: 17 of 20 files reviewed at latest revision, 10 unresolved discussions.

---

*[webrender/res/ps_composite.vs.glsl, line 12 at r1](https://reviewable.io:443/reviews/servo/webrender/750#-KbED1Bn_45yGRPgE1QB:-KbHjCDa2jHUlJNcq9s3:b-vh1620) ([raw file](https://github.com/servo/webrender/blob/d8424dd7174431f35edf26b287bb9a666680f82a/webrender/res/ps_composite.vs.glsl#L12)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

hmm, this seem to diverge from the old code:
Was: `dest.task_origin`
Now: `dest.task_origin - dest.screen_origin + src.screen_origin`
</blockquote></details>

The previous blend code worked on tiles only, so didn't need to take into account offsets of the stacking context within a render target.

---

*[webrender/res/ps_composite.vs.glsl, line 22 at r1](https://reviewable.io:443/reviews/servo/webrender/750#-KbEDrFr-vso5FevtBbs:-KbHjLyfMDOIssyWgJ8k:besydup) ([raw file](https://github.com/servo/webrender/blob/d8424dd7174431f35edf26b287bb9a666680f82a/webrender/res/ps_composite.vs.glsl#L22)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

these `st0` and `st1` have also diverged from the original. You are essentially Y-flipping the `backdrop_task` UVs. Is this intentional?
</blockquote></details>

Yep - reading back from the framebuffer as we do now for composites is upside-down from rendering to a FBO and then sampling it as a texture.

---

*[webrender/src/renderer.rs, line 1062 at r1](https://reviewable.io:443/reviews/servo/webrender/750#-KbEGFNQxZMom7iBrglV:-KbHjXaxv1URhiqWQLR_:bpiatn3) ([raw file](https://github.com/servo/webrender/blob/d8424dd7174431f35edf26b287bb9a666680f82a/webrender/src/renderer.rs#L1062)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

ok, yes, this is a bit (too much) hacky
</blockquote></details>

Yep - I'm going to try and tidy this up today. It's a bit tricky since these values aren't known until quite late in the frame (once the render target allocation has been done). Have you got any suggestions on a cleaner way to do this? I could perhaps make specific structs and implement From on them, for the RenderTaskData, but I'm open to any other ideas here.

---

*[webrender/src/renderer.rs, line 1115 at r1](https://reviewable.io:443/reviews/servo/webrender/750#-KbEGMkiNrJRgCfajiqQ:-KbHjqU7SpHOXyaD__5p:bmmx5fj) ([raw file](https://github.com/servo/webrender/blob/d8424dd7174431f35edf26b287bb9a666680f82a/webrender/src/renderer.rs#L1115)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

why is this needed?
</blockquote></details>

It's not - fixed :)

---

*[webrender/src/tiling.rs, line 182 at r1](https://reviewable.io:443/reviews/servo/webrender/750#-KbEGi6Ddn0g9emjSIy4:-KbHjsjL_opc7qTkd-cK:b-886gsx) ([raw file](https://github.com/servo/webrender/blob/d8424dd7174431f35edf26b287bb9a666680f82a/webrender/src/tiling.rs#L182)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

pretty sure you can get away without `&mut` here and the line below
</blockquote></details>

Fixed

---

*[webrender/src/tiling.rs, line 430 at r1](https://reviewable.io:443/reviews/servo/webrender/750#-KbEGzJRuqE94cBn4Ali:-KbHjtcbHPQO6dBTXAtC:bx2jatz) ([raw file](https://github.com/servo/webrender/blob/d8424dd7174431f35edf26b287bb9a666680f82a/webrender/src/tiling.rs#L430)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

I think using `readback` term here is confusing. Perhaps, change it to `backup` or even `copy`?
</blockquote></details>

Changed to CopyFramebuffer - is that clearer?

---

*[webrender/src/tiling.rs, line 652 at r1](https://reviewable.io:443/reviews/servo/webrender/750#-KbEHxEo-q0sJ7tztDYd:-KbHlOsxOnj5oCesTpCV:bsz04oo) ([raw file](https://github.com/servo/webrender/blob/d8424dd7174431f35edf26b287bb9a666680f82a/webrender/src/tiling.rs#L652)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

what is the point of early-out here? I don't see any side effects in this inner loop body, so it doesn't seem like anything changes at all if we drop out early. Perhaps, you forgot to assign `alpha_batch_index` after the loop?
</blockquote></details>

What it's saying is that as soon as it encounters an intersection with something in the batch it's looking at, stop considering any of the other batches before that. Instead, we just force creation of a new batch in that case.

---

*[webrender/src/tiling.rs, line 2605 at r1](https://reviewable.io:443/reviews/servo/webrender/750#-KbEKFqNfje6_2frb6aI:-KbHk-IuwQN44m9JqTir:b-886gsx) ([raw file](https://github.com/servo/webrender/blob/d8424dd7174431f35edf26b287bb9a666680f82a/webrender/src/tiling.rs#L2605)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

nit: could just check for `is_some()` instead of a pattern match
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/750)*

**Comment by kvark** [comment]
Thanks for the fixes! :lgtm:

---

Review status: 17 of 20 files reviewed at latest revision, 4 unresolved discussions.

---

*[webrender/res/ps_composite.vs.glsl, line 22 at r1](https://reviewable.io:443/reviews/servo/webrender/750#-KbEDrFr-vso5FevtBbs:-KbLY7ZrifX8stMBttRq:b-sv987y) ([raw file](https://github.com/servo/webrender/blob/d8424dd7174431f35edf26b287bb9a666680f82a/webrender/res/ps_composite.vs.glsl#L22)):*
<details><summary><i>Previously, glennw (Glenn Watson) wrote…</i></summary><blockquote>

Yep - reading back from the framebuffer as we do now for composites is upside-down from rendering to a FBO and then sampling it as a texture.
</blockquote></details>

why do we need to read it upside-down?

---

*[webrender/src/renderer.rs, line 1062 at r1](https://reviewable.io:443/reviews/servo/webrender/750#-KbEGFNQxZMom7iBrglV:-KbLYMua-s1PtzhwZ4TM:bik0qbj) ([raw file](https://github.com/servo/webrender/blob/d8424dd7174431f35edf26b287bb9a666680f82a/webrender/src/renderer.rs#L1062)):*
<details><summary><i>Previously, glennw (Glenn Watson) wrote…</i></summary><blockquote>

Yep - I'm going to try and tidy this up today. It's a bit tricky since these values aren't known until quite late in the frame (once the render target allocation has been done). Have you got any suggestions on a cleaner way to do this? I could perhaps make specific structs and implement From on them, for the RenderTaskData, but I'm open to any other ideas here.
</blockquote></details>

I'm fine with this as a follow-up. And yes, looks like implementing `From` for some nice structs is the way to go.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/750#-:-KbLZvRKpCdQIlJhaJuD:b-zgdw96)*

**Comment by glennw** [comment]
Review status: 17 of 20 files reviewed at latest revision, 4 unresolved discussions.

---

*[webrender/res/ps_composite.vs.glsl, line 22 at r1](https://reviewable.io:443/reviews/servo/webrender/750#-KbEDrFr-vso5FevtBbs:-KbMDYirvuJPa3H8YECa:bxio9ox) ([raw file](https://github.com/servo/webrender/blob/d8424dd7174431f35edf26b287bb9a666680f82a/webrender/res/ps_composite.vs.glsl#L22)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

why do we need to read it upside-down?
</blockquote></details>

This is just the nature of how the GL coordinate system and glBlitFramebuffer works, as far as I know?

---

*[webrender/src/renderer.rs, line 1062 at r1](https://reviewable.io:443/reviews/servo/webrender/750#-KbEGFNQxZMom7iBrglV:-KbMDhPrLKhVIcrBpveN:b-4dxi2r) ([raw file](https://github.com/servo/webrender/blob/d8424dd7174431f35edf26b287bb9a666680f82a/webrender/src/renderer.rs#L1062)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

I'm fine with this as a follow-up. And yes, looks like implementing `From` for some nice structs is the way to go.
</blockquote></details>

Sounds good - I'll file a follow up bug to fix this then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/750)*

**Comment by kvark** [comment]
Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[webrender/res/ps_composite.vs.glsl, line 22 at r1](https://reviewable.io:443/reviews/servo/webrender/750#-KbEDrFr-vso5FevtBbs:-KbODlLnxkKmKFA2w7dv:bic8egf) ([raw file](https://github.com/servo/webrender/blob/d8424dd7174431f35edf26b287bb9a666680f82a/webrender/res/ps_composite.vs.glsl#L22)):*
<details><summary><i>Previously, glennw (Glenn Watson) wrote…</i></summary><blockquote>

This is just the nature of how the GL coordinate system and glBlitFramebuffer works, as far as I know?
</blockquote></details>

Well, glBlitFramebuffer doesn't flip anything upside down unless requested. And GL coordinate system shouldn't be a problem if we are using it consistently. But I don't want to push for any changes here if it works, we can revisit it later on.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/750)*

**Pull request merged**
