### PR TITLE
Add two new rectangle structures in webrender.

### PR DESCRIPTION
**Pull request by mephisto41**
This is for issue #887

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/903)

### CODE REVIEW

**Comment by glennw** [comment]
Reviewed 6 of 7 files at r1.
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[webrender/res/ps_border.vs.glsl, line 85 at r1](https://reviewable.io:443/reviews/servo/webrender/903#-KdSu0OH0NFJBDUWVZsr:-KdSu0OIS_s9_Jc3ZrGX:b8nn5m9) ([raw file](https://github.com/servo/webrender/blob/2bd13ace90c4093709a5ad54704d6c54952ff498/webrender/res/ps_border.vs.glsl#L85)):*
> ```GLSL
>         case PST_BOTTOM_LEFT:
>             segment_rect.p0 = vec2(bl_outer.x, bl_inner.y);
>             segment_rect.size = vec2(bl_inner.x - bl_outer.x, bl_outer.y - br_inner.y);
> ```

typo here (br_inner.y instead of bl_inner.y)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/903)*

**Comment by glennw** [comment]
Looks good - just one typo, then this should be good to merge.

**Comment by glennw** [comment]
Once that typo is fixed, let's squash the commits together too - then this should be ready to go.

**Comment by mephisto41** [comment]
Done, thanks for reviewing.

**Comment by glennw** [comment]
@bors-servo r+

Thanks!

**Pull request merged**
