### PR TITLE
Remove IPC API.

### PR DESCRIPTION
**Pull request by jdm**
This removes the use of ipc-channel. I would love to remove the Serialize/Deserialize lies as well, but last time I tried to do that proved harder than I anticipated.

### CODE REVIEW

**Comment by kvark** [comment]
Why is this done?

**Comment by jrmuizel** [comment]
```
./Cargo.lock:1: duplicates for `crossbeam-utils` are allowed, but only single version found
	The following packages depend on version 0.2.2 from 'crates.io':
		crossbeam-deque
		crossbeam-epoch
```

**Comment by jrmuizel** [comment]
the ipc-channel usage isn't need anymore because of https://github.com/servo/servo/commit/564c16d75499ae45b3945f487e49587c6fd662c7

**Comment by jdm** [comment]
Fixed the tidy issue.

**Comment by kvark** [comment]
> error: Package `webrender_api v0.60.0 (/home/worker/webrender/webrender_api)` does not have these features: `ipc`

**Comment by atouchet** [comment]
This was done in #3850.

**Pull request closed without merging**
