### PR TITLE
Sync changes from mozilla-central gfx/wr

### PR DESCRIPTION
**Pull request by moz-gfx**

### CODE REVIEW

**Comment by staktrace** [comment]
@jdm bors taking a holiday too?

**Comment by jdm** [comment]
@staktrace Github's webhooks had a bunch of issues today, so the latest push to the branch wasn't delivered to the homu webhook. This situation can be identified by comparing the hash that homu is reporting is approved against the hash of the latest commit in the branch.

**Comment by staktrace** [comment]
@jdm Good to know, thanks!

**Pull request merged**
