### PR TITLE
Add a reftest for rounded clips under extreme perspective.

### LINKED ISSUE #2421: Border radius clip problem with perspective transforms
Failing test case:

https://gist.github.com/pcwalton/07bd4ae28e953553c20fda0dfa257334

Screen shot:

https://i.imgur.com/PFOPzWx.png

### PR DESCRIPTION
**Pull request by pcwalton**
Closes #2421.

r? @gw3583

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/3083)

### CODE REVIEW

**Comment by kvark** [comment]
> max difference: 9, number of differing pixels: 348

:rofl: 
Let's fuzz it some more?

**Comment by pcwalton** [comment]
Off-by-one error!

**Pull request merged**
