### PR TITLE
Use a newer rustc on CI, to possibly workaround a rustc compiler bug.

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/812)

### CODE REVIEW

**Comment by jrmuizel** [comment]
FWIW, it would probably be good to be using same version of rustc that we use in the gecko CI

**Comment by glennw** [comment]
@jrmuizel Agreed - where can I find out that information?

**Comment by glennw** [comment]
We'll push this as a commit in the PR that is causing issues, so can close this.

**Pull request closed without merging**
