### PR TITLE
 Remove AlphaBatchTask, and introduce start of raster mode. 

### PR DESCRIPTION
**Pull request by glennw**
Most of the difficult work related to this was done in the
large picture PR that landed previously.

This removes the remnants of AlphaBatch tasks, and makes them
all run through Picture render tasks.

This also introduces the first part of the picture and shader
side support for selecting whether primitives on a given picture
are to be rasterized in screen space or a local space.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2053)

### CODE REVIEW

**Comment by glennw** [comment]
r? @kvark 

This patch isn't as big as it seems - it just includes https://github.com/servo/webrender/pull/2052 which is a prerequisite. If it's easier to review and land #2052 first, and then review this - that's cool, otherwise I can close #2052 and just get them both reviewed here at the same time.

I'll kick off a gecko try run with this shortly.

**Comment by glennw** [comment]
Pending try is here https://treeherder.mozilla.org/#/jobs?repo=try&revision=8b82697f5d521d9e07fc45dd874b36c88ccd57cb - all the orange results are expected due to previous PRs, from what I can tell (but the try is not quite finished yet).

**Comment by kvark** [comment]
Where does this one come from? https://treeherder.mozilla.org/logviewer.html#?job_id=145504579&repo=try&lineNumber=4811

**Comment by mstange** [comment]
The first one is known, see https://bugzilla.mozilla.org/show_bug.cgi?id=1417062#c18 .

**Comment by mstange** [comment]
And `same-filter.html` has existing fuzz: `fuzzy-if(webrender,15-15,8274-8274)`.
The reftest failure says `max difference: 14, number of differing pixels: 8286`

**Comment by kvark** [comment]
:lgtm: minus a few points mentioned, also the fact it's based on a PR where I requested more changes

---

Reviewed 14 of 14 files at r2.
Review status: 14 of 18 files reviewed at latest revision, 3 unresolved discussions.

---

*[webrender/res/prim_shared.glsl, line 290 at r1](https://reviewable.io:443/reviews/servo/webrender/2053#-KzAis4S2em0HWc6sIUL:-KzAis4Tjr4sRtW4ov5h:b-hdvacm) ([raw file](https://github.com/servo/webrender/blob/999c9bec0821c9c2131993371d1b37f9d62858a3/webrender/res/prim_shared.glsl#L290)):*
> ```GLSL
> }
> 
> struct AlphaBatchTask {
> ```

hooray!

---

*[webrender/src/picture.rs, line 44 at r2](https://reviewable.io:443/reviews/servo/webrender/2053#-KzAjEyBHKfvTOJLSN_A:-KzAjEyBHKfvTOJLSN_B:b5h6yr8) ([raw file](https://github.com/servo/webrender/blob/c4955a4e43572f1482afb57ed4854087b5b89d3e/webrender/src/picture.rs#L44)):*
> ```Rust
> #[repr(C)]
> #[derive(Debug, Copy, Clone)]
> pub enum RasterizationMode {
> ```

shouldn't this be `RasterizationSpace::Local/Screen` instead?

---

*[webrender/src/render_task.rs, line 286 at r2](https://reviewable.io:443/reviews/servo/webrender/2053#-KzAjd7qarqeT7Rf29Sk:-KzAjd7qarqeT7Rf29Sl:b-in05iq) ([raw file](https://github.com/servo/webrender/blob/c4955a4e43572f1482afb57ed4854087b5b89d3e/webrender/src/render_task.rs#L286)):*
> ```Rust
>         prim_index: PrimitiveIndex,
>         target_kind: RenderTargetKind,
>         content_origin_x: f32,
> ```

any reason this is not just `LayerPoint`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/2053#-:-KzAkEUhfB0B6zjkRVHH:b-tborac)*

**Comment by glennw** [comment]
Review status: 14 of 18 files reviewed at latest revision, 3 unresolved discussions.

---

*[webrender/src/picture.rs, line 44 at r2](https://reviewable.io:443/reviews/servo/webrender/2053#-KzAjEyBHKfvTOJLSN_A:-KzL-AOdz4YmK0olKPzs:b-896fix) ([raw file](https://github.com/servo/webrender/blob/c4955a4e43572f1482afb57ed4854087b5b89d3e/webrender/src/picture.rs#L44)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

shouldn't this be `RasterizationSpace::Local/Screen` instead?
</blockquote></details>

Done.

---

*[webrender/src/render_task.rs, line 286 at r2](https://reviewable.io:443/reviews/servo/webrender/2053#-KzAjd7qarqeT7Rf29Sk:-KzL-Ax2l2BqA8BWtSs8:b-jy9ylj) ([raw file](https://github.com/servo/webrender/blob/c4955a4e43572f1482afb57ed4854087b5b89d3e/webrender/src/render_task.rs#L286)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

any reason this is not just `LayerPoint`?
</blockquote></details>

When rasterization space is Screen - it's a device space content origin, not a layer origin. As a follow up, I'd like to make this type safe - by moving content origin to be part of the rasterization space enum.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/2053)*

**Comment by glennw** [comment]
I messed up and pushed this branch to the #2052 after addressing review comments. Closing this as #2052 has both commits and comments addressed from both reviews.

**Pull request closed without merging**
