### PR TITLE
Sync changes from mozilla-central

### PR DESCRIPTION
**Pull request by moz-gfx**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/3753)

### CODE REVIEW

**Comment by jrmuizel** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1580543 should help here.

**Comment by jrmuizel** [comment]
We're now timing out on appveyor because of the double building: https://github.com/servo/mozangle/issues/28#issuecomment-530610862

**Comment by Eijebong** [comment]
This looks a lot like a 100 minutes timeout

**Pull request merged**
