### PR TITLE
Support arbitrary rasterization coordinate roots.

### PR DESCRIPTION
**Pull request by gw3583**
This allows us to choose to rasterize any picture in an
arbitrary coordinate space.

This fixes a large number of real world pages that use 3d
transforms. It also simplifies fixing any remaining 3d
transform related issues.

The initial patch uses this to promote any picture that has
perspective into a rasterization root.

There are a number of benefits to this:
 * It simplifies a lot of the math involving plane splitting,
   since we don't need to deal with splits drawn in screen-space.
 * It makes caching perspective rendered pictures much easier,
   since we can cache them between frames even when the
   root coordinate system is animating the picture (this isn't
   implemented yet, but is a simple-ish follow up).

We can make use of this to render text shadows in local space,
as a performance optimization (which can then be cached between
frames and display lists).

Part of this change involves simplifying the plane splitting
code to work in a similar way to traditional brush images. It's
likely that in the future we can completely remove ps_split_composite
and draw plane splits with brush_image for better batching.

Introducing a new coordinate space allows for some more optimal
calculations of required raster rectangles, which reduces the
number of pixels that we draw for clip masks and transformed
pictures, in some cases.

Follow ups:
 * Support arbitrary rasterization scales for raster roots, for
   better quality / performance.
 * Support caching of pictures as discussed above.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/3030)

### CODE REVIEW

**Comment by gw3583** [comment]
r? @kvark 

This needs some more code documentation - but I thought I'd open the PR now anyway, and work on the remaining bits tomorrow. This fixes a lot of real world pages that have 3d transforms on them.

Try run:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=5274c24e237d09c87f21693974d11b7aa1332250

There are 2 FAILs in R6 that I need to look into, and 1 new PASS in Wr1.

(I'll do a full try run on all platforms once I resolve those 2 FAILs tomorrow).

:tada:

**Comment by gw3583** [comment]
(includes the fix in https://github.com/servo/webrender/pull/3029)

**Comment by pcwalton** [comment]
Note that this will possibly be needed to optimize blur as well, because right now there's no way to render contents at a lower resolution without introducing more transforms, which necessitate stacking contexts and reference frames.

**Comment by gw3583** [comment]
Current try:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=57331aff6e49b2ec1003a85abff4b4130dd0e3ff

Down to one failure - working through that now, then will follow up on and address review comments :)

**Comment by kvark** [comment]
I confirm (by downloading the last try artifact) that the PR fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1487570
:tada: :tada: :tada:

**Comment by gw3583** [comment]
Addressed most of those review comments. Still working on one reftest failure, and then a couple of tidy up comments from above still need to be addressed.

**Comment by gw3583** [comment]
Try run looks good so far (still in progress):

https://treeherder.mozilla.org/#/jobs?repo=try&revision=3e29fc7c6924f333afd5418aed4854ac32255937

1 new PASS in Wr1.
2x new PASS in R1 (OSX).
Unrelated intermittent in R8 and 15.

Bugzilla bugs that are affected by this change:

FIXED:
	https://bugzilla.mozilla.org/show_bug.cgi?id=1487570
	https://bugzilla.mozilla.org/show_bug.cgi?id=1470905
	https://bugzilla.mozilla.org/show_bug.cgi?id=1421526
	https://bugzilla.mozilla.org/show_bug.cgi?id=1451087 (https://github.com/servo/webrender/issues/2587)
	https://bugzilla.mozilla.org/show_bug.cgi?id=1454706 (still some flickering in places)
	https://bugzilla.mozilla.org/show_bug.cgi?id=1483647

IMPROVED:
	https://bugzilla.mozilla.org/show_bug.cgi?id=1415272
	https://bugzilla.mozilla.org/show_bug.cgi?id=1422051

**Comment by gw3583** [comment]
Try run looks good. The same new PASS results on Windows, plus a couple unrelated intermittents. re-r? @kvark

**Comment by gw3583** [comment]
@kvark Thanks! Responded to those comments / quesions and pushed an updated commit.

**Comment by gw3583** [comment]
:rocket:

**Comment by gw3583** [comment]
Just pushed an amended commit to try and get bors to respond, but no luck so far :cry:

**Pull request merged**
