### PR TITLE
clamp_rect Angle workaround

### LINKED ISSUE #1324: ps_image shader compile error in angle, '_clamp_rect': ambiguous function call
The latest WR update into gecko resulted in a new failure on Windows QR reftests. ([Full log](https://treeherder.mozilla.org/logviewer.html#?job_id=103721042&repo=graphics&lineNumber=2277))

Relevant output:
```
08:08:30     INFO - WebRender - OpenGL version new OpenGL ES 3.0 (ANGLE 2.1.0.dec065540d5f)
08:08:30     INFO - Failed to link shader program: "ps_image"
08:08:30     INFO - C:\fakepath(968,14-36): error X3067: '_clamp_rect': ambiguous function call
08:08:30     INFO - Warning: D3D shader compilation failed with default flags. (vs_5_0)
08:08:30     INFO -  Retrying with skip validation
08:08:30     INFO - C:\fakepath(968,14-36): error X3067: '_clamp_rect': ambiguous function call
08:08:30     INFO - Warning: D3D shader compilation failed with skip validation flags. (vs_5_0)
08:08:30     INFO -  Retrying with skip optimization
08:08:30     INFO - C:\fakepath(968,14-36): error X3067: '_clamp_rect': ambiguous function call
08:08:30     INFO - Warning: D3D shader compilation failed with skip optimization flags. (vs_5_0)
08:08:30     INFO - Failed to create D3D shaders.
08:08:30     INFO - thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Link("ps_image", "C:\\fakepath(968,14-36): error X3067: \'_clamp_rect\': ambiguous function call\n\nWarning: D3D shader compilation failed with default flags. (vs_5_0)\n Retrying with skip validation\nC:\\fakepath(968,14-36): error X3067: \'_clamp_rect\': ambiguous function call\n\nWarning: D3D shader compilation failed with skip validation flags. (vs_5_0)\n Retrying with skip optimization\nC:\\fakepath(968,14-36): error X3067: \'_clamp_rect\': ambiguous function call\n\nWarning: D3D shader compilation failed with skip optimization flags. (vs_5_0)\n\n\n\nFailed to create D3D shaders.\n")', src\libcore\result.rs:859
08:08:31     INFO - stack backtrace:
08:08:31     INFO -    0: <unknown>
08:08:31     INFO -    1: <unknown>
08:08:31     INFO -    2: <unknown>
08:08:31     INFO -    3: <unknown>
08:08:31     INFO -    4: <unknown>
08:08:31     INFO -    5: <unknown>
08:08:31     INFO -    6: <unknown>
08:08:31     INFO -    7: glWaitSync
08:08:31     INFO -    8: <unknown>
08:08:31     INFO -    9: <unknown>
08:08:31     INFO -   10: <unknown>
08:08:31     INFO -   11: <unknown>
08:08:31     INFO -   12: ANGLEPlatformShutdown
08:08:31     INFO -   13: <unknown>
08:08:31     INFO -   14: <unknown>
08:08:31     INFO -   15: <unknown>
08:08:31     INFO -   16: <unknown>
08:08:31     INFO -   17: <unknown>
08:08:31     INFO -   18: soundtouch::SoundTouch::`vftable'
08:08:31     INFO -   19: <unknown>
08:08:31     INFO -   20: <unknown>
08:08:31     INFO -   21: <unknown>
08:08:31     INFO -   22: <unknown>
08:08:31     INFO -   23: <unknown>
08:08:31     INFO -   24: <unknown>
08:08:31     INFO -   25: <unknown>
08:08:31     INFO -   26: <unknown>
08:08:31     INFO -   27: <unknown>
```

### PR DESCRIPTION
**Pull request by kvark**
Fixes #1324
(hopefully)
cc @staktrace 
r? anyone

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1325)

### CODE REVIEW

**Comment by glennw** [comment]
r=me but could we add a comment / link to the driver issue somewhere explaining the problem?

**Comment by kvark** [comment]
@glennw I thought about doing that once @staktrace can confirm that it helps. E.g. in a similar #1311 my workaround didn't help right away.

**Comment by staktrace** [comment]
I kicked off a [try push](https://treeherder.mozilla.org/#/jobs?repo=try&revision=1fb9afbc163a91a80ac932d491434d129218dbdb) with this change but it's taking a while to get the results back. win8 machines have a backlog.

**Comment by staktrace** [comment]
This fixed the clamp_angle problem but there is another similar one with intersect_rect. I'll file a new issue for that, I guess.

**Pull request merged**
