### PR TITLE
Revert "Use debug assertions to check WebGL errors"

### PR DESCRIPTION
**Pull request by glennw**
This reverts commit 57c5cd430e2360ef4e3fc4473be25bc313979d35.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1167)

### CODE REVIEW

**Comment by glennw** [comment]
Unfortunately this breaks a number of tests in the WPT suite - reverting for now so that we can land the WR update.

**Comment by kvark** [comment]
I'm curious, how does checking/non-checking for GL errors ended up affecting the reftests?

**Comment by glennw** [comment]
@kvark I think what probably happens is that the GL error check results in a glFlush call internally, which is affecting the reftests on OSMesa. That's just a guess though - I haven't confirmed.

**Pull request merged**
