### PR TITLE
Resurrect non-premultiplied alpha codepath for use in Gecko

### PR DESCRIPTION
**Pull request by staktrace**
I think we need this to fix some canvas reftests that have been failing for a long time. See bug https://bugzilla.mozilla.org/show_bug.cgi?id=1429951 for the gecko side patch, which has the list of failing reftests.

Also I don't really know this code well, most of this patch is just copy-paste, so please let me know if I'm way off base here.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2295)

### CODE REVIEW

**Comment by glennw** [comment]
@mstange @kvark Do you know why we would need this? It seems like we should be able to handle these cases without introducing a non-premultiplied alpha path again, but I haven't looked closely at the tests in question.

**Comment by mstange** [comment]
WebGL lets you specify `premultipliedAlpha: false` in the [WebGLContextAttributes](https://www.khronos.org/registry/webgl/specs/latest/1.0/#WEBGLCONTEXTATTRIBUTES). Then the WebGL canvas needs to be composited using unpremultiplied alpha.

**Comment by glennw** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[webrender/src/prim_store.rs, line 192 at r1](https://reviewable.io:443/reviews/servo/webrender/2295#-L2rB3CXYQ_lops6-CFb:-L2rB3CXYQ_lops6-CFc:b-8u92nm) ([raw file](https://github.com/servo/webrender/blob/a9dbc7be24367b8e57323cddf2400e42f38538dd/webrender/src/prim_store.rs#L192)):*
> ```Rust
>     pub is_backface_visible: bool,
>     pub screen_rect: Option<DeviceIntRect>,
>     pub non_premultiplied: bool,
> ```

Could we change the logic of this to be ```premultiplied``` and the default to be true? It reads a bit easier to not have a negative here, I think.

---

*[webrender/src/renderer.rs, line 3544 at r1](https://reviewable.io:443/reviews/servo/webrender/2295#-L2rBDwano0JOQTAfDGV:-L2rBDwano0JOQTAfDGW:bw5rb2u) ([raw file](https://github.com/servo/webrender/blob/a9dbc7be24367b8e57323cddf2400e42f38538dd/webrender/src/renderer.rs#L3544)):*
> ```Rust
> 
>                         match batch.key.blend_mode {
>                             BlendMode::Alpha => {
> ```

I think this can probably be a ```panic```. We should never end up in the path where we are compositing text primitives that are not premultiplied.

---

*[webrender_api/src/display_item.rs, line 70 at r1](https://reviewable.io:443/reviews/servo/webrender/2295#-L2rBRIfdvGtCchCW2RO:-L2rBRIfdvGtCchCW2RP:b-5oyhps) ([raw file](https://github.com/servo/webrender/blob/a9dbc7be24367b8e57323cddf2400e42f38538dd/webrender_api/src/display_item.rs#L70)):*
> ```Rust
>     pub local_clip: LocalClip,
>     pub is_backface_visible: bool,
>     pub non_premultiplied: bool,
> ```

Can we make this a property of the ```Image``` display item instead of a generic property that applies to all primitives? That way the comment above (about text prims) becomes irrelevant, we don't pay the memory cost of extra bool for every item. I think that should cover what we need, since this only applies to webgl images?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/2295)*

**Comment by staktrace** [comment]
> Can we make this a property of the Image display item instead of a generic property that applies 
> to all primitives? That way the comment above (about text prims) becomes irrelevant, we don't 
> pay the memory cost of extra bool for every item. I think that should cover what we need, since 
> this only applies to webgl images?

We can do this, but it will mean passing around this extra bool through a bunch of functions like create_primitive and add_primitive. That was the main reason I put it into the LayerPrimitiveInfo, so that it would avoid polluting the function signatures.

**Comment by kvark** [comment]
Review status: 0 of 17 files reviewed at latest revision, 3 unresolved discussions.

---

*[webrender/src/prim_store.rs, line 192 at r1](https://reviewable.io:443/reviews/servo/webrender/2295#-L2rB3CXYQ_lops6-CFb:-L2v09I01T44zFmpU8-4:bn7ng97) ([raw file](https://github.com/servo/webrender/blob/a9dbc7be24367b8e57323cddf2400e42f38538dd/webrender/src/prim_store.rs#L192)):*
<details><summary><i>Previously, glennw (Glenn Watson) wrote…</i></summary><blockquote>

Could we change the logic of this to be ```premultiplied``` and the default to be true? It reads a bit easier to not have a negative here, I think.
</blockquote></details>

Perhaps, we should just use an `enum` for that. Passing true/false in many places is not idiomatic, since it's not clear what it means without checking the function signatures.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/2295)*

**Comment by staktrace** [comment]
> Perhaps, we should just use an enum for that. Passing true/false in many places is not idiomatic, 
> since it's not clear what it means without checking the function signatures.

Before I go and do this, can you take a look at the second patch I added and let me know if you prefer making that change or not? (Without this second patch, the flag is on PrimitiveInfo, but with the patch it's in ImageDisplayItem and then gets propagated to a bunch of function signatures as an extra parameter).

Also, if I convert it to an enum, is it fine to just one have enum exposed in the display_item.rs file and use that everywhere, or do you want a frontend/backend separation, with another enum defined in webrender/ somewhere?

**Comment by glennw** [comment]
(Discussed on IRC) I think if we store the bool (or enum) in the ```ImagePrimitiveCpu``` struct, we should be able to avoid any changes to fn signatures.

**Comment by glennw** [comment]
Having one enum is fine, I think.

**Comment by staktrace** [comment]
Updated patch to use one AlphaType enum and propagate it via ImagePrimitiveCpu. ^

**Comment by glennw** [comment]
Looks good, thanks! As a follow up, we should add a wrench reftest for this case.

@bors-servo r+

**Pull request merged**
