### PR TITLE
Only draw vertical and horizontal edge when border radius is less then border width

### PR DESCRIPTION
**Pull request by subsevenx2001**
#1805 is caused by fragment shader incorrectly processes corner pixels outside the clip reigon which is originally written for handling border width > border radius case. 

This patch checks whether border radius is less than border width or not before drawing pixel.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1975)

### CODE REVIEW

**Comment by subsevenx2001** [comment]
screen shot 2017-11-02 at 2 55 50 pm

I ran reftest locally and corrected some logic, now this one is the only failed reftest.

But the difference is so little that I cannot see it unless with "Circle the Difference" checked.

Hi @glennw , is that the case which need ref image being regenerated?

**Comment by glennw** [comment]
In that case, you can run ```./headless.py png <reftest name>``` and it will generate and crop a new baseline image.

**Comment by glennw** [comment]
@subsevenx2001 Is there any way we can add a new reftest that covers this change, to ensure we don't regress in the future?

**Comment by subsevenx2001** [comment]
@glennw  It seems that the bug itself only triggered in certain zoom ratio, and the ratio varies among different screen resolution, I am not sure how to trigger it with reftest since we don't have screen resolution in headless mode when performing reftest.

**Comment by glennw** [comment]
@subsevenx2001 Yea, it could be tricky. I *think* I ported the test case at https://bug1404158.bmoattachments.org/attachment.cgi?id=8913468 to a wrench yaml file and was able to reproduce it when I was doing some testing. I've lost that file, but it's probably worth just converting that test case to a wrench YAML file and seeing if it reproduces.

**Comment by subsevenx2001** [comment]
@glennw I see 1920x1080 when running the script generating reference image.

I think maybe it is the base resolution when running headless mode, perhaps we can try reproducing it on a 1080p screen and convert it in YAML.

**Comment by subsevenx2001** [comment]
Add a reftest for testing bogus line in border radius.

**Comment by glennw** [comment]
I submitted a gecko try run for this:

https://treeherder.mozilla.org/#/jobs?repo=try&revision=a374b822433151bd6b29fabb26b78d7fe649cfc9

If it's all green, then this is good to merge.

**Comment by glennw** [comment]
Try looks good, thanks!

@bors-servo r+

**Pull request merged**
