### PR TITLE
Port intermediate blits to brush_image, remove another ps_hw_composite case.

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2510)

### CODE REVIEW

**Comment by glennw** [comment]
r? @kvark 

This is a direct follow up to https://github.com/servo/webrender/pull/2509.

Try still has a few outstanding results, but looks green so far:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=02e3027a715fa9cae5e5107922b12131727517af

**Comment by glennw** [comment]
(Once this lands, the only remaining use of ```ps_hw_composite``` is the drop-shadow implementation. I'll be working on that next, which should fix the remaining drop-shadow bugs we have).

**Comment by glennw** [comment]
Yup, looks like all relevant items in the try run are green.

**Comment by kvark** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/servo/webrender/2510#-:-L7W6tWg4pY-OMEMcD5F:bnfp4nl)*

**Comment by glennw** [comment]
@bors-servo r=kvark
 * bors seems stuck?

**Pull request merged**
