### PR TITLE
Render task tree view in debug server

### PR DESCRIPTION
**Pull request by kvark**
MOARE debugging!

It would be great to somewhat automate the implementation of Json messages being passed for our structs, but for now the manual code is sufficient.

r? @glennw 

wr-render-tasks

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2136)

### CODE REVIEW

**Comment by glennw** [comment]
Looks good, but needs a rebase? r=me once that is done.

**Comment by pcwalton** [comment]
This is awesome! I was literally just thinking today that it would be good to have this.

I wonder if we could generate Graphviz files too :) (obviously that shouldn't block this work from landing)

**Comment by kvark** [comment]
@glennw oh, I rebased but forgot to push it afterwards, d'oh :)
Should be good now.

**Comment by kvark** [comment]
btw, I think we should get rid of the `root` in all the trees and instead just list the documents right away

**Pull request merged**
