### PR TITLE
Add brush_image shader.

### PR DESCRIPTION
**Pull request by glennw**
This adds an initial implementation of an image brush shader,
allowing segments to be used for images that don't have spacing,
tiling or repeat.

This gives an immediate win for common case images (opaque inner
segments, simpler shader), while allowing us to incrementally
port the other image related functionality to image brushes.

The eventual plan is to remove ps_image and brush_picture, by
supporting the functionality they provide into the brush_image
shader.

We can use this as a start point to make image tiling work more
efficiently, by only requesting tiles on demand (rather than
decomposing them up-front), and make spacing / repetition more
efficient by pre-rendering them into the texture cache.

This also unblocks further work on a couple of existing bugzilla issues.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2399)

### CODE REVIEW

**Comment by glennw** [comment]
r? @kvark 

I'll kick off a gecko try shortly.

**Comment by kvark** [comment]
Looks good minus a few optional nits. :lgtm: 

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[webrender/src/batch.rs, line 696 at r1](https://reviewable.io:443/reviews/servo/webrender/2399#-L4si8ZvpnrQjVYZ4QDY:-L4si8ZvpnrQjVYZ4QDZ:bb280w2) ([raw file](https://github.com/servo/webrender/blob/9fc938dd25d045c7ba0c32a55d4e0f61bbb72c34/webrender/src/batch.rs#L696)):*
> ```Rust
>         let specified_blend_mode = ctx.prim_store.get_blend_mode(prim_metadata);
> 
>         let legacy_blend_mode = if !prim_metadata.opacity.is_opaque ||
> ```

I'm a little bit confused about `legacy` term here. Would something like `effective_blend_mode` reflect the semantics better?

---

*[webrender/src/batch.rs, line 1386 at r1](https://reviewable.io:443/reviews/servo/webrender/2399#-L4siOGUGrBRekwp2bM_:-L4siOGUGrBRekwp2bMa:b-hlhtwv) ([raw file](https://github.com/servo/webrender/blob/9fc938dd25d045c7ba0c32a55d4e0f61bbb72c34/webrender/src/batch.rs#L1386)):*
> ```Rust
>             }
>             None => {
>                 let needs_blending = !prim_metadata.opacity.is_opaque ||
> ```

this is repeating the same logic as with `legacy_blend_mode`. Let's have it DRY

---

*[wrench/reftests/image/reftest.list, line 7 at r1](https://reviewable.io:443/reviews/servo/webrender/2399#-L4skD5jnGHnnjbaPnaC:-L4skD5jnGHnnjbaPnaD:bf0ctx9) ([raw file](https://github.com/servo/webrender/blob/9fc938dd25d045c7ba0c32a55d4e0f61bbb72c34/wrench/reftests/image/reftest.list#L7)):*
> ```
> fuzzy(1,250000) == tile-repeat-prim-or-decompose.yaml tile-repeat-prim-or-decompose-ref.yaml
> == downscale.yaml downscale.png
> segments.yaml segments.png
> ```

shouldn't this be `== segments.yaml segments.png`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/2399#-:-L4skSFEGCjfMxUkTbzH:b1rv9sh)*

**Comment by glennw** [comment]
Review status: 12 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[webrender/src/batch.rs, line 696 at r1](https://reviewable.io:443/reviews/servo/webrender/2399#-L4si8ZvpnrQjVYZ4QDY:-L4spgelPhBAh4eN_nBl:bflc8j3) ([raw file](https://github.com/servo/webrender/blob/9fc938dd25d045c7ba0c32a55d4e0f61bbb72c34/webrender/src/batch.rs#L696)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

I'm a little bit confused about `legacy` term here. Would something like `effective_blend_mode` reflect the semantics better?
</blockquote></details>

Renamed it to ```non_segmented_blend_mode```.

---

*[webrender/src/batch.rs, line 1386 at r1](https://reviewable.io:443/reviews/servo/webrender/2399#-L4siOGUGrBRekwp2bM_:-L4spmVfE5zpbRGyDGqE:b-896fix) ([raw file](https://github.com/servo/webrender/blob/9fc938dd25d045c7ba0c32a55d4e0f61bbb72c34/webrender/src/batch.rs#L1386)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

this is repeating the same logic as with `legacy_blend_mode`. Let's have it DRY
</blockquote></details>

Done.

---

*[wrench/reftests/image/reftest.list, line 7 at r1](https://reviewable.io:443/reviews/servo/webrender/2399#-L4skD5jnGHnnjbaPnaC:-L4spn-TP8vvtyL2M413:b-896fix) ([raw file](https://github.com/servo/webrender/blob/9fc938dd25d045c7ba0c32a55d4e0f61bbb72c34/wrench/reftests/image/reftest.list#L7)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

shouldn't this be `== segments.yaml segments.png`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/2399)*

**Comment by glennw** [comment]
@kvark Thanks for the quick review! All comments addressed now.

**Comment by kvark** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/2399)*

**Comment by staktrace** [comment]
@glennw This PR seems to have caused a large increase in the number of windows reftest failures, and some user-visible differences in behaviour as well. See https://bugzilla.mozilla.org/show_bug.cgi?id=1436058#c13 onwards.

**Pull request merged**
