### PR TITLE
Update dwrote to 0.11.0.

### PR DESCRIPTION
**Pull request by jdm**

### CODE REVIEW

**Comment by atouchet** [comment]
Is there anything blocking this? It would be nice to get this updated to dedupe dwrote in Servo.

**Comment by kvark** [comment]
WebRender changes have to go through Phabricator for review and landing. Typically, a PR gets picked up by somebody willing to port it to Phabricator, with some delay, and eventually lands.
@jdm could technically do it themselves.
Otherwise, it would be useful to ping somebody from the team (or just in #gfx:mozilla.org) to take care of a PR like this.

**Comment by kvark** [comment]
This procedure also involves creating a bugzilla issue... takes a few steps.
I did the same change from the ground up in https://phabricator.services.mozilla.com/D72748 (since this PR is conflicting).

**Comment by atouchet** [comment]
This was done in #3935.

**Pull request closed without merging**
