### PR TITLE
Improve ellipse calculations.

### PR DESCRIPTION
**Pull request by demo99**
There is a performance issue (gecko [bug 1414575](https://bugzilla.mozilla.org/show_bug.cgi?id=1414575)). It looks like there is a large ellipse clip and I think we shouldn't calculate the distance for all points on the rectangle.
The gecko try push with the patch looks fine: https://treeherder.mozilla.org/#/jobs?repo=try&revision=f47b134d028bd510c49dabfb85e287a48a098f94. I also add a wrench test for ellipse clipping.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2103)

### CODE REVIEW

**Comment by glennw** [comment]
It'd be good to also have a large ellipse clip test in the ```benchmarks/``` - then we can evaluate the performance difference of this change on different GPUs over time.

**Comment by demo99** [comment]
I just added a benchmark test.
Without the fix, the result is:   
            {
	      "name": "benchmarks/large-boxshadow-ellipse.yaml",
	      "backend_time_ns": 43619,
	      "composite_time_ns": 278558,
	      "paint_time_ns": 1936842,
	      "draw_calls": 5
	    },

With the fix, the result is:
	    {
	      "name": "benchmarks/large-boxshadow-ellipse.yaml",
	      "backend_time_ns": 53068,
	      "composite_time_ns": 333172,
	      "paint_time_ns": 6770394,
	      "draw_calls": 5
    },

**Comment by demo99** [comment]
I just added a benchmark test.
Without the fix, the result is:
{
"name": "benchmarks/large-boxshadow-ellipse.yaml",
"backend_time_ns": 53068,
"composite_time_ns": 333172,
"paint_time_ns": 6770394,
"draw_calls": 5
},

With the fix, the result is:
{
"name": "benchmarks/large-boxshadow-ellipse.yaml",
"backend_time_ns": 43619,
"composite_time_ns": 278558,
"paint_time_ns": 1936842,
"draw_calls": 5
},

**Comment by glennw** [comment]
Great, thanks!

@bors-servo r+

**Pull request merged**
