### PR TITLE
Next set of ClipScrollTree optimizations

### PR DESCRIPTION
**Pull request by mrobinson**
This seems to cut the prominence of ClipScrollTree updates in my profile a great deal.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2156)

### CODE REVIEW

**Comment by mrobinson** [comment]
Here is the Gecko try: https://treeherder.mozilla.org/#/jobs?repo=try&revision=51369c294686d137fc80ace6ef8032bd5208ad50&group_state=expanded

97% done and no failures.

**Comment by glennw** [comment]
I'd like to get #2146 landed before we land this, if possible (doing a gecko try now, hopefully it will be ready after that), since they will conflict a bit.

This looks awesome from a quick scan though, it should help with CPU performance a lot!

**Comment by glennw** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[webrender/src/prim_store.rs, line 1661 at r1](https://reviewable.io:443/reviews/servo/webrender/2156#-L-UuEjPbDMeA3O7Lu0D:-L-UuEjQ8Wbo2SuhyyZ0:b3pj9pp) ([raw file](https://github.com/servo/webrender/blob/3aa471129f5ed3c2a28abd978c60548467e2529b/webrender/src/prim_store.rs#L1661)):*
> ```Rust
> }
> 
> fn get_local_bounding_rect(
> ```

This uses ```transform_point3d``` while the version it's replaced with in ```util.rs``` uses ```transform_point2d```. Perhaps that's not actually relevant here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/2156)*

**Comment by glennw** [comment]
Just one question, otherwise this looks good to me (it will need a rebase after #2146 lands too).

**Comment by mrobinson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[webrender/src/prim_store.rs, line 1661 at r1](https://reviewable.io:443/reviews/servo/webrender/2156#-L-UuEjPbDMeA3O7Lu0D:-L-VyHK0AMQQyqEED9_b:bmpmi99) ([raw file](https://github.com/servo/webrender/blob/3aa471129f5ed3c2a28abd978c60548467e2529b/webrender/src/prim_store.rs#L1661)):*
<details><summary><i>Previously, glennw (Glenn Watson) wrote…</i></summary><blockquote>

This uses ```transform_point3d``` while the version it's replaced with in ```util.rs``` uses ```transform_point2d```. Perhaps that's not actually relevant here?
</blockquote></details>

I think this should be okay. Both methods are using the same code to calculate the x and y coordinates of the final point.

```
    #[inline]
    pub fn transform_point3d(&self, p: &TypedPoint3D<T, Src>) -> TypedPoint3D<T, Dst> {
        let x = p.x * self.m11 + p.y * self.m21 + p.z * self.m31 + self.m41;
        let y = p.x * self.m12 + p.y * self.m22 + p.z * self.m32 + self.m42;
        let z = p.x * self.m13 + p.y * self.m23 + p.z * self.m33 + self.m43;
        let w = p.x * self.m14 + p.y * self.m24 + p.z * self.m34 + self.m44;

        point3(x/w, y/w, z/w)
}
```

```   
#[inline]
    pub fn transform_point2d(&self, p: &TypedPoint2D<T, Src>) -> TypedPoint2D<T, Dst> {
        let x = p.x * self.m11 + p.y * self.m21 + self.m41;
        let y = p.x * self.m12 + p.y * self.m22 + self.m42;

        let w = p.x * self.m14 + p.y * self.m24 + self.m44;

        point2(x/w, y/w)
```

transform_point2d should be *slightly* more efficient.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/2156)*

**Comment by mrobinson** [comment]
Okay. I've rebased this branch as well as adding another, very simple, cleanup commit for util.rs.

**Pull request merged**
