### PR TITLE
Fixed transformed primitives

### LINKED ISSUE #2168: regression: Rotated rect not respecting device pixel ratio
This is a regression from #2069 
```
8253bbb398d03094c704be9333415789cabf6b7c is the first bad commit
commit 8253bbb398d03094c704be9333415789cabf6b7c
Author: Glenn Watson <github@intuitionlibrary.com>
Date:   Tue Nov 21 14:36:11 2017 +1000

    Remove manual interpolation of local space in transform shaders.

    Instead, for vertex transform shaders we now write out:
     (world.xy, z * world.w, world.w)

    This gives us constant Z across the polygon for draw ordering.

    It also means we can use the hardware interpolators instead of
    manually dividing by Z in the fragment shader for local_pos.

    This is mostly preparation work for switching shaders over to
    be brush primitives, but has the happy side effect of:

     * Fixing a small number of Gecko + Servo reftests.
     * Simpler and faster code.
```

### STR:
I first noticed this in the `animations` sample, you can hit `2` to set the device pixel ratio to 2.0 and then hit `,` or `.` to rotate the rect.

You can also run `rotated-clip.yaml` when run with `-p=2` and observe it not respecting the pixel ratio

I didn't see a way to specify a device pixel ratio in `reftest.list` but perhaps it would be a nice enhancement?

### PR DESCRIPTION
**Pull request by kvark**
Fixes #2168

Try push: https://treeherder.mozilla.org/#/jobs?repo=try&revision=e446306f491bf773f335469280f0b3db412ffa9f

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2217)

### CODE REVIEW

**Comment by glennw** [comment]
Oops! r=me if try is green.

**Comment by jrmuizel** [comment]
Test case?

**Comment by kvark** [comment]
All green.
@bors-servo r+

**Comment by kvark** [comment]
OSX:
> No output has been received in the last 10m0s

@bors-servo retry

**Comment by kvark** [comment]
Hmm, have our OSX build times regressed?
@bors-servo retry

**Pull request merged**
