### PR TITLE
Expand gitignore to include common editor metadata files

### PR DESCRIPTION
**Pull request by mrobinson**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1215)

### CODE REVIEW

**Comment by kvark** [comment]
Looks reasonable
@bors-servo r+

**Comment by kvark** [comment]
Mac is still stubborn. Retrying.
@bors-servo retry

**Comment by metajack** [comment]
Not a big deal, but usually I put these in the global .gitignore on my machine instead of in every project's .gitignore.

**Comment by mrobinson** [comment]
@metajack Thanks for the tip!

**Pull request merged**
