### PR TITLE
Add query feature to wrench.

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1890)

### CODE REVIEW

**Comment by glennw** [comment]
r? anyone

**Comment by kvark** [comment]
> the job exceeded the maximum time limit for jobs, and has been terminated.

@bors-servo retry

**Comment by kvark** [comment]
> The job exceeded the maximum time limit for jobs, and has been terminated.

hmm, that again. Maybe more luck when everyone is asleep?
@bors-servo r+

**Comment by kvark** [comment]
buy, nightly
r+

**Comment by kvark** [comment]
I mean,
@bors-servo r+

**Comment by glennw** [comment]
Wow, this one line patch *really* doesn't want to merge...

@bors-servo retry

**Pull request merged**
