### PR TITLE
Update to glutin 0.19 and winit 0.18 issue #3198 macOS 10.14 fix

### PR DESCRIPTION
**Pull request by martinenzinger**
fixes the empty window issue on macOS 10.14 

https://github.com/tomaka/winit/pull/685

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/3295)

### CODE REVIEW

**Comment by atouchet** [comment]
Doesn't cargo.lock still need to be updated?

**Comment by martinenzinger** [comment]
@atouchet `Cargo.lock` should not be manually changed. Here is a link explaining what the `.lock` files are meant to do: [Cargo.toml vs Cargo.lock](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html).
If the examples still don't work on Mojave, you can try cloning [martinenzinger/webrender](https://github.com/martinenzinger/webrender) into a new folder.

**Comment by martinenzinger** [comment]
@gw3583  In the v0.19 release of glutin the `GlContext` trait is different. I guess this would require changes I, having seen the code for the first time a week ago, can not carry out. What do the other people think about the issue being examples are not working and a different version of glutin for the wrench debugging as a temporary solution?

On the other hand, the pull request is linked in the issue, and in the meantime, Mojave users can find an easy fix when they search for issues.

https://docs.rs/glutin/0.19.0/glutin/trait.GlContext.html
https://github.com/tomaka/glutin/releases/tag/v0.19.0

**Comment by kvark** [comment]
@martinenzinger if Cargo.lock is in Git, we need to update it here. If you want to raise the discussion of *why* we keep it in Git, that would be a different issue.

> Merge remote-tracking branch 'upstream/master' 

Also, please rebase instead of merging from upstream.

**Pull request closed without merging**
