### PR TITLE
Remove unused DisplayListMode

### PR DESCRIPTION
**Pull request by jrmuizel**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/920)

### CODE REVIEW

**Comment by glennw** [comment]
@mrobinson Do you see any need to keep this around?

**Comment by jrmuizel** [comment]
I've added another field removal

**Comment by mrobinson** [comment]
@glennw Nope. I think that these can be safely removed. In fact, I think I had meant to do it myself. ☺

**Pull request merged**
