### PR TITLE
support font subpixel AA with content transforms

### PR DESCRIPTION
**Pull request by lsalzman**
This solves issue #1808. It ensures that we render subpixel AA in device space rather than layer local space, so as to side-step the issue with subpixels getting deformed by a layer transform.

The engine of this is FontTransform, which is the upper 2x2 submatrix of the layer transform and which is stored in the FontInstance - automatically and necessarily becoming part of the font key. That transform has to be passed down to the font backend so that rasterization actually uses it.

In the text shader, we can just optionally derive this transform from the layer transform, without having to pass in any other state. We have to make sure we only conditionally use it, as not all glyphs will be pre-transformed. To that end, I made TextShader a replacement for PrimitiveShader (as discussed with Glenn).

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2058)

### CODE REVIEW

**Comment by glennw** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/2058)*

**Comment by glennw** [comment]
This looks great! We'll need a gecko try run before merging though. I'll handle running it through the Servo tests.

**Comment by glennw** [comment]
Oh, one other thing - we should add some wrench reftest cases - rotation, skew etc on both subpx and alpha test runs. Also with some text shadow cases. These can be done as a follow up.

**Comment by glennw** [comment]
There's a few gecko try failures that @lsalzman is working on - we know the cause.

**Comment by lsalzman** [comment]
Fixed issue with computing snap offsets in the text shader.

**Comment by glennw** [comment]
I think we should have at least a couple of reftests (just on one platform is enough) for this stuff - it's so fiddly to get right and easy to regress.

**Comment by lsalzman** [comment]
Fixed merge conflicts.

**Comment by lsalzman** [comment]
Added subpixel rotation, scale, and skew transform reftests.

**Comment by glennw** [comment]
Based on discussions with @lsalzman I think this is blocked until we get some fixes to the mac dependency crates.

**Comment by lsalzman** [comment]
Fixed core-graphics-rs to have the functionality needed and updated this to use it.

**Comment by glennw** [comment]
Reviewed 20 of 20 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/2058)*

**Comment by glennw** [comment]
@lsalzman has done a try run and got green results, so this looks good to go. Thanks!

@bors-servo r+

**Comment by glennw** [comment]
Needs a rebase.

**Comment by lsalzman** [comment]
Fixes #1808

**Pull request merged**
