### PR TITLE
Rename text-shadow APIs to shadow instead.

### PR DESCRIPTION
**Pull request by glennw**
In the near future, the text-shadow APIs will be used to
implement other types of shadows (e.g. box-shadows).

This patch just renames all functions and structures, which
will make it easier to review the follow up patches that
modify box shadows to work via the current text-shadow API.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1801)

### CODE REVIEW

**Comment by glennw** [comment]
r? @nical or @kvark 

@Gankro @staktrace Heads up that this modifies the public API and will require updating WR bindings. It's a straight rename - ```push_text_shadow``` to ```push_shadow``` etc.

**Comment by Gankro** [comment]
Ok, should be very easy to update gecko.

Just checking, will this refactoring only lead to the addition of rects as "things that go in a (text)-shadow"? (currently only glyphs and lines?)

**Comment by glennw** [comment]
Yep, that's right (for now, anyway!).

**Comment by staktrace** [comment]
Thanks for the heads-up (re WR bindings update needed)!

**Pull request merged**
