### PR TITLE
Port the Pathfinder branch to Linux (FreeType).

### LINKED ISSUE #2617: webrender fails to build with --default-features=false + features = "pathfinder"
```toml
[dependencies.webrender]
git = "https://github.com/servo/webrender"
rev = "f9ddc5261ad2cd35c60851c4091b682c900dbb0a"
features = ["pathfinder"]
```

Since now both pathfinder and webrender link to freetype, this fails to build with:

```rust
error: multiple packages link to native library `freetype`, but a native library can be linked only once

package `freetype-sys v0.6.0`
    ... which is depended on by `pathfinder_font_renderer v0.1.0 (https://github.com/pcwalton/pathfinder#fcfd157c)`
    ... which is depended on by `webrender v0.57.2 (https://github.com/servo/webrender?rev=f9ddc5261ad2cd35c60851c4091b682c900dbb0a#f9ddc526)`
    ... which is depended on by `azul v0.1.0 (file:///home/felix/Development/azul)`
links to native library `freetype`

package `servo-freetype-sys v4.0.3`
    ... which is depended on by `freetype v0.4.0`
    ... which is depended on by `webrender v0.57.2 (https://github.com/servo/webrender?rev=f9ddc5261ad2cd35c60851c4091b682c900dbb0a#f9ddc526)`
    ... which is depended on by `azul v0.1.0 (file:///home/felix/Development/azul)`
also links to native library `freetype`
```

So, my next course of action was to disable the default freetype feature (also note that with the migration to pathfinder, it shouldn't be a default feature anymore IMO):

```toml
[dependencies.webrender]
git = "https://github.com/servo/webrender"
rev = "f9ddc5261ad2cd35c60851c4091b682c900dbb0a"
default-features = false
features = ["pathfinder"]
```

Which fails to build with a few compile errors:

```rust
   Compiling pathfinder_partitioner v0.1.0 (https://github.com/pcwalton/pathfinder#fcfd157c)
error[E0599]: no method named `add_native_font` found for type `&mut pathfinder_font_renderer::FontContext<webrender_api::FontKey>` in the current scope
   --> /home/felix/.cargo/git/checkouts/webrender-c3596abe1cf4f320/f9ddc52/webrender/src/glyph_rasterizer.rs:867:27
    |
867 |                 drop(self.add_native_font(&font_key, (*native_font_handle).clone().0));
    |                           ^^^^^^^^^^^^^^^

error[E0609]: no field `0` on type `webrender_api::NativeFontHandle`
   --> /home/felix/.cargo/git/checkouts/webrender-c3596abe1cf4f320/f9ddc52/webrender/src/glyph_rasterizer.rs:867:54
    |
867 |                 drop(self.add_native_font(&font_key, (*native_font_handle).clone().0));
    |                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no method named `compute_scale` found for type `glyph_rasterizer::FontTransform` in the current scope
   --> /home/felix/.cargo/git/checkouts/webrender-c3596abe1cf4f320/f9ddc52/webrender/src/platform/unix/font.rs:280:49
    |
280 |         let (x_scale, y_scale) = font.transform.compute_scale().unwrap_or((1.0, 1.0));
    |                                                 ^^^^^^^^^^^^^
    |
   ::: /home/felix/.cargo/git/checkouts/webrender-c3596abe1cf4f320/f9ddc52/webrender/src/glyph_rasterizer.rs:83:1
    |
83  | pub struct FontTransform {
    | ------------------------ method `compute_scale` not found for this

error[E0599]: no method named `invert_scale` found for type `glyph_rasterizer::FontTransform` in the current scope
   --> /home/felix/.cargo/git/checkouts/webrender-c3596abe1cf4f320/f9ddc52/webrender/src/platform/unix/font.rs:289:44
    |
289 |             let mut shape = font.transform.invert_scale(x_scale, y_scale);
    |                                            ^^^^^^^^^^^^
    |
   ::: /home/felix/.cargo/git/checkouts/webrender-c3596abe1cf4f320/f9ddc52/webrender/src/glyph_rasterizer.rs:83:1
    |
83  | pub struct FontTransform {
    | ------------------------ method `invert_scale` not found for this

error: aborting due to 4 previous errors

error: Could not compile `webrender`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

rustc 1.25 stable
Debian 9.4 (note: in the pathfinder repo, the `add_native_font` uses macOS Quartz fonts?)

### PR DESCRIPTION
**Pull request by pcwalton**
Closes #2617.

r? @glennw

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2636)

### CODE REVIEW

**Comment by pcwalton** [comment]
Should be fixed now

**Comment by jrmuizel** [comment]
FWIW, I seem to have broken the Mac CI

**Comment by glennw** [comment]
@jrmuizel Was it a WR PR that caused it? I don't see anything recently landed that would break it?

**Comment by jrmuizel** [comment]
Nope, I was working on getting the worker to be able to use the display and I'm guessing that broke it somehow

**Pull request merged**
