### PR TITLE
Fix binary recording and replay.

### PR DESCRIPTION
**Pull request by glennw**
* Add SetWindowParameters to the list of messages that get serialized.
* Ensure we wait for the three initial messages in correct order to detect the first frame.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1252)

### CODE REVIEW

**Comment by jrmuizel** [comment]
This gets broken often enough that it's probably worth adding some kind of testing...

**Comment by glennw** [comment]
@jrmuizel Agreed - opened https://github.com/servo/webrender/issues/1253

**Comment by kvark** [comment]
Thank you!
@bors-servo r+

**Pull request merged**
