### PR TITLE
Tile decomposition crash

### PR DESCRIPTION
**Pull request by jrmuizel**
This adds a test case that causes a panic in render_backend.rs with 'RenderBackend' panicked at 'assertion failed: image_size.width <= tile_size'. This is a reduction from a crash in Gecko with tiled blob images turned on.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1603)

### CODE REVIEW

**Comment by jrmuizel** [comment]
It might be worth fixing this before landing it.

**Comment by glennw** [comment]
I figured it was OK to land since the raw tests are only run manually right now - but we can hold off if you prefer?

**Comment by jrmuizel** [comment]
I don't feel strongly either way.

**Pull request merged**
