### PR TITLE
Remove StackingContext nesting for overflow scroll regions

### PR DESCRIPTION
**Pull request by mrobinson**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/451)

### CODE REVIEW

**Comment by mrobinson** [comment]
@pcwalton or @glennw r?

**Comment by glennw** [comment]
@mrobinson This looks fine to me - I assume it needs a similar change in servo though? Feel free to merge this if/when that's ready.

**Comment by mrobinson** [comment]
@glennw The Servo part is here: https://github.com/mrobinson/servo/tree/remove-nesting. I'll merge this and make a PR for Servo.

**Pull request merged**
