### PR TITLE
webrender_api: Pass &[FilterOp] instead of Vec<FilterOp>.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/3245)

### CODE REVIEW

**Comment by nical** [comment]
Nice! The taskcluster failure looks unrelated I'll try to retrigger when appveyor is done.

**Comment by emilio** [comment]
(There's no point in retriggering taskcluster since bors does a whole new run)

**Comment by staktrace** [comment]
```
error: Connection to server timed out
error: Could not compile `osmesa-src`.
```

This definitely seems like an sccache intermittent. Somebody should tell bors to retry.

**Pull request merged**
