### PR TITLE
Properly support tiling clip mask images.

### LINKED ISSUE #2852: Support tiled clip images
When we request image for a clip source that is an image, we never supply a tile:
```rust
                ClipSource::Image(ref mask) => {
                    resource_cache.request_image(
                        ImageRequest {
                            key: mask.image,
                            rendering: ImageRendering::Auto,
                            tile: None, // <---------- HERE
                        },
                        gpu_cache,
                    );
                }
```
This breaks the resource cache expectations that a tiled image would only be requested with specific tiles.
cc @nical @aosmond

### PR DESCRIPTION
**Pull request by emilio**
Fixes #2852.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/3220)

### CODE REVIEW

**Comment by emilio** [comment]
r? @gw3583 / @nical / @kvark 

I'd prefer not to land it yet, since the code is basically copy-pasted from image tiling, and it could get some cleanup.

Just want to confirm this approach is the right way to fix this.

I also need to write some reftests for this, but testing of blob images is none as of right now... So I'll add some Gecko reftests to the bug.

If this an acceptable solution I'll clean up and such before get it landed.

**Comment by emilio** [comment]
I think this should be basically ready for review. I added a bunch of cleanup commits that made me feel less bad about copying the image tiling code, and a bunch of tests (will add reftests that check the blob image stuff in Gecko after this lands).

Once thing that may be problematic is that if I understand correctly this I'm drawing the whole visible area for each tile just to `discard` the pixels afterwards... I think there must be a way to do better, but not sure how... Also that wouldn't necessarily need to be part of this PR I guess.

In any case... r? :)

**Comment by emilio** [comment]
https://treeherder.mozilla.org/#/jobs?repo=try&revision=a1029ae05c0e88b6cfe84f27120ba25e45b0b558 has this patch.

**Comment by gw3583** [comment]
This basically looks good to me (a couple of minor nits). It'd be good to get @nical to take a look over the image tiling changes, if possible, as well.

**Comment by nical** [comment]
Looks good to me!

**Comment by emilio** [comment]
Thanks!

@bors-servo r=gw3583,nical

**Comment by gw3583** [comment]
Trying to wake up bors

**Pull request merged**
