### PR TITLE
appveyor: download latest stable rust with rustup

### PR DESCRIPTION
**Pull request by UK992**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2631)

### CODE REVIEW

**Comment by glennw** [comment]
I'm not sure this is what we want. We want to specifically track the most recent rustc that is allowed for Gecko builds, which is our minimal target. This seems like it would get rustc versions ahead of that?

**Comment by staktrace** [comment]
Note that the taskcluster Linux CI also uses the most recent stable rustc.
The taskcluster mac CI uses whatever we installed - rustc has to be
manually updated there. While using gecko's minimal rustc would be ideal I
don't know of an API to get that info, but I haven't looked either.

**Comment by glennw** [comment]
In the past we've just been updating the travis.yml manually with the current Gecko rustc version each time it changes (6 weeks, I think?).

**Comment by glennw** [comment]
Closing this, since I think we'll want to retain the ability to pin to a specific rustc version. If our current rustc version is behind the gecko minimum rustc, we could update that though.

**Pull request closed without merging**
