### PR TITLE
Proper near plane splitting

### LINKED ISSUE #2272: regression: Animation rendered all over the place with webrender
Filing for https://bugzilla.mozilla.org/show_bug.cgi?id=1420754

This was determined to be a regression from #2069 but was not fixed by the fixes for #2133.

### PR DESCRIPTION
**Pull request by kvark**
The PR is built on the shoulders of #2913, #2741, https://github.com/servo/euclid/pull/277, https://github.com/servo/euclid/pull/291, https://github.com/servo/plane-split/pull/12, and (last but not the least!) https://github.com/servo/plane-split/pull/15

It uses the new clipping semantics in `plane-split` crate uniformly for both bounding box computation and 3d plane splitting itself, ensuring that no incorrect perspective divisions are performed (and closing quite a few TODO entries). Also adds a small reftest for the latter.

Fixes #2272

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2947)

### CODE REVIEW

**Comment by gw3583** [comment]
Wow, nice! I'll review this today. Could you kick off a try-push in the meantime?

**Comment by kvark** [comment]
Launched a try in https://treeherder.mozilla.org/#/jobs?repo=try&revision=b1fc20bb9928bf6e3ed055fb9bb69c5250c8d784
Also confirmed the bugzilla case working:
screenshot from 2018-08-01 23-03-58

**Comment by gw3583** [comment]
There are several new PASS results in the try :tada: but there's also a few failures. Each of them seem to be the same assert:

```
hread 'WRRenderBackend#4' panicked at 'assertion failed: edge2.square_length() > T::approx_epsilon()', third_party\rust\plane-split\src\polygon.rs:133:9
```

**Comment by gw3583** [comment]
The change basically looks good to me, but I'll take another pass over it once we get that assert failure fixed :)

**Comment by kvark** [comment]
Addressed the try push issues in https://github.com/servo/plane-split/pull/18
Launched a try push with those plane-split changes (overridden with a cargo patch):
https://treeherder.mozilla.org/#/jobs?repo=try&revision=f8225f77003bdf6bb87ecd0494e2dd8b779210d3&selectedJob=191881097

So far, it's a bunch of intermittents plus the expected unexpected passes.
@gw3583 please take your extra pass ;) no code is changed on this side (other than pulling the patched plane-split crate).

**Pull request merged**
