### PR TITLE
Multi-doc support

### PR DESCRIPTION
**Pull request by kvark**
A namespace can now contain multiple documents. Operations on a document are done ~~via a separate object `DocumentApi`, which created from `ResourceApi` that manages resources~~ by providing `DocumentId` parameter to `RenderApi` calls.

This PR is a step towards #1357, also relates to #1370.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1509)

### CODE REVIEW

**Comment by glennw** [comment]
Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[webrender/src/lib.rs, line 16 at r1](https://reviewable.io:443/reviews/servo/webrender/1509#-KpmO5Y9Yf7jvHQoNvUk:-KpmO5YA44phEnWCKmT7:b-14eodz) ([raw file](https://github.com/servo/webrender/blob/820a8b1633de3352eaa8a1f36af56c30d8c5472c/webrender/src/lib.rs#L16)):*
> ```Rust
> //! The main entry point to WebRender is the `webrender::renderer::Renderer`.
> //!
> //! By calling `Renderer::new(...)` you get a `Renderer`, as well as a `DocumentApiSender`.
> ```

It's not a DocumentApiSender you get from that?

---

*[webrender/src/lib.rs, line 19 at r1](https://reviewable.io:443/reviews/servo/webrender/1509#-KpmODfMhtKyhFmlFOWA:-KpmODfNeVBxRfwNh12U:b2nreh6) ([raw file](https://github.com/servo/webrender/blob/820a8b1633de3352eaa8a1f36af56c30d8c5472c/webrender/src/lib.rs#L19)):*
> ```Rust
> //! Your `Renderer` is responsible to render the previously processed frames onto the screen.
> //!
> //! By calling `yourDocumentApiSenderInstance.create_api()`, you'll get a `DocumentApi` instance,
> ```

Same as above.

---

*[webrender/src/render_backend.rs, line 123 at r1](https://reviewable.io:443/reviews/servo/webrender/1509#-KpmNZ4nJyHewaMa5MZn:-KpmNZ4nJyHewaMa5MZo:bpogl36) ([raw file](https://github.com/servo/webrender/blob/820a8b1633de3352eaa8a1f36af56c30d8c5472c/webrender/src/render_backend.rs#L123)):*
> ```Rust
> 
>     frame_config: FrameBuilderConfig,
>     documents: HashMap<DocumentId, Document>,
> ```

Let's use Fnv hasher here.

---

*[wrench/src/json_frame_writer.rs, line 73 at r1](https://reviewable.io:443/reviews/servo/webrender/1509#-KpmOSeBjK3pxQNJNMK6:-KpmOSeBjK3pxQNJNMK7:b50oiae) ([raw file](https://github.com/servo/webrender/blob/820a8b1633de3352eaa8a1f36af56c30d8c5472c/wrench/src/json_frame_writer.rs#L73)):*
> ```Rust
>     }
> 
>     pub fn begin_write_display_list(&mut self,
> ```

I wonder if we should just remove the json from writer completely? I don't think anyone uses it...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/1509)*

**Comment by glennw** [comment]
Looks great! Just a few minor comments / changes.

**Comment by glennw** [comment]
Also, it'd be good to have the corresponding Servo patch ready to go when we land this so we can get a WR update landed straight after.

**Comment by nical** [comment]
The separation between the resource and document apis looks nice but it will make the task of bundling image updates and display lists in the same transactions difficult.

**Comment by nical** [comment]
I suggest not rushing to update servo and gecko, because if I manage to be convincing enough during tomorrow's meeting, we'll do something different (not totally different but with some substantial API changes).

**Comment by kvark** [comment]
Servo integration is not trivial, WIP, but other notes are addressed now.

---

Review status: 12 of 21 files reviewed at latest revision, 4 unresolved discussions.

---

*[webrender/src/lib.rs, line 16 at r1](https://reviewable.io:443/reviews/servo/webrender/1509#-KpmO5Y9Yf7jvHQoNvUk:-Kpq19JPBPtpUuDzfVIy:b-7ql1td) ([raw file](https://github.com/servo/webrender/blob/820a8b1633de3352eaa8a1f36af56c30d8c5472c/webrender/src/lib.rs#L16)):*
<details><summary><i>Previously, glennw (Glenn Watson) wrote…</i></summary><blockquote>

It's not a DocumentApiSender you get from that?
</blockquote></details>

fixed

---

*[webrender/src/lib.rs, line 19 at r1](https://reviewable.io:443/reviews/servo/webrender/1509#-KpmODfMhtKyhFmlFOWA:-Kpq1Aa_0EcFYGvyUfBY:b-7ql1td) ([raw file](https://github.com/servo/webrender/blob/820a8b1633de3352eaa8a1f36af56c30d8c5472c/webrender/src/lib.rs#L19)):*
<details><summary><i>Previously, glennw (Glenn Watson) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

fixed

---

*[webrender/src/render_backend.rs, line 123 at r1](https://reviewable.io:443/reviews/servo/webrender/1509#-KpmNZ4nJyHewaMa5MZn:-Kpq1Bx5BPbKjJ9Up93H:b-7ql1td) ([raw file](https://github.com/servo/webrender/blob/820a8b1633de3352eaa8a1f36af56c30d8c5472c/webrender/src/render_backend.rs#L123)):*
<details><summary><i>Previously, glennw (Glenn Watson) wrote…</i></summary><blockquote>

Let's use Fnv hasher here.
</blockquote></details>

fixed

---

*[wrench/src/json_frame_writer.rs, line 73 at r1](https://reviewable.io:443/reviews/servo/webrender/1509#-KpmOSeBjK3pxQNJNMK6:-Kpq1DSBLddurxVbvc0l:b-p4pqfy) ([raw file](https://github.com/servo/webrender/blob/820a8b1633de3352eaa8a1f36af56c30d8c5472c/wrench/src/json_frame_writer.rs#L73)):*
<details><summary><i>Previously, glennw (Glenn Watson) wrote…</i></summary><blockquote>

I wonder if we should just remove the json from writer completely? I don't think anyone uses it...
</blockquote></details>

agreed, but better left for a dedicated PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/1509#-:-Kpq1IIb8Agww_FX9wdd:bywd3un)*

**Comment by jrmuizel** [comment]
Previously, glennw (Glenn Watson) wrote…
>  I wonder if we should just remove the json from writer completely? I don't think anyone uses it...

It's been used for getting readable dumps of binary recordings. I think we could probably simplify it to just providing that functionality.

**Comment by kvark** [comment]
@glennw servo update is in https://github.com/kvark/servo/commit/4f940df68722232a12b934f0e66054b23ae12140

**Comment by glennw** [comment]
Reviewed 21 of 21 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/1509)*

**Comment by kvark** [comment]
Rebasing this is a constant pain...
@bors-servo r=glennw

**Comment by sotaroikeda** [comment]
@kvark, can you explain about actual benefit of supporting Multi-doc support? Is it still in the middle of implementation? Gecko creates GL context for each window, but webrender Renderer instance still owns single GL context, therefore each window needs to have different Renderer instance. Then current gecko just use one document on each Renderer and each window creates each webrender Renderer by [Bug 1385003](https://bugzilla.mozilla.org/show_bug.cgi?id=1385003) Thanks!

**Comment by kvark** [comment]
@sotaroikeda the idea is that WR can have multiple Renderer instances sharing the same backend and receiving frames only from the corresponding documents.

**Comment by sotaroikeda** [comment]
@nical, do you have any ideas to use Multi-doc support in gecko?

**Comment by nical** [comment]
> @nical, do you have any ideas to use Multi-doc support in gecko?

I haven't looked into the details since the multi-doc stuff landed, but I think that it'd be good to complete the implementation so that documents can use their own renderer. That way we can look into grouping some windows like tooltips into using a single render backend thread, and share fonts, glyph cache, etc.

> Is it still in the middle of implementation? 

Yes, as far as I can tell (it doesn't let you have a renderer per document yet for example).

**Comment by kvark** [comment]
Basically, https://github.com/servo/webrender/blob/2ac2da08b77aff15cc7e38118fa20071262b07e9/webrender/src/renderer.rs#L1455

**Pull request merged**
