### PR TITLE
Implement GetShaderPrecisionFormat WebGL command

### PR DESCRIPTION
**Pull request by MortimerGoro**
Implement GetShaderPrecisionFormat. See https://github.com/servo/gleam/pull/119

This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1127)

### CODE REVIEW

**Comment by MortimerGoro** [comment]
@kvark yes, version bumped :)

**Comment by kvark** [comment]
Thanks!
@bors-servo r+

**Comment by Gankro** [comment]
Note: `mach vendor rust` in Firefox seems to vomit while processing this `gleam` update -- specifically when it hits `gkrust`.

```
/Users/ABeingessner/.cargo/bin/cargo update --manifest-path /Users/ABeingessner/dev/firefox/src/mozilla-central/toolkit/library/rust/Cargo.toml -p gkrust
Error running mach:

    ['vendor', 'rust']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

Exception: Process executed with non-0 exit code 101: ['/Users/ABeingessner/.cargo/bin/cargo', u'update', u'--manifest-path', u'/Users/ABeingessner/dev/firefox/src/mozilla-central/toolkit/library/rust/Cargo.toml', u'-p', u'gkrust']

  File "/Users/ABeingessner/dev/firefox/src/mozilla-central/python/mozbuild/mozbuild/mach_commands.py", line 1805, in vendor_rust
    vendor_command.vendor(**kwargs)
  File "/Users/ABeingessner/dev/firefox/src/mozilla-central/python/mozbuild/mozbuild/vendor_rust.py", line 275, in vendor
    self._run_command_in_srcdir(args=[cargo, 'update', '--manifest-path', mozpath.join(path, 'Cargo.toml'), '-p', lib])
  File "/Users/ABeingessner/dev/firefox/src/mozilla-central/python/mozbuild/mozbuild/base.py", line 600, in _run_command_in_srcdir
    return self.run_process(cwd=self.topsrcdir, **args)
  File "/Users/ABeingessner/dev/firefox/src/mozilla-central/python/mach/mach/mixin/process.py", line 147, in run_process
    raise Exception('Process executed with non-0 exit code %d: %s' % (status, args))
```

I don't know enough about the vendoring process to know if this is normal/expected, so I'm just posting this here so it's recorded somewhere persistent!

**Comment by staktrace** [comment]
I think the `mach vendor rust` problem is a result of limitations in the `cargo update` command and our vendoring process. I'm not sure of what a proper fix would be, but for now what I'm going to suggest is to run `cargo update -p webrender_traits -p gleam` in both `toolkit/library/rust` and `toolkit/library/gtest/rust` before running `mach vendor rust`. That should fix it for you locally, and I'll try to figure out how to fix it more properly.

**Pull request merged**
