### PR TITLE
Add a benchmark / stress test that has 8192 image templates.

### PR DESCRIPTION
**Pull request by glennw**
This is a good test case for resource cache / hashing performance.

### CODE REVIEW

**Comment by kvark** [comment]
Can we have a script in the repo that generates this test?

**Comment by glennw** [comment]
Do you mean instead of checking this file in, or in addition to having the file checked in?

I did generate it with a python script, so can tidy that up and either add it here or as a follow up.

**Comment by kvark** [comment]
I think it's fine to check it in, but having the generating source would be useful. So yes, let's have this python script somewhere (`/script/`?)

**Comment by glennw** [comment]
Closing since it's included in https://github.com/servo/webrender/pull/1540 and reviewed as part of that.

**Pull request closed without merging**
