### PR TITLE
A variety of clippy fixes.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1065)

### CODE REVIEW

**Comment by kvark** [comment]
Looks sane, thanks!
@bors-servo r+

**Comment by glennw** [comment]
@waywardmonkeys This will need a rebase, then we'll get it merged.

**Comment by waywardmonkeys** [comment]
@glennw Rebased and force pushed.

**Pull request merged**
