### PR TITLE
Support inset/outset border styles as brush primitives.

### PR DESCRIPTION
**Pull request by gw3583**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2778)

### CODE REVIEW

**Comment by gw3583** [comment]
r? @kvark or anyone

Pending try:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=e7a27e35202cb05b7ecff0943ef3b51358289c1a

**Comment by gw3583** [comment]
Try run is as expected (lots of unrelated orange also occurring on m-c, a few expected fuzziness failures from the previous border PR, no new failures).

**Comment by gw3583** [comment]
(This is included in #2779).

**Comment by mrobinson** [comment]
@bors-servo r+

This looks good to me.

**Pull request merged**
