### PR TITLE
Scattered GPU cache updates

### LINKED ISSUE #2110: PBO copies are slow on Angle
It appears that Windows/Angle spends tons of time in `update_texture_from_pbo`: https://perfht.ml/2zJnkg4
Angle decided to defer mapping and filling an actual D3D11 staging buffer up until this call. Since the copy itself is done in a draw call, it has to stall the GPU until the copy is done. This is one issue, but the actual current one is different: `Map` itself is waiting. I suppose it's waiting for the GPU considering the texture is still in use, which implies our PBO orphaning doesn't work as expected (see `Device::orphan_pbo`).

cc @jrmuizel @glennw

### PR DESCRIPTION
**Pull request by kvark**
Fixes #2110

This PR introduces the GPU cache uploading via shader writes. It minimizes the amount of data we need to transfer to the GPU in order to reduce the stalls and make us scale better with content (see https://github.com/servo/webrender/issues/2132#issuecomment-348735499).

Note: in terms of efficiency, rasterizing lines would be much better than points. Leaving this for the follow up. Doing so would require us to upload the source data into a texture as opposed to a buffer, and slightly (but non-critically) complicate things.

WIP, because:
  - benchmarking is TODO
  - to be squashed eventually

Try push: https://treeherder.mozilla.org/#/jobs?repo=try&revision=f583b2deae1c7312437638bdda6ddc65693d53ed

r? @glennw

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2162)

### CODE REVIEW

**Comment by glennw** [comment]
I like the general idea of this, but I think that F32 targets are not renderable on ES3 - which would mean this isn't usable on ANGLE?

**Comment by pcwalton** [comment]
Half precision float should be part of GLES3. It's part of WebGL 2. If you can get away with f16 render targets, you should be good.

**Comment by kvark** [comment]
@pcwalton I don't see RGBA16F supported as color-renderable in GLES 3.1. However, it appears that we can use RGBA32UI and cast/reinterpret the floats to/from it, given that we need no filtering.

**Comment by pcwalton** [comment]
Oh, I guess not. Well, all hardware I've tested supports half-float as an extension (the straggler being PowerVR, as it only supports R16F, not R32F).

**Comment by glennw** [comment]
Unfortunately I don't think ANGLE exposes any extensions for that, which is primarily what this is for.

**Comment by pcwalton** [comment]
Really? Pathfinder relies on that extension and works on my Windows laptop in WebGL…

**Comment by glennw** [comment]
Huh, interesting! Which extension is it you're relying on? I'll check on my Windows laptop if it's present with ANGLE.

**Comment by pcwalton** [comment]
@glennw Looks like it's these:

https://developer.mozilla.org/en-US/docs/Web/API/OES_texture_half_float

https://developer.mozilla.org/en-US/docs/Web/API/EXT_color_buffer_half_float

**Comment by glennw** [comment]
OK, I can see that https://chromium.googlesource.com/chromium/src/gpu/+/master/GLES2/extensions/CHROMIUM/CHROMIUM_color_buffer_float_rgba.txt is available on my Windows laptop. @kvark So it looks like we can render to F32 on ANGLE...

**Comment by kvark** [comment]
Here is some good news, bad news, and a somewhat ugly conclusion.

### Good
I managed to fix the correctness/Angle issues, making it run now on all platforms. 🎉 
Angle is quite picky about the shader code, it decided to ignore my scatter draw call because the VS didn't assign anything to `gl_PointSize`...

### Bad
Benchmarking with MotionMark on a Windows/Angle machine didn't show any speedup. In fact, the scores were even ~10 lower, within the margin of measurement error. On the other hand, we don't appear to be nearly bottlenecked by the GPU cache updates. Compositor time I've seen is either mostly waiting, or doing texture uploads (which have been optimized to be Angle-friendly).

Perhaps, we can come up with a stronger test case that stresses the hell out of GPU cache, e.g. by using a thousand of borders?..

### Ugly
The PR brings a bit of a nicer code overall, and it would be nice to reserve this option (to minimize the GPU cache transfers) for the future. So we have a tentative agreement with @glennw to disable it by default and merge.

**Comment by glennw** [comment]
Reviewed 2 of 4 files at r1, 4 of 5 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[webrender/res/gpu_cache_update.glsl, line 14 at r4](https://reviewable.io:443/reviews/servo/webrender/2162#-L-rtNhq7UVDTgpyBiw3:-L-rtNhq7UVDTgpyBiw4:b-ggniwg) ([raw file](https://github.com/servo/webrender/blob/8eeeae048910b81e8b60a17c45f519338f1e1a86/webrender/res/gpu_cache_update.glsl#L14)):*
> ```GLSL
> 
> void main() {
> 	vData = aValue;
> ```

nit: tabs here instead of spaces

---

*[webrender/src/device.rs, line 411 at r4](https://reviewable.io:443/reviews/servo/webrender/2162#-L-rtYZB6ds2VLne_2De:-L-rtYZCLzcSPiU_SDHh:b6zzob8) ([raw file](https://github.com/servo/webrender/blob/8eeeae048910b81e8b60a17c45f519338f1e1a86/webrender/src/device.rs#L411)):*
> ```Rust
>     }
> 
>     pub fn streaw_with<'a>(&self, attributes: &'a [VertexAttribute]) -> Stream<'a> {
> ```

nit: spelling

---

*[webrender/src/renderer.rs, line 74 at r4](https://reviewable.io:443/reviews/servo/webrender/2162#-L-ruE-FP0Ce8T3oeV9w:-L-ruE-FP0Ce8T3oeV9x:b-f29qha) ([raw file](https://github.com/servo/webrender/blob/8eeeae048910b81e8b60a17c45f519338f1e1a86/webrender/src/renderer.rs#L74)):*
> ```Rust
> 
> pub const MAX_VERTEX_TEXTURE_WIDTH: usize = 1024;
> const GPU_CACHE_RESIZE_TEST: bool = false;
> ```

Let's add a comment here describing what this is for, if we still need it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/2162)*

**Comment by glennw** [comment]
@kvark Looks good! Added a few very minor nits, r=me once those are resolved. I leave it to your judgment if we need a try run here :)

**Comment by kvark** [comment]
Thanks @glennw !
Notes are addressed. The try run has 1 unexpected pass and 1 unexpected failure (in same-filter): https://treeherder.mozilla.org/#/jobs?repo=try&revision=f583b2deae1c7312437638bdda6ddc65693d53ed&selectedJob=150711942
Not sure if those are expected (will check later, unless you know out of hand).

Also, I believe the scatter-enabled Gecko is a little bit snappier at start, for it uses blitting for GPU texture cache resizing, which helps to grow the height from 512 to 2048 without hitches.

**Comment by glennw** [comment]
@kvark Yes, those are expected differences with current WR master.

**Comment by staktrace** [comment]
This PR caused panics on windows reftest runs: https://bugzilla.mozilla.org/show_bug.cgi?id=1424280#c8

**Comment by staktrace** [comment]
I filed #2208 for this regression with a more useful backtrace.

**Pull request merged**
