### PR TITLE
Store the last rendered epoch for all pipelines.

### PR DESCRIPTION
**Pull request by glennw**
Instead of storing the last rendered epoch for each pipeline from
the previous frame, accumulate this information for each frame.
This is a workaround for the way servo's compositor keeps iframes
in the frame tree when they are invisible.

Long term, we should find a better solution for this.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/388)

### CODE REVIEW

**Comment by mrobinson** [comment]
@glennw This looks good to me, so r=mrobinson unless you explicitly want @pcwalton to look at this.

**Comment by pcwalton** [comment]
Could you add a link to the Servo issue number in the comment?

**Comment by glennw** [comment]
@pcwalton Rebased and added comment.

**Pull request merged**
