### PR TITLE
Port dot/dash to border brushes, remove old border code.

### PR DESCRIPTION
**Pull request by gw3583**
This ports the last remaining legacy border styles to run with
the new border brush implementation.

With the complete, it's possible to remove all the old border
path code and shaders.

The dash/dot placement is not quite the same as the previous
code. It's better in some cases, and worse in others. Working
on this as a follow up to handle all the possible edge cases
should be much easier once this patch lands.

This completes the work of moving borders to be brush images,
which gives some very significant performance wins - mostly
stemming from (a) caching of border primitives across scrolls
and display lists and (b) much better batching during the main
scene pass, since all borders are now batched as brush_images.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2795)

### CODE REVIEW

**Comment by gw3583** [comment]
This is [WIP] for now. The placement and alignment of dots and dashes still need a little bit of work. But the bulk of the patch should remain the same and can be reviewed now.

**Comment by gw3583** [comment]
@staktrace This is the PR that I mentioned in bugzilla related to the detected memory increase. This patch removes the 3 legacy shaders that are replaced by ```cs_border_segment```. I still think it unlikely that the memory increase was caused by the new shader, but we can compare when this lands in gecko.

**Comment by gw3583** [comment]
I tweaked the dot / dash placement code a little. It still needs work in a future follow up, but I think it's good enough for now.

The latest try run is:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=e9df2b78275672bf73ab57f81b511c2acc455d67&selectedJob=181280623

The results match up with current expectations of WR master, except for one test - ```box-decoration-break-with-inset-box-shadow-1.html```

This has become a PASS on OS X, and a FAIL on Linux with ~100 more fuzzy pixels. Since the fuzz is already very high on this test in Linux, I think adding a little extra is fine, although will get @staktrace to confirm that.

r? @kvark

**Comment by staktrace** [comment]
Yup, the extra fuzz on `box-decoration-break-with-inset-box-shadow-1.html` looks reasonable.

**Comment by kvark** [comment]
Amazing work! Left my comments below

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[webrender/res/brush_image.glsl, line 98 at r2](https://reviewable.io/reviews/servo/webrender/2795#-LDwsGHW6iJ-MRACgIvJ:-LDwsGHW6iJ-MRACgIvK:b7ry104) ([raw file](https://github.com/servo/webrender/blob/fbdf5999465c45615258d3509f69cfbbbfcb4c2c/webrender/res/brush_image.glsl#L98)):*
> ```GLSL
>         //       is used for other purposes in the future.
>         if ((brush_flags & BRUSH_FLAG_SEGMENT_REPEAT_X) != 0) {
>             stretch_size.x = (texel_rect.z - texel_rect.x) / uDevicePixelRatio;
> ```

why are we dividing the texels by the device-pixel ratio? it's not device-texel ration after all :)

---

*[webrender/res/cs_border_segment.glsl, line 198 at r2](https://reviewable.io/reviews/servo/webrender/2795#-LDwssoq8-sQ3MRMwOv8:-LDwssoq8-sQ3MRMwOv9:b-9jo04y) ([raw file](https://github.com/servo/webrender/blob/fbdf5999465c45615258d3509f69cfbbbfcb4c2c/webrender/res/cs_border_segment.glsl#L198)):*
> ```GLSL
>     //           dash clips!
>     if (clip_mode == CLIP_DOT) {
>         float expanded_radius = aClipParams1.z + 2.0;
> ```

where does 2.0 come from?

---

*[webrender/res/cs_border_segment.glsl, line 199 at r2](https://reviewable.io/reviews/servo/webrender/2795#-LDwt0Av5eKW6ILYteTM:-LDwt0Aw8KVSLGuayH1O:b7ucbxt) ([raw file](https://github.com/servo/webrender/blob/fbdf5999465c45615258d3509f69cfbbbfcb4c2c/webrender/res/cs_border_segment.glsl#L199)):*
> ```GLSL
>     if (clip_mode == CLIP_DOT) {
>         float expanded_radius = aClipParams1.z + 2.0;
>         vPos = vClipParams1.xy - vec2(expanded_radius);
> ```

nit: could be `vPos = vClipParams1.xy + expanded_radius * (2.0 * aPosition.xy - 1.0);`

---

*[webrender/res/cs_border_segment.glsl, line 322 at r2](https://reviewable.io/reviews/servo/webrender/2795#-LDwu1wi9O75tyOqMWCC:-LDwu1wj00byQBq-MyuP:bui4168) ([raw file](https://github.com/servo/webrender/blob/fbdf5999465c45615258d3509f69cfbbbfcb4c2c/webrender/res/cs_border_segment.glsl#L322)):*
> ```GLSL
>     bool in_clip_region = all(lessThan(vClipCenter_Sign.zw * clip_relative_pos, vec2(0.0)));
> 
>     switch (clip_mode) {
> ```

can we move the declaration of `d` closer to here where it's initialized?

---

*[webrender/src/border.rs, line 353 at r2](https://reviewable.io/reviews/servo/webrender/2795#-LDwvRScEx4afuWqvvfe:-LDwvRSdD7NCSn4mOv-V:bpfpk4m) ([raw file](https://github.com/servo/webrender/blob/fbdf5999465c45615258d3509f69cfbbbfcb4c2c/webrender/src/border.rs#L353)):*
> ```Rust
>                 let dash_arc_length =
>                     0.5 * self.ellipse.total_arc_length / self.max_clip_count as f32;
>                 let mut current_arc_length = 0.25 * dash_arc_length;
> ```

could you explain this bit?

---

*[webrender/src/border.rs, line 535 at r2](https://reviewable.io/reviews/servo/webrender/2795#-LDww3Xk48044MCubPGk:-LDww3Xk48044MCubPGl:b-nueg87) ([raw file](https://github.com/servo/webrender/blob/fbdf5999465c45615258d3509f69cfbbbfcb4c2c/webrender/src/border.rs#L535)):*
> ```Rust
>     avail_size: f32,
>     scale: f32,
> ) -> (f32, f32, f32) {
> ```

perhaps, return a struct with naming fields instead? that would make the calling site easier - no need to de-struct

---

*[webrender/src/border.rs, line 550 at r2](https://reviewable.io/reviews/servo/webrender/2795#-LDwvsrx16U8YAe2j-LY:-LDwvsrx16U8YAe2j-LZ:bsnjqla) ([raw file](https://github.com/servo/webrender/blob/fbdf5999465c45615258d3509f69cfbbbfcb4c2c/webrender/src/border.rs#L550)):*
> ```Rust
>             let device_size = 2.0 * dash_size * scale;
>             let offset = (extra_space * 0.5).round();
>             return (offset, used_size, device_size)
> ```

no need for `return`s at the branch ends

---

*[webrender/src/border.rs, line 953 at r2](https://reviewable.io/reviews/servo/webrender/2795#-LDwwUOC7xlBH566aZ3d:-LDwwUOC7xlBH566aZ3e:blt0sza) ([raw file](https://github.com/servo/webrender/blob/fbdf5999465c45615258d3509f69cfbbbfcb4c2c/webrender/src/border.rs#L953)):*
> ```Rust
>         BorderSegment::BottomLeft |
>         BorderSegment::BottomRight => {
>             // TODO(gw): Similarly to the old border code, we don't correctly handle a a corner
> ```

let's at least detect this case explicitly and maybe `warn!` on it

---

*[webrender/src/prim_store.rs, line 1480 at r2](https://reviewable.io/reviews/servo/webrender/2795#-LDwxQee5ixvmb3dn3RF:-LDwxQef3viUeZ_gSNJf:bjhdwtn) ([raw file](https://github.com/servo/webrender/blob/fbdf5999465c45615258d3509f69cfbbbfcb4c2c/webrender/src/prim_store.rs#L1480)):*
> ```Rust
>                     });
> 
>                     frame_state.gpu_cache.invalidate(&mut metadata.gpu_location);
> ```

why is this needed now?

---

*[webrender/src/shade.rs, line 264 at r2](https://reviewable.io/reviews/servo/webrender/2795#-LDwxa1k7a41ngSyQhl8:-LDwxa1k7a41ngSyQhl9:b5eytpe) ([raw file](https://github.com/servo/webrender/blob/5e4f257d9f3cdb5691ac62f3affe2e9189d66447/webrender/src/shade.rs#L264)):*
> ```Rust
> }
> 
> struct PrimitiveShader {
> ```

oh wow, this is an epic moment :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/servo/webrender/2795#-:-LDwxkvL3Oo2vyyJYotX:bh7uj08)*

**Comment by gw3583** [comment]
Review status: 20 of 23 files reviewed at latest revision, 9 unresolved discussions.

---

*[webrender/res/brush_image.glsl, line 98 at r2](https://reviewable.io/reviews/servo/webrender/2795#-LDwsGHW6iJ-MRACgIvJ:-LE6fCCv8TvY9Cz_uoiL:b-22kf5k) ([raw file](https://github.com/servo/webrender/blob/fbdf5999465c45615258d3509f69cfbbbfcb4c2c/webrender/res/brush_image.glsl#L98)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

why are we dividing the texels by the device-pixel ratio? it's not device-texel ration after all :)
</blockquote></details>

The texel rect is in device pixels, but the stretch size is in local space.

---

*[webrender/res/cs_border_segment.glsl, line 198 at r2](https://reviewable.io/reviews/servo/webrender/2795#-LDwssoq8-sQ3MRMwOv8:-LE6fRTU1isg1qgIrytg:b-imxp6t) ([raw file](https://github.com/servo/webrender/blob/fbdf5999465c45615258d3509f69cfbbbfcb4c2c/webrender/res/cs_border_segment.glsl#L198)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

where does 2.0 come from?
</blockquote></details>

It's an arbitrary constant to give room for AA (taken from the previous shader). I added a comment about it.

---

*[webrender/res/cs_border_segment.glsl, line 322 at r2](https://reviewable.io/reviews/servo/webrender/2795#-LDwu1wi9O75tyOqMWCC:-LE6fepE8hzu_ArsLH2Q:b-896fix) ([raw file](https://github.com/servo/webrender/blob/fbdf5999465c45615258d3509f69cfbbbfcb4c2c/webrender/res/cs_border_segment.glsl#L322)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

can we move the declaration of `d` closer to here where it's initialized?
</blockquote></details>

Done.

---

*[webrender/src/border.rs, line 353 at r2](https://reviewable.io/reviews/servo/webrender/2795#-LDwvRScEx4afuWqvvfe:-LE6nWxEAWU8p3Yw7H1b:b-e8mu2o) ([raw file](https://github.com/servo/webrender/blob/fbdf5999465c45615258d3509f69cfbbbfcb4c2c/webrender/src/border.rs#L353)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

could you explain this bit?
</blockquote></details>

It's somewhat arbitrary - I added a comment to explain.

---

*[webrender/src/border.rs, line 535 at r2](https://reviewable.io/reviews/servo/webrender/2795#-LDww3Xk48044MCubPGk:-LE6jA8U4iPDtGgwwbRi:b-896fix) ([raw file](https://github.com/servo/webrender/blob/fbdf5999465c45615258d3509f69cfbbbfcb4c2c/webrender/src/border.rs#L535)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

perhaps, return a struct with naming fields instead? that would make the calling site easier - no need to de-struct
</blockquote></details>

Done.

---

*[webrender/src/border.rs, line 550 at r2](https://reviewable.io/reviews/servo/webrender/2795#-LDwvsrx16U8YAe2j-LY:-LE6fmZY3qBxU8t7NlBc:b-896fix) ([raw file](https://github.com/servo/webrender/blob/fbdf5999465c45615258d3509f69cfbbbfcb4c2c/webrender/src/border.rs#L550)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

no need for `return`s at the branch ends
</blockquote></details>

Done.

---

*[webrender/src/border.rs, line 953 at r2](https://reviewable.io/reviews/servo/webrender/2795#-LDwwUOC7xlBH566aZ3d:-LE6m3DnE_A2DDRYX2tg:b-896fix) ([raw file](https://github.com/servo/webrender/blob/fbdf5999465c45615258d3509f69cfbbbfcb4c2c/webrender/src/border.rs#L953)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

let's at least detect this case explicitly and maybe `warn!` on it
</blockquote></details>

Done.

---

*[webrender/src/prim_store.rs, line 1480 at r2](https://reviewable.io/reviews/servo/webrender/2795#-LDwxQee5ixvmb3dn3RF:-LE6fz566-RNOBjAouDQ:bef1ksu) ([raw file](https://github.com/servo/webrender/blob/fbdf5999465c45615258d3509f69cfbbbfcb4c2c/webrender/src/prim_store.rs#L1480)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

why is this needed now?
</blockquote></details>

The segments have changed, so we need to re-upload them. I added a comment about this.

---

*[webrender/src/shade.rs, line 264 at r2](https://reviewable.io/reviews/servo/webrender/2795#-LDwxa1k7a41ngSyQhl8:-LE6g1wz4RcHDebsXGLB:b-896fix) ([raw file](https://github.com/servo/webrender/blob/5e4f257d9f3cdb5691ac62f3affe2e9189d66447/webrender/src/shade.rs#L264)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

oh wow, this is an epic moment :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/servo/webrender/2795)*

**Comment by gw3583** [comment]
@kvark Thanks for the review! All comments addressed, I think.

**Comment by kvark** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/servo/webrender/2795#-:-LEAVeNo7E2UeMfyg1oV:bnfp4nl)*

**Comment by kvark** [comment]
thank you! :ship: it
@bors-servo r+

**Pull request merged**
