### PR TITLE
Fixed inner rectangle computation for transformed clips

### LINKED ISSUE #2167: regression: Children of transformed parent elements with overflow:hidden are not displayed correctly
GH issue for https://bugzilla.mozilla.org/show_bug.cgi?id=1423104 - see the testcase on that bug.

This is a regression from #2104.

/cc @mrobinson

### PR DESCRIPTION
**Pull request by kvark**
Alternative to #2171, which it steals the test from (thanks @mrobinson !)

Fixes #2167

Try push: https://treeherder.mozilla.org/#/jobs?repo=try&revision=59424192544b000e9363f382056c68ccc7209dae

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2177)

### CODE REVIEW

**Comment by mrobinson** [comment]
The change looks good to me. Thanks for restoring the conservative inner rect calculation. I guess someone else will need to review my test.

**Comment by mrobinson** [comment]
Instead of mentioning my Github name in the test commit message, it would probably make for a cleaner git history to use the `--author=` argument.

**Comment by kvark** [comment]
Thanks @mrobinson , great idea! Fixed now.

**Comment by glennw** [comment]
It would be good to crop the reference image, but that can be done as a follow up.

@bors-servo r+

**Comment by mrobinson** [comment]
It seems that bors has been stuck today, so I've taken the liberty of opening a new PR with the test image cropped.

**Pull request closed without merging**
