### PR TITLE
Add a legend to the gpu queries debug view.

### PR DESCRIPTION
**Pull request by nical**
This displays a list of primitive types present with their colors and labels to make it easier to see what is going on in the profiler.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2074)

### CODE REVIEW

**Comment by nical** [comment]
Looks like this:

screenshot from 2017-11-21 17-00-18

**Comment by nical** [comment]
r? anyone

**Comment by mrobinson** [comment]
@bors-servo r+

Looks good to me.

**Comment by kvark** [comment]
@nical you've got some crazy amount of time in `target`, which is basically clearing stuff.

**Pull request merged**
