### PR TITLE
Capture feature split

### PR DESCRIPTION
**Pull request by kvark**
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1433910
Related - https://github.com/serde-rs/serde/issues/1153
Local measurements show no build time increase with the new "capture" feature that excludes deserialization derives 🎉 
The downside is more configuration code bloat.
cc @Gankro @dtolnay

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2359)

### CODE REVIEW

**Comment by kvark** [comment]
@glennw rebased and ready for the review.

**Comment by glennw** [comment]
Reviewed 32 of 32 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/2359)*

**Comment by kvark** [comment]
[uh](https://travis-ci.org/servo/webrender/jobs/334998115#L1004)
> error[E0554]: #![feature] may not be used on the stable release channel
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.27/src/lib.rs:89:35
89 | #![cfg_attr(feature = "unstable", feature(nonzero, specialization))

@Gankro know what's going on?

**Comment by kvark** [comment]
Looks like passing `--all-features` to WR crate itself triggered `webrender_api/nightly` feature. Sort of unexpeted. Reverted this to just "profiler,capture" now.
@bors-servo r=glennw

**Pull request merged**
