### PR TITLE
Update sha2 to 0.8

### PR DESCRIPTION
**Pull request by Eijebong**
This will dedupe sha2 in m-c

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/3447)

### CODE REVIEW

**Comment by emilio** [comment]
Err, right...

@bors-servo r+

**Comment by staktrace** [comment]
@Eijebong While I'm not opposed to bumping dependencies I just wanted to point out that this does not dedup anything in m-c and in fact adds a bunch of new stuff.

https://hg.mozilla.org/try/rev/1968173d59dea55133ae1e82c769f09d73762686

**Comment by Eijebong** [comment]
@staktrace Oh right, I did my checks with a fully updated lockfile. `cargo update -p lalrpop -p lalrpop-util` will update stuff to dedupe sha2.

**Comment by staktrace** [comment]
Doing that also bumps the regex crate to a new version which includes a 100k+ test file, and requires build peer approval to land. So if you want to do that please do it as a separate bug. When I do the WR update I'm just going to take this PR without the lalrpop update.

**Comment by Eijebong** [comment]
For reference https://bugzilla.mozilla.org/show_bug.cgi?id=1516337

**Pull request merged**
