### PR TITLE
support Windows variation fonts

### PR DESCRIPTION
**Pull request by lsalzman**
This uses the new variation font support in DWrote so that we can fix Gecko bug https://bugzilla.mozilla.org/show_bug.cgi?id=1441323

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/3105)

### CODE REVIEW

**Comment by lsalzman** [comment]
This is because Pathfinder is pulling in an older version of dwrote. I think the only way to fix that is for him to update the deposit. Nothing I can do on this side.

**Comment by lsalzman** [comment]
Rather him = @pcwalton

**Comment by pcwalton** [comment]
I'm on it.

**Comment by pcwalton** [comment]
Updated the `webrender` branch of Pathfinder to the latest version of `winapi`. Let me know if you run into any problems with it.

**Pull request merged**
