### PR TITLE
Various small changes related to caching text runs with brushes.

### PR DESCRIPTION
**Pull request by glennw**
* Remove unused subpixel blend mode (can retrieve via git if we need later).
* Switch brush_image shader to do mask swizzling the same way as text shader.
  * This allows handling the various subpx modes in brush_image for later.
  * It's more flexible, a superset of existing brush_image swizzle modes.
* Remove BrushImageSourceKind.
* Store two colors inline with the brush primitive data for images / pictures.
  * These are always fetched in the brush_image VS.
  * Extra data is only fetched when drawing drop-shadows / screen-space images.
* Rename TextShaderMode -> ShaderColorMode, move to prim_shared.
* Allow batching code to correctly handle multi-pass mode for any batch kind.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2674)

### CODE REVIEW

**Comment by glennw** [comment]
These are small changes that I can land incrementally, pulled from my local
branch where I am working on drawing (and caching) text runs as brushes. Some
of them probably don't make a heap of sense individually, but are hopefully
easier to review if we can land bits incrementally.

Pending try:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=99dfc3dde70c4a8b8a6a52cebe645c92854a51b7

r? @kvark

**Comment by staktrace** [comment]
Yeah the oranges look unrelated, at least two of them I've seen before and the Wr6 orange looks like a random intermittent.

**Comment by kvark** [comment]
:lgtm: left a few notes

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[webrender/res/ps_text_run.glsl, line 143 at r1](https://beta.reviewable.io/reviews/servo/webrender/2674#-LAU-BJ85vuw1jQci_Cm:-LAU-BJ85vuw1jQci_Cn:b62njme) ([raw file](https://github.com/servo/webrender/blob/6394ce5e7ea8230e2084010d896e98c7a2be1878/webrender/res/ps_text_run.glsl#L143)):*
> ```GLSL
>             vColor = vec4(text.color.a);
>             break;
>         case COLOR_MODE_SUBPX_BG_PASS1:
> ```

looks like an opportunity to share this logic with `brush_image`

---

*[webrender/src/batch.rs, line 753 at r1](https://beta.reviewable.io/reviews/servo/webrender/2674#-LAU-OCH1sNymYhY1fMG:-LAU-OCH1sNymYhY1fMH:bhxmbux) ([raw file](https://github.com/servo/webrender/blob/6394ce5e7ea8230e2084010d896e98c7a2be1878/webrender/src/batch.rs#L753)):*
> ```Rust
>                                             let extra_data_address = gpu_cache.get_address(&picture.extra_gpu_data_handle);
>                                             let shadow_prim_address = extra_data_address.offset(2);
>                                             let shadow_data_address = extra_data_address.offset(8);
> ```

can we have those defined somewhere? (bonus points for use elsewhere and/or assertions to match the size during the GPU data population)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/servo/webrender/2674#-:-LAU-wxu07FX-BoCoNis:blwyo0g)*

**Comment by glennw** [comment]
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[webrender/res/ps_text_run.glsl, line 143 at r1](https://beta.reviewable.io/reviews/servo/webrender/2674#-LAU-BJ85vuw1jQci_Cm:-LAUedLe7WyUNlMLFVeO:bgtzyn5) ([raw file](https://github.com/servo/webrender/blob/6394ce5e7ea8230e2084010d896e98c7a2be1878/webrender/res/ps_text_run.glsl#L143)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

looks like an opportunity to share this logic with `brush_image`
</blockquote></details>

I haven't done that yet, since if things work out here, ps_text_run will be disappearing soon :) If that doesn't happen, then we should definitely share this code in a function.

---

*[webrender/src/batch.rs, line 753 at r1](https://beta.reviewable.io/reviews/servo/webrender/2674#-LAU-OCH1sNymYhY1fMG:-LAUeoR19PbVb9cvzOgu:b-wmd0jo) ([raw file](https://github.com/servo/webrender/blob/6394ce5e7ea8230e2084010d896e98c7a2be1878/webrender/src/batch.rs#L753)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

can we have those defined somewhere? (bonus points for use elsewhere and/or assertions to match the size during the GPU data population)
</blockquote></details>

For now, I've made them constants and added a comment near the code in picture.rs that they need to be updated. We should aim to make this type-safe and/or assert in the future though, for sure.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/servo/webrender/2674)*

**Comment by kvark** [comment]
thanks!
@bors-servo r+

**Pull request merged**
