### PR TITLE
Update thread_profiler version.

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1281)

### CODE REVIEW

**Comment by glennw** [comment]
Oh, the change in ```thread_profiler``` uses serde_json 1.0 - but it looks like everything else in WR / Servo is on v0.9. @nox Do you know if we're planning to update serde_json in Servo in the near future, or perhaps I'd be best to downgrade the serde_json version used in thread_profiler?

**Comment by nox** [comment]
I intentto update serde and whatnot but was too busy with stylo things.

**Comment by glennw** [comment]
Closing for now - can reopen when the serde update lands.

**Pull request closed without merging**
