### PR TITLE
Add mousewheel support to the scrolling example

### PR DESCRIPTION
**Pull request by mrobinson**
This makes it a bit easier to quickly scrolling the different layers.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1164)

### CODE REVIEW

**Comment by staktrace** [comment]
Is it possible to read out the scroll offset using the WR API? Because it would be nice to update the `root_scroller_pos` and `nested_scroller_pos` values in the ScrollState when you wheel-scroll, otherwise the keyboard scrolling state gets out of sync.

**Comment by mrobinson** [comment]
@staktrace Okay, I've eliminated the need to sync the scrolling states with the keyboard scrolling in the latest patch. I think this also simplifies this in the way that we discussed via IRC.

**Comment by staktrace** [comment]
LGTM, thanks!

**Comment by kvark** [comment]
Looks clean.
@bors-servo r+

**Comment by kvark** [comment]
Eh, there we go again, Mac bots (also see #1155)

**Pull request merged**
