### PR TITLE
Slimmed down reference frame API

### PR DESCRIPTION
**Pull request by kvark**
This is another part of #3251 that can be merged separately.
cc @staktrace 
(pending) try: https://treeherder.mozilla.org/#/jobs?repo=try&revision=c0694fe869fbf7fd018a1a0b2d597af97516934c

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/3450)

### CODE REVIEW

**Comment by kvark** [comment]
This should be ready for a review, assuming try is turning green ;)

**Comment by staktrace** [comment]
Looks like there's an assertion failure, plus some reftest failures?

**Comment by kvark** [comment]
oh right, that's a proper error I didn't see for running reftests in release mode. On it now

**Comment by kvark** [comment]
Actually, trying to re-fit the iframe item changes to the old API doesn't work out well. Let's not do it, and just keep it a part of the original APi-changing PR, should we?
Try push with just the RF changes: https://treeherder.mozilla.org/#/jobs?repo=try&revision=d47fcc17ed84213df01a7c52f52040124afc4b55

**Comment by staktrace** [comment]
Ok. This patch is simple enough, r+ assuming the try is green

**Comment by kvark** [comment]
Try is looking green, and the patch is generally harmless.
@bors-servo r=staktrace

gecko patch:
```diff
--- a/gfx/webrender_bindings/src/bindings.rs
+++ b/gfx/webrender_bindings/src/bindings.rs
@@ -1849,17 +1849,17 @@ pub extern "C" fn wr_dp_restore(state: &
 
 #[no_mangle]
 pub extern "C" fn wr_dp_clear_save(state: &mut WrState) {
     state.frame_builder.dl_builder.clear_save();
 }
 
 #[no_mangle]
 pub extern "C" fn wr_dp_push_stacking_context(state: &mut WrState,
-                                              bounds: LayoutRect,
+                                              mut bounds: LayoutRect,
                                               clip_node_id: *const WrClipId,
                                               animation: *const WrAnimationProperty,
                                               opacity: *const f32,
                                               transform: *const LayoutTransform,
                                               transform_style: TransformStyle,
                                               perspective: *const LayoutTransform,
                                               mix_blend_mode: MixBlendMode,
                                               filters: *const WrFilterOp,
@@ -1935,32 +1935,32 @@ pub extern "C" fn wr_dp_push_stacking_co
     }
 
     let perspective_ref = unsafe { perspective.as_ref() };
     let perspective = match perspective_ref {
         Some(perspective) => Some(perspective.clone()),
         None => None,
     };
 
-    let mut prim_info = LayoutPrimitiveInfo::new(bounds);
-
     *out_is_reference_frame = transform_binding.is_some() || perspective.is_some();
     if *out_is_reference_frame {
         let ref_frame_id = state.frame_builder
             .dl_builder
-            .push_reference_frame(&prim_info, transform_style, transform_binding, perspective);
+            .push_reference_frame(&bounds, transform_style, transform_binding, perspective);
         *out_reference_frame_id = pack_clip_id(ref_frame_id);
 
-        prim_info.rect.origin = LayoutPoint::zero();
-        prim_info.clip_rect.origin = LayoutPoint::zero();
+        bounds.origin = LayoutPoint::zero();
         state.frame_builder.dl_builder.push_clip_id(ref_frame_id);
     }
 
-    prim_info.is_backface_visible = is_backface_visible;
-    prim_info.tag = state.current_tag;
+    let prim_info = LayoutPrimitiveInfo {
+        is_backface_visible,
+        tag: state.current_tag,
+        .. LayoutPrimitiveInfo::new(bounds)
+    };
 
     state.frame_builder
          .dl_builder
          .push_stacking_context(&prim_info,
                                 clip_node_id,
                                 transform_style,
                                 mix_blend_mode,
                                 &filters,
```

**Pull request merged**
