### PR TITLE
Forbid segmentation of tiled images

### PR DESCRIPTION
**Pull request by kvark**
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1470855
r? @gw3583

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2850)

### CODE REVIEW

**Comment by gw3583** [comment]
Could we store (if we don't already) whether tiling is enabled inside ```BrushKind::Image``` I wonder? That would mean we don't need to pass resource cache, and avoid a resource cache hash lookup each time we call supports_segments? In general, looks good though!

**Comment by kvark** [comment]
I think it would be semantically nicer to have `visible_tiles: Option<Vec<...>>` in there, as you suggest. I'll give it a try tomorrow.

**Comment by kvark** [comment]
@gw3583 actually, we don't have easy access to the tiling information during flattening, where `visible_tiles` is first initialized, so I don't think this is a good path. I think we should just merge the PR as is. cc @nical

**Comment by gw3583** [comment]
@kvark OK, sounds good. Is it possible to add a reftest for this?

**Comment by kvark** [comment]
Added now. I also confirmed that it fails with the previous revision.

**Pull request merged**
