### PR TITLE
Fix bug I introduced during the render task tree refactor in composites.

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1598)

### CODE REVIEW

**Comment by glennw** [comment]
r? @kvark 

cc @staktrace 

This passes the wrench tests, Servo WPT/CSS suite. I've tested the ```css-blend``` reftest directory locally in Gecko (where the reftest failures were) and these all pass now.

A complete Gecko try run is pending:

https://hg.mozilla.org/try/rev/c4f6acfc28b562ff1fc1face225ff81b5c6aa8fa
https://treeherder.mozilla.org/#/jobs?repo=try&revision=c4f6acfc28b562ff1fc1face225ff81b5c6aa8fa

**Comment by glennw** [comment]
I'm still working on a local wrench test that will reproduce the bug to prevent regressions in the future, but this can be reviewed now.

**Comment by glennw** [comment]
Added a regression reftest for this bug, and the try run looks like it is green now.

**Comment by kvark** [comment]
Wrench fails to build on windows though:
https://ci.appveyor.com/project/servo/webrender/build/1.0.4915#L604

**Comment by kvark** [comment]
Try push seems to be green - https://treeherder.mozilla.org/#/jobs?repo=try&revision=c4f6acfc28b562ff1fc1face225ff81b5c6aa8fa

**Comment by glennw** [comment]
@kvark Thanks! The windows / appveyor failures are occurring on all PRs at the moment. I haven't had a chance to look into it - I suspect the rustc version might be the cause?

**Pull request merged**
