### PR TITLE
Separate interning text run

### PR DESCRIPTION
**Pull request by djg**
First part of separating Primitives into separate interned data.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/3369)

### CODE REVIEW

**Comment by gw3583** [comment]
Looks like there is a reftest failure on CI:

```
REFTEST TEST-UNEXPECTED-FAIL | reftests\text\shadow.yaml == reftests\text\shadow-ref.yaml | image comparison, max difference: 131, number of differing pixels: 6425
```

Any chance you could do a talos run before review, just to give an idea what effect it has on dl_mutate (even just to make sure it doesn't regress, for now, since we probably won't get big wins from this initial work)?

**Comment by gw3583** [comment]
(partial review only so far, will work through this today).

**Comment by djg** [comment]
> (partial review only so far, will work through this today).

Thanks @gw3583

**Comment by djg** [comment]
@gw3583 Ping

**Comment by gw3583** [comment]
Sorry, all-hands jetlag and that - I was going to take a more detailed look in the morning, but I think it probably looks good in general now, or the remaining bits could be done as follow ups. Did we work out what effect this has on talos?

**Comment by gw3583** [comment]
Probably worth getting @kvark to take a quick look too, if he has time.

**Comment by djg** [comment]
I'm currently working through removing the conflict with servo/master. Update shortly.

@gw3583 It had a slight improvement on talos, but I wasn't expecting much of a change yet.

**Comment by gw3583** [comment]
@djg Yea, I wouldn't expect a large improvement until we separate solid rects. As long as it doesn't regress, we're good for now :+1:

**Comment by gw3583** [comment]
Sorry, this got conflicts again - I think it should be good to go once those conflicts are resolved?

**Comment by djg** [comment]
Gecko try run:  https://treeherder.mozilla.org/#/jobs?repo=try&revision=b66118f88f9306e0d2fd6a94df9da24fb71a7135

**Comment by djg** [comment]
@gw3583 Apparently there is one comment to resolve?

**Comment by gw3583** [comment]
I think it's fine to get this merged now, to avoid any more rebase issues. We should be able to fix up any remaining changes as follow ups.

**Pull request merged**
