### PR TITLE
Sync changes from mozilla-central

### PR DESCRIPTION
**Pull request by moz-gfx**

### CODE REVIEW

**Comment by jrmuizel** [comment]
This got broke by rust 1.39 which just so happened to come out now.

**Comment by SimonSapin** [comment]
Temporarily removing `RUSTFLAGS='--deny warnings'` in CI configuration could be a way to unblock this until a proper fix lands in https://bugzilla.mozilla.org/show_bug.cgi?id=1564873

**Comment by petemoore** [comment]
> Temporarily removing `RUSTFLAGS='--deny warnings'` in CI configuration could be a way to unblock this until a proper fix lands in https://bugzilla.mozilla.org/show_bug.cgi?id=1564873

Thanks @SimonSapin!

I'm landing https://lando.services.mozilla.com/D52360/ (currently queued), so hopefully it should get merged back here soon.

**Comment by petemoore** [comment]
Note, when https://treeherder.mozilla.org/#/jobs?repo=autoland&revision=c61c05f3707767aaf77f7cffa741c86ef44ace2d completes, I'm hoping the Community-TC (pull request) task will pass.

**Pull request merged**
