### PR TITLE
Add display list items for marking content caching region.

### PR DESCRIPTION
**Pull request by gw3583**
This is an experimental API - we may need to change how this
works, depending on how we integrate it into Gecko.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/3389)

### CODE REVIEW

**Comment by gw3583** [comment]
This provides the API hooks for marking the region(s) of a display list that should be cached, allowing Gecko to specify where the main scroll root for the content region exists.

It doesn't actually _do_ anything with those markers yet, this initial patch is just to see if the API seems reasonable, and allow the Gecko integration work to be done.

Does this seem like all we would need @mstange @mattwoodrow @jrmuizel ?

**Comment by gw3583** [comment]
(The scroll root is supplied by the normal WR mechanism, with push/pop clip id methods. We could explicitly make it include the scroll root id if preferred?)

**Comment by kvark** [comment]
We've talked about this with @gw3583 a bit, and this appears to be an acceptable interim solution. We can't get this caching scope bound to any existing item, and will in future revise this based on the results.

**Pull request merged**
