### PR TITLE
Texture update strategies

### LINKED ISSUE #2110: PBO copies are slow on Angle
It appears that Windows/Angle spends tons of time in `update_texture_from_pbo`: https://perfht.ml/2zJnkg4
Angle decided to defer mapping and filling an actual D3D11 staging buffer up until this call. Since the copy itself is done in a draw call, it has to stall the GPU until the copy is done. This is one issue, but the actual current one is different: `Map` itself is waiting. I suppose it's waiting for the GPU considering the texture is still in use, which implies our PBO orphaning doesn't work as expected (see `Device::orphan_pbo`).

cc @jrmuizel @glennw

### PR DESCRIPTION
**Pull request by kvark**
~~Fixes  #2110, hopefully: still to be benchmarked on Windows.~~
Provide the settings for Gecko to fix ^^

Try push: https://treeherder.mozilla.org/#/jobs?repo=try&revision=12fecf240aa3440764cd64205b17bfcfe7eb252c

r? @glennw

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2147)

### CODE REVIEW

**Comment by glennw** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/2147)*

**Comment by kvark** [comment]
Oh, forgot to mention also that the PR optimizes the GPU cache PBO transfers by allocating a buffer once instead of orphaning it multiple times.

**Comment by kvark** [comment]
The try push contains quite a few failures, many related to text, so it might not be this PR. Investigating...

**Comment by glennw** [comment]
@kvark The current wr-future bug contains a patch from @lsalzman which fixes all the font failures when trying on WR master. I hit this yesterday :)

**Comment by kvark** [comment]
@glennw thanks!
Latest push with Lee's fix in it: https://treeherder.mozilla.org/#/jobs?repo=try&revision=981a2e19c39d40f63ebe6c73fc65a6d5534ecb99

I'd say that the PR is good to go if the tests are green. If, somehow, the `UploadMode::Immediate` default on Windows appears to be slower, we can just select `UploadMode::PixelBuffer(Stream)` in the `RendererOptions` for Gecko/Servo until it's sorted out.

**Comment by jrmuizel** [comment]
This commit may regress the CSS bouncing blend circles on AMD Windows. I need to still confirm.

**Comment by glennw** [comment]
@jrmuizel Do you mean with native GL or ANGLE?

**Comment by jrmuizel** [comment]
This was with ANGLE

**Comment by kvark** [comment]
I found the bug in the code, fixed it, and also switched the PBO upload method on Windows to the same as it is now. So the only functional change would be the bulk upload of CPU cache data.
Also, try push is green: https://treeherder.mozilla.org/#/jobs?repo=try&revision=12fecf240aa3440764cd64205b17bfcfe7eb252c
I think it's safe to land, but more benchmarking is pending.

**Comment by kvark** [comment]
## Benchmarking MotionMark results on Windows/AMD/Angle

### Experiment steps:
  - set up the settings (reading from a file)
  - boot up firefox in full screen
  - jump to the bouncing circles test with ramping complexity
  - test it 3 times in a row

### Scores

- `Immediate`: 192, 181, 168
- `PixelBuffer(Static)`: 156, 176, 168
- `PixelBuffer(Dynamic)`: 145, 142, 149
- `PixelBuffer(Stream)`: 153, 135, 127

### Analysis

Good thing is - the scores support our expectations about what should be fast. Both `Dynamic` and `Stream` PBO uploads are slow, with the current default arguably being the worst (on this configuration!). Both `Static` PBO and `Immediate` are quite fast.

I'm going to benchmark pure GL on the main platforms as well. Here is the local patch I use to make it run-time configurable:
```diff
diff --git a/gfx/webrender_bindings/src/bindings.rs b/gfx/webrender_bindings/src/bindings.rs
index 4365919..a7c0e79 100644
--- a/gfx/webrender_bindings/src/bindings.rs
+++ b/gfx/webrender_bindings/src/bindings.rs
@@ -10,7 +10,7 @@ use gleam::gl;
 use webrender::api::*;
 use webrender::{ReadPixelsFormat, Renderer, RendererOptions, ThreadListener};
 use webrender::{ExternalImage, ExternalImageHandler, ExternalImageSource};
-use webrender::DebugFlags;
+use webrender::{DebugFlags, UploadMethod, VertexUsageHint};
 use webrender::{ApiRecordingReceiver, BinaryRecorder};
 use webrender::ProgramCache;
 use thread_profiler::register_thread_with_profiler;
@@ -718,10 +718,30 @@ pub extern "C" fn wr_window_new(window_id: WrWindowId,
         Arc::clone(&(*thread_pool).0)
     };
 
+    let upload_method = {
+        use std::fs::File;
+        use std::io::Read;
+        let mut string = String::new();
+        match File::open("c:/Code/pbo-usage.txt") {
+            Ok(mut file) => {
+                file.read_to_string(&mut string).unwrap();
+                let hint = match string.as_str() {
+                    "static" => VertexUsageHint::Static,
+                    "dynamic" => VertexUsageHint::Dynamic,
+                    "stream" => VertexUsageHint::Stream,
+                    _ => panic!(format!("Unknown usage {}", string)),
+                };
+                UploadMethod::PixelBuffer(hint)
+            },
+            Err(_) => UploadMethod::Immediate,
+        }
+    };
+
     let opts = RendererOptions {
         enable_aa: true,
         enable_subpixel_aa: true,
-        recorder: recorder,
+        recorder,
+        upload_method,
         blob_image_renderer: Some(Box::new(Moz2dImageRenderer::new(workers.clone()))),
         workers: Some(workers.clone()),
         thread_listener: Some(Box::new(GeckoProfilerThreadListener::new())),
```

**Comment by kvark** [comment]
## Windows/GL/Native scores

- Immediate: 135, 149, 143
- Static: 136, 143, 123
- Dynamic: 161, 143, 145
- Stream: 143, 141, 131

Interestingly, `Dynamic` works best for this case.

**Comment by kvark** [comment]
Testing on my Linux laptop shows the MM scores all over the place. I think we should proceed and then have a bit of logic in Gecko to select the proper upload style (e.g. Immedaite on Angle, Dynamic on pure GL). Any concerns left about this PR?

**Comment by glennw** [comment]
No concerns here, r=me.

**Comment by kvark** [comment]
We'll keep messing with upload/Angle performance, trying out quite a few optimization paths. No need to hold this one longer.

@bors-servo r=glennw

**Pull request merged**
