### PR TITLE
Fix bug in get_relative_transform.

### PR DESCRIPTION
**Pull request by gw3583**
Fixes the maze solver bug (bugzilla 1487984).

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/3029)

### CODE REVIEW

**Comment by gw3583** [comment]
Oops. :blush: 

r? @kvark 

Try run looks good (a few unrelated intermittent failures only):
https://treeherder.mozilla.org/#/jobs?repo=try&revision=f5dc114fe7f9a7cf9e20e67b4f58828bfeeebfe6

**Comment by gw3583** [comment]
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1487984

**Comment by kvark** [comment]
Thanks for the reftest! :)

**Pull request merged**
