### PR TITLE
Remove establishes_3d_context field from StackingContext

### PR DESCRIPTION
**Pull request by mrobinson**
This field is currently unused.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/562)

### CODE REVIEW

**Comment by mrobinson** [comment]
@glennw r?

**Comment by kvark** [comment]
is it the same as checking for the `transform` to use Z?

**Comment by mrobinson** [comment]
This used to mean a bunch of different things in Servo and, if I remember correctly, was used primarily by rust-layers. Now this is more or less hard-coded to
```
let establishes_3d_context = transform_style == transform_style::T::flat;
```

**Pull request merged**
