### PR TITLE
Fix order of border colors

### PR DESCRIPTION
**Pull request by hgallagher1993**
From #1832

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1837)

### CODE REVIEW

**Comment by mstange** [comment]
Could you add a test for this?

**Comment by hgallagher1993** [comment]
I wouldn't really know where to start tbh, this is only my second or third task on Webrender and I've never written any sort of test for it before. . .at the same time though I'd be happy to try with a couple of pointers :-)

**Comment by glennw** [comment]
What we'd generally use is a reftest in wrench (the WR testing tool). However, in this case there are already several reftests that have a border with a different color for each edge. Since these tests fail with this change, just updating the test expectations should be sufficient.

You can see the test failures here https://travis-ci.org/servo/webrender/jobs/286108271. You can also see them locally by running:

```cd wrench
./headless reftest
```

In the case of this PR, the reference images are PNGs, so you'll need to re-generate them. You can do that for an individual reference by running:

```
./headless png <path to individual reference test>
```

Once that's done, running the ```reftest``` command above should pass all tests. One additional complication is that I usually manually crop the output PNG reference images to the approximate size of the test.

**Comment by hgallagher1993** [comment]
@glennw That's perfect thanks, I'll get to it later on this evening

**Comment by glennw** [comment]
@hgallagher1993 Sorry, I missed that you had updated this! There seems to be a difference in the degenerate-curve png - perhaps the border color needs to be specified for a different side in that test?

**Comment by glennw** [comment]
@hgallagher1993 Will you have time in the next few days to fix up that last reftest image?

**Comment by hgallagher1993** [comment]
@glennw Yes, sorry about the delay I can look at it tomorrow evening

**Comment by glennw** [comment]
@hgallagher1993 No worries, thank you!

**Comment by hgallagher1993** [comment]
@glennw Hi so I have had a look at the degenerate-curve but didn't get it fixed but then something came up in the last week that I'd rather not go into here but anyway if there's no rush with this I can get back to it next week or I can enable edits by maintainers either if there is.

**Comment by glennw** [comment]
@hgallagher1993 It's not super urgent, next week is fine, thanks!

**Comment by hgallagher1993** [comment]
@glennw I've finally got back to this now and the degenerate curve looks the same as before and 1 or 2 tests failed after a rebase so they should be fixed as well, reftests pass locally anyway.

**Comment by glennw** [comment]
@hgallagher1993 Looks good, thanks! Would you mind squashing those commits into one and then we'll get this merged?

**Comment by hgallagher1993** [comment]
@glennw Squashed now

**Pull request merged**
