### PR TITLE
Bump wr_traits version, to pick the last PR.

### PR DESCRIPTION
**Pull request by emilio**
I don't know if right now we're supposed to use it, though. Isn't it included
via path by WR?

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/376)

### CODE REVIEW

**Comment by nox** [comment]
Yes we can just `./mach cargo-update` it. If you do a bump, please bump both crates though.

**Comment by nox** [comment]
Last PR was a breaking change though. Adding new variants to a public enum is a breaking change.

**Comment by glennw** [comment]
@nox @emilio  Is this PR needed / wanted?

**Comment by nox** [comment]
As long as we don't publish it, not really.

**Comment by emilio** [comment]
Nope, it's not.

**Pull request closed without merging**
