### PR TITLE
Clamp the blur radius

### LINKED ISSUE #2061: Very large box shadows cause rendering bugs
Testcase: `data:text/html,<div style="height:20px;box-shadow:0 0 2000px 2000px rgba(0,0,0,0.4)">`

Loading this page in a WebRender Firefox renders a blank tab and makes text in the tab bar disappear. I think unreasonably large box-shadow blurs should be clamped, or the shadow should be rendered without a blur. In this case, the blur achieves nothing, but I ran into a website that did this anyway.

### PR DESCRIPTION
**Pull request by nc4rrillo**
Fixes #2061 
Still needs a reftest

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2076)

### CODE REVIEW

**Comment by nc4rrillo** [comment]
I added a reftest, it fails on the OSX build bot with the following:

```
REFTEST TEST-UNEXPECTED-FAIL | reftests/boxshadow/box-shadow-large-border-radius.yaml == reftests/boxshadow/box-shadow-large-border-radius.png | image comparison, max difference: 1, number of differing pixels: 2638
```



Maybe it needs to be fuzzed?

**Comment by glennw** [comment]
Did you generate the reference image with ```./headless.py <yaml>```? That should *in theory* make the reference consistent with the CI machines, which all run tests with OSMesa software rasterizer.

**Comment by nc4rrillo** [comment]
Oh nope, I did it using wrench itself. I'll regenerate.

**Comment by mstange** [comment]
Looks good, but I think the test should be called `box-shadow-large-blur-radius.yaml` instead of `box-shadow-large-border-radius.yaml`. Would it be better to make the reference a YAML file that has a blur radius of 300, rather than a PNG?

**Comment by nc4rrillo** [comment]
I didn't know you could have YAML files on both sides of the ref tests. Cool!
Updated.

r? @mstange

**Comment by glennw** [comment]
Looks good, thank you!

@bors-servo r+

**Pull request merged**
