### PR TITLE
euclid update

### PR DESCRIPTION
**Pull request by paulrouget**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2923)

### CODE REVIEW

**Comment by Eijebong** [comment]
You also need to update the lockfile and this is blocked on https://github.com/nical/lyon/pull/394

`cargo update -p euclid`

**Comment by paulrouget** [comment]
Fixed all the duplicated dependencies.

r?

**Comment by kvark** [comment]
I wonder why/how the euclid update works given that `num-traits` is still 0.1 here. Perhaps, they used the [semver hack](https://github.com/dtolnay/semver-trick) ?..

**Comment by Eijebong** [comment]
@kvark They did. That euclid update is hopefully the last one before getting rid of `num-traits` 0.1

**Pull request merged**
