### PR TITLE
Make DebugRenderer optional to save startup time

### PR DESCRIPTION
**Pull request by fschutt**
This change makes the `DebugRenderer` optional, thereby saving the compilation time of two shaders ("debug_font" and "debug_color") and improving the startup time of webrender. If you don't need to debug webrender, there is no point in having a `DebugRenderer` and no point in compiling the shaders. 

The relevant feature is called `debug_renderer`. It is enabled by default for the features `debugger` and `profiler` (mostly because `wrench` needs them). Otherwise, this feature is not enabled by default, which also saves roughly 2.5 MB of RAM.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2574)

### CODE REVIEW

**Comment by fschutt** [comment]
Yeah, of course, the tests need to be fixed, sorry ...

**Comment by nical** [comment]
Having these debug utilities in release mode is useful, but it'd be great to initialize it lazily to avoid the startup cost.

**Comment by fschutt** [comment]
@nical As far as I can see, servo doesn't even use the `DebugRenderer` in any way. The only tool using the `DebugRenderer` is wrench, which is the debugger for webrender. So it would make more sense to make this a compile-time feature, wouldn't it?

**Comment by nical** [comment]
I use it in Firefox quite a bit, and it'd be good to not have keep Firefox startup times as fast as possible.

**Comment by nical** [comment]
Also a some of the information provided by the debug renderer, like performance counters, only makes sense in optimized builds.

**Comment by fschutt** [comment]
@nical I think I'll do both, lazy initialization and a compile-time feature. For people who don't need the `DebugRenderer` at all, it is disabled by default. I've also noticed that getting rid of the `DebugRenderer` also elleviates the need to create a `Profiler` in the `Renderer` struct (https://github.com/servo/webrender/blob/master/webrender/src/renderer.rs#L1152) - since the `DebugRenderer` is the only struct that uses the `Profiler` (as far as I can see). If I disable the `Profiler`, I can remove the whole module `debug_profiler.rs`, which saves compilation time (of course, only if you don't need the `DebugRenderer` or the `Profiler`).

So I think, moving the `DebugRenderer` and the `Profiler` to an optional feature is a good idea - for shipping Firefox, you could have the option to include the `DebugRenderer`, but people who don't need it (like me) can disable it to save compilation time, startup time and memory.

**Comment by nical** [comment]
I doubt it will make a significant difference for servo build times, but as long as the debug render is available by default in wrench and Firefox it's fine by me. You should check with @glennw about servo, I think that he uses it in this configuration regularly.

**Comment by fschutt** [comment]
Ok now I've created a feature `debug_renderer` in webrender, it's enabled by default if the `debugger` feature is enabled (which is true for wrench, but may be false for servo). So, no change for wrench. Lazy initialization is also done, although there's a slight bit of code duplication. If you want to enable the debugger in servo, you'd need to enable `debug_renderer`.

**Comment by fschutt** [comment]
I removed any code that wasn't needed (see commit message). I added the crate [`alexcrichton/cfg_if`](https://github.com/alexcrichton/cfg-if) because it has a macro to disable multiple imports in one go, making the imports a bit more readable. Not sure if this is allowed, I didn't want to write:

```rs
#[cfg(feature = "debug_renderer")]
use foo::Foo;
#[cfg(feature = "debug_renderer")]
use bar::Bar;
#[cfg(feature = "debug_renderer")]
use baz::Baz;
```

but rather 

```rs
cfg_if! {
    if #[cfg(feature = "debug_renderer")]  {
        use foo::Foo;
        use bar::Bar;
        use baz::Baz;
    }
}
```

It's a bit more readable. I'll remove it if it isn't allowed to add crates without permission.

**Comment by fschutt** [comment]
The `debug_renderer` feature is now only enabled for the `debugger` and `profiler` features.

**Comment by glennw** [comment]
We should add a config to the taskcluster file in the repo that compiles with / without this feature, so we don't regress compilation in either mode.

I think having cfg_if is fine, but it would probably be better just to exclude entire sources files if this is disabled - for example, the entire profiler.rs file is not useful (I think?) if there's no debug output enabled to render it.

**Comment by fschutt** [comment]
Hm, isn't the with / without already taken care of by compiling webrender / wrench? webrender has the feature disabled, while wrench has it enabled. So yes, you could make a seperate pass, but it would test the same things as we do now - unless webrender would be tested completely seperately from wrench, which it isn't. 

As for the profiler.rs - I did try to disable the whole module, but some functions / structs are still used in other modules. I could move that to a different module, though and refactor the profiler.rs into multiple modules.

**Comment by glennw** [comment]
Reviewed 6 of 7 files at r3.
Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---

*[webrender/src/renderer.rs, line 80 at r3](https://beta.reviewable.io/reviews/servo/webrender/2574#-L8eScQ109S_fA4rTFg4:-L8eScQ109S_fA4rTFg5:b-2hj2cp) ([raw file](https://github.com/servo/webrender/blob/93563784839b6d6334d0e29aa06ec06127142123/webrender/src/renderer.rs#L80)):*
> ```Rust
> cfg_if! {
>     if #[cfg(feature = "debug_renderer")] {
>         use api::ColorU;    
> ```

nit: trailing spaces

---

*[webrender/src/renderer.rs, line 2182 at r3](https://beta.reviewable.io/reviews/servo/webrender/2574#-L8eSoIy8Sjj0ECLCE9E:-L8eSoIy8Sjj0ECLCE9F:b-2hj2cp) ([raw file](https://github.com/servo/webrender/blob/93563784839b6d6334d0e29aa06ec06127142123/webrender/src/renderer.rs#L2182)):*
> ```Rust
>             self.gpu_profile.end_frame();
>             #[cfg(feature = "debug_renderer")]
>             {        
> ```

nit: trailing spaces

---

*[webrender/src/renderer.rs, line 2184 at r3](https://beta.reviewable.io/reviews/servo/webrender/2574#-L8eTLHyATE_s6xpbta9:-L8eTLHyATE_s6xpbtaA:b-su0fpc) ([raw file](https://github.com/servo/webrender/blob/93563784839b6d6334d0e29aa06ec06127142123/webrender/src/renderer.rs#L2184)):*
> ```Rust
>             {        
>                 let device = &mut self.device;
>                 self.debug.get_or_insert_with(|| DebugRenderer::new(device))
> ```

Instead of having an Option and doing this wherever it's accessed, how about we always create a DebugRenderer (even if it's an empty struct when feature is disabled), which internally lazily initializes when it's used?

---

*[webrender/src/renderer.rs, line 3687 at r3](https://beta.reviewable.io/reviews/servo/webrender/2574#-L8eSr6e48UR94vXeZeI:-L8eSr6e48UR94vXeZeJ:b-2hj2cp) ([raw file](https://github.com/servo/webrender/blob/93563784839b6d6334d0e29aa06ec06127142123/webrender/src/renderer.rs#L3687)):*
> ```Rust
>     #[cfg(feature = "debug_renderer")]
>     fn draw_epoch_debug(&mut self) {
>         if !self.debug_flags.contains(DebugFlags::EPOCHS) || 
> ```

nit: trailing spaces

---

*[webrender/src/renderer.rs, line 3762 at r3](https://beta.reviewable.io/reviews/servo/webrender/2574#-L8eSs2103D-mbHjS9xG:-L8eSs2103D-mbHjS9xH:b-2hj2cp) ([raw file](https://github.com/servo/webrender/blob/93563784839b6d6334d0e29aa06ec06127142123/webrender/src/renderer.rs#L3762)):*
> ```Rust
>         self.device.delete_vao(self.clip_vao);
>         self.device.delete_vao(self.blur_vao);
>         
> ```

nit: trailing spaces

---

*[webrender/src/renderer.rs, line 3764 at r3](https://beta.reviewable.io/reviews/servo/webrender/2574#-L8eSsfe2n99izHy_H51:-L8eSsfe2n99izHy_H52:b-2hj2cp) ([raw file](https://github.com/servo/webrender/blob/93563784839b6d6334d0e29aa06ec06127142123/webrender/src/renderer.rs#L3764)):*
> ```Rust
>         
>         #[cfg(feature = "debug_renderer")]
>         {         
> ```

nit: trailing spaces

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/servo/webrender/2574)*

**Comment by fschutt** [comment]
The `DebugRenderer` needs a `&mut Device` for intialization and deinitialization. So every call to `LazyInitializedDebugRenderer::get_mut()` needs to pass a `&mut self.device` along, in case the `DebugRenderer` hasn't been initialized up until this point. 

Trailing whitespace should be fixed now.

**Comment by fschutt** [comment]
Review status: 6 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[webrender/src/renderer.rs, line 80 at r3](https://beta.reviewable.io/reviews/servo/webrender/2574#-L8eScQ109S_fA4rTFg4:-L8hHdHKCzBYRI_Zx-U6:b-896fix) ([raw file](https://github.com/servo/webrender/blob/93563784839b6d6334d0e29aa06ec06127142123/webrender/src/renderer.rs#L80)):*
<details><summary><i>Previously, glennw (Glenn Watson) wrote…</i></summary><blockquote>

nit: trailing spaces
</blockquote></details>

Done.

---

*[webrender/src/renderer.rs, line 2182 at r3](https://beta.reviewable.io/reviews/servo/webrender/2574#-L8eSoIy8Sjj0ECLCE9E:-L8hHFlKEo6k6m3Y479f:b-896fix) ([raw file](https://github.com/servo/webrender/blob/93563784839b6d6334d0e29aa06ec06127142123/webrender/src/renderer.rs#L2182)):*
<details><summary><i>Previously, glennw (Glenn Watson) wrote…</i></summary><blockquote>

nit: trailing spaces
</blockquote></details>

Done.

---

*[webrender/src/renderer.rs, line 2184 at r3](https://beta.reviewable.io/reviews/servo/webrender/2574#-L8eTLHyATE_s6xpbta9:-L8h-FkWEfTsKy_ZBK_S:b-29g398) ([raw file](https://github.com/servo/webrender/blob/93563784839b6d6334d0e29aa06ec06127142123/webrender/src/renderer.rs#L2184)):*
<details><summary><i>Previously, glennw (Glenn Watson) wrote…</i></summary><blockquote>

Instead of having an Option and doing this wherever it's accessed, how about we always create a DebugRenderer (even if it's an empty struct when feature is disabled), which internally lazily initializes when it's used?
</blockquote></details>

Done. See the LazyInitializedDebugRenderer struct.

---

*[webrender/src/renderer.rs, line 3687 at r3](https://beta.reviewable.io/reviews/servo/webrender/2574#-L8eSr6e48UR94vXeZeI:-L8hHBdICDbWqcVVIghb:b-896fix) ([raw file](https://github.com/servo/webrender/blob/93563784839b6d6334d0e29aa06ec06127142123/webrender/src/renderer.rs#L3687)):*
<details><summary><i>Previously, glennw (Glenn Watson) wrote…</i></summary><blockquote>

nit: trailing spaces
</blockquote></details>

Done.

---

*[webrender/src/renderer.rs, line 3762 at r3](https://beta.reviewable.io/reviews/servo/webrender/2574#-L8eSs2103D-mbHjS9xG:-L8hGvIdE_t6cRTFsBH5:b-896fix) ([raw file](https://github.com/servo/webrender/blob/93563784839b6d6334d0e29aa06ec06127142123/webrender/src/renderer.rs#L3762)):*
<details><summary><i>Previously, glennw (Glenn Watson) wrote…</i></summary><blockquote>

nit: trailing spaces
</blockquote></details>

Done.

---

*[webrender/src/renderer.rs, line 3764 at r3](https://beta.reviewable.io/reviews/servo/webrender/2574#-L8eSsfe2n99izHy_H51:-L8hH9td4v2Qt5IoHqs3:b-896fix) ([raw file](https://github.com/servo/webrender/blob/93563784839b6d6334d0e29aa06ec06127142123/webrender/src/renderer.rs#L3764)):*
<details><summary><i>Previously, glennw (Glenn Watson) wrote…</i></summary><blockquote>

nit: trailing spaces
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/servo/webrender/2574)*

**Comment by fschutt** [comment]
@glennw fixed everything, ready to merge. I am not sure how to close discussions on Reviewable so that the the "6 discussions left" goes away. But if there are no further problems, I'd merge it before this branch inevitably gets merge conflicts. Sorry for being so pushy, but I hate stale PRs where I can't do anything to advance them.

**Comment by glennw** [comment]
Looks good, thanks!

@bors-servo r+

**Comment by staktrace** [comment]
This seems to have broken the gecko build. See https://treeherder.mozilla.org/logviewer.html#?job_id=171025276&repo=try&lineNumber=13033 for the failure log. https://bugzilla.mozilla.org/show_bug.cgi?id=1449562#c2 has the regression range.

**Comment by staktrace** [comment]
@fschutt It looks like we're building webrender with just the capture feature, see https://hg.mozilla.org/try/file/c405075b734f1ae4a50d7bfae00e34e5c7449aa0/gfx/webrender_bindings/Cargo.toml#l19 - does this feature need to include the new debug_renderer feature too?

**Comment by fschutt** [comment]
@staktrace Is this a debug or release build? If it's a debug build, just add the feature `debug_renderer` and it should build. If this is a release build, I probably have to go back and split the `debug_renderer` feature into two parts. Because in release mode, it's supposed to work with the feature disabled. Otherwise, this PR would be pretty pointless.

**Comment by staktrace** [comment]
@fschutt We do both debug and release. And both are failing. I can reproduce just by running `cargo build --no-default-features --features capture` in a standalone webrender checkout. Same happens if I add `--debug`.

**Comment by staktrace** [comment]
As far as I can tell the DebugRenderer feature is not used by Gecko, unless the capture feature internally requires it.

I've put up a patch on #2591 to fix this for now the "obvious" way, feel free to write another patch that adds the extra annotations. I thought that in general every combination of features is supposed to be valid in rust, since features are additive.

**Comment by fschutt** [comment]
@staktrace The `capture` feature doesn't seem to need access to the `DebugRenderer`. I just disabled a few too many functions on the `Device` because rustc complained they were never used. I probably shouldn't have done that. I'll add these few functions to the `capture` feature and then remove the `debug_renderer` from the `capture` feature. That should be the "proper" fix.

**Comment by kvark** [comment]
@fschutt are you intending to do this now, or want the quick fix merged first?

**Comment by fschutt** [comment]
I've already fixed it, just added `#[cfg(any(feature = "debug_renderer", feature="capture"))]` to some functions in `device.rs`. I'll do a seperate PR, do the quick fix for now.

**Comment by fschutt** [comment]
See https://github.com/servo/webrender/pull/2593

**Pull request merged**
