### PR TITLE
configurable angle for synthetic italics

### PR DESCRIPTION
**Pull request by lsalzman**
This fixes Gecko bug https://bugzilla.mozilla.org/show_bug.cgi?id=1460259

Gecko no longer uses a fixed angle for synthetic italics, so the old strategy of just trying to use fixed per-platform values that match Gecko also no longer works.

We thus need to be able to pass in a per-font angle.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2855)

### CODE REVIEW

**Comment by gw3583** [comment]
Do we need a try run for this?

**Comment by gw3583** [comment]
Looks good to me. Is it possible to add a reftest for this?

**Comment by lsalzman** [comment]
Already did a try run: https://treeherder.mozilla.org/#/jobs?repo=try&revision=587c4a551808f98a18599dd893eea415aaa0c1d2

The only thing that went wrong there is the R2 which was marked as a perma-fail, but now passes because of this change. Just needs to be fixed in the Gecko reftest.list.

**Comment by lsalzman** [comment]
Added reftests

**Comment by gw3583** [comment]
Looks like one of the ref yaml files is missing? I'll delegate anyway so feel free to r+ when that file is added, or now if I just missed it.

@bors-servo delegate+

**Pull request merged**
