### PR TITLE
Add more premultiplied gradient reftests.

### PR DESCRIPTION
**Pull request by glennw**
The existing gradient tests don't have any coverage for whether
the input color is correctly pre-multiplied.

Additionally, the angle test wasn't actually triggering the angle
gradient shader, and was running the aligned shader.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1792)

### CODE REVIEW

**Comment by glennw** [comment]
r? anyone

**Comment by mstange** [comment]
I thought as much.

**Comment by Gankro** [comment]
Huh, I could've sworn I was...

**Comment by glennw** [comment]
@mstange @Gankro I will discuss with @metajack and @larsbergstrom what we need to get you approved as reviewers!

@bors-servo r=mstange

**Pull request merged**
