### PR TITLE
Add a reftest to ensure that scroll frames can be defined and used in any order.

### PR DESCRIPTION
**Pull request by pcwalton**
r? @gw3583 

@mrobinson How's this?

### CODE REVIEW

**Comment by gw3583** [comment]
Looks fine to me - would you be able to provide it as a patch to m-c (since this is a read-only mirror of m-c now)? If your environment isn't set up for that, let me know, and we can manually move this across to m-c.

**Comment by jdm** [comment]
@gw3583 Would you mind moving this to m-c for us?

**Comment by gw3583** [comment]
https://phabricator.services.mozilla.com/D84628

**Comment by jdm** [comment]
Thanks!

**Pull request closed without merging**
