### PR TITLE
Support double, groove, ridge borders in new border brush path.

### PR DESCRIPTION
**Pull request by gw3583**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2784)

### CODE REVIEW

**Comment by gw3583** [comment]
Supersedes #2779, so closing that.

**Comment by gw3583** [comment]
This adds support for double, ridge and groove border styles to run through the new border brush path.

I also moved a few GLSL functions around. This allows us to use them in cache shaders without including ```prim_shared.glsl```. The ```prim_shared``` file declares a few unused interpolators. 

Avoiding that means we won't run into any shader compiler issues as we add the extra interpolators to this shader needed for dashing / dotting styles in the future.

r? @kvark or @mrobinson

**Comment by gw3583** [comment]
Try run looks good - there are the expected (fuzziness required) failures from the previous border PR, and a number of new PASS results in R5.

**Comment by gw3583** [comment]
With actual link to try run:

https://treeherder.mozilla.org/#/jobs?repo=try&revision=04b332b7d3f4653cb6e3f138f7e7e5131e40134b&selectedJob=180518780

**Comment by gw3583** [comment]
Added a follow up commit - this doesn't contain any functional changes, but is prep work for supporting dashing / dotting as border brushes (and it's a small optimization too).

**Comment by kvark** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[webrender/res/cs_border_segment.glsl, line 245 at r2](https://reviewable.io/reviews/servo/webrender/2784#-LDczkHx894X0DPjU3fI:-LDdp-MlD-SsUjQ3PR8G:b-8jromx) ([raw file](https://github.com/servo/webrender/blob/a82aec758c8eda2b943a7a0b7b2463e6698de299/webrender/res/cs_border_segment.glsl#L245)):*
<details><summary><i>Previously, gw3583 (Glenn Watson) wrote…</i></summary><blockquote>

It's not clear to me what this would look like - could you expand on that?
</blockquote></details>

Sure:
```glsl
float swizzled_factor;
switch (segment) {
  case SEGMENT_TOP_LEFT: swizzled_factor = 0.0; break;
  case SEGMENT_TOP_RIGHT: swizzled_factor = mix_factor;
  case SEGMENT_BOTTOM_RIGHT: swizzled_factor = 1.0; break;
  case SEGMENT_BOTTOM_LEFT: swizzled_factor = 1.0 - mix_factor; break;
  default: swizzled_factor = 0.0;
};
vec4 c0 = mix(color[1], color[0], swizzled_factor);
vec4 c1 = mix(color[0], color[1], swizzled_factor);
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/servo/webrender/2784)*

**Comment by gw3583** [comment]
Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[webrender/res/cs_border_segment.glsl, line 245 at r2](https://reviewable.io/reviews/servo/webrender/2784#-LDczkHx894X0DPjU3fI:-LDeVAbz4dvCuRVb5hjN:b-8nnxqd) ([raw file](https://github.com/servo/webrender/blob/a82aec758c8eda2b943a7a0b7b2463e6698de299/webrender/res/cs_border_segment.glsl#L245)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

Sure:
```glsl
float swizzled_factor;
switch (segment) {
  case SEGMENT_TOP_LEFT: swizzled_factor = 0.0; break;
  case SEGMENT_TOP_RIGHT: swizzled_factor = mix_factor;
  case SEGMENT_BOTTOM_RIGHT: swizzled_factor = 1.0; break;
  case SEGMENT_BOTTOM_LEFT: swizzled_factor = 1.0 - mix_factor; break;
  default: swizzled_factor = 0.0;
};
vec4 c0 = mix(color[1], color[0], swizzled_factor);
vec4 c1 = mix(color[0], color[1], swizzled_factor);
```
</blockquote></details>

Ah, I thought you meant to somehow combine it with the mix below. Updated now :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/servo/webrender/2784)*

**Comment by kvark** [comment]
thank you!
@bors-servo r+

**Comment by gw3583** [comment]
Rebased to include rawtest fixes.

@bors-servo r=kvark

**Pull request merged**
