### PR TITLE
Improve the clipping and scrolling API

### PR DESCRIPTION
**Pull request by mrobinson**
This branch includes two improvements to the clipping and scrolling API:

1. Create `DisplayListBuilder::define_scroll_frame` API which avoids having to guess when a Clip item should create a ScrollFrame and when it shouldn't. Additionally, this removes a lot of weirdness around whether a ScrollFrame's clip starts at the origin of the ScrollFrame or not. It doesn't matter any longer, because the Clip created for the ScrollFrame is entirely independent.
2. Make all clipping coordinates relative to the StackingContext. This was whirlpool of weirdness in the API that only caused confusion. We now hide this detail, making clip coordinates the same as any other coordinates.

There are a few other small cleanups included with this, such as remove the `push_clip_node` and `pop_clip_node` APIs.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1428)

### CODE REVIEW

**Comment by glennw** [comment]
@mrobinson Do you have Servo branch with API updates for this and the previous PR? Would be good to be able to do some testing with Servo and land a WR update once this is reviewed and merged.

**Comment by mrobinson** [comment]
I've pushed a new commit to this branch and the Servo part of this PR is available here: https://github.com/mrobinson/servo/tree/webrender-update.

**Comment by staktrace** [comment]
@glennw or @kvark , can we get this one reviewed and landed? It is needed in order to do a WR update in gecko. (Well, we either need this or #1459, but this is the correct solution and #1459 is just a temp workaround).

**Comment by mrobinson** [comment]
I just noticed the reftest failure here. I'm looking at this now.

**Comment by mrobinson** [comment]
Okay. The latest version of the PR fixes the typo in the ref test, but one of the jobs seemed to fail due to an error on the bot. I'll rerun that particular configuration.

**Comment by glennw** [comment]
Reviewed 16 of 27 files at r1, 15 of 15 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/1428)*

**Comment by glennw** [comment]
Let's get this merged, and try to get both Servo and Gecko updated to the API changes this week :)

@bors-servo r+

**Comment by glennw** [comment]
@bors-servo retry
 * Looks like a nightly-specific compile error in a dependency? Let's just confirm it's consistent...

**Comment by glennw** [comment]
This appears to be broken on nightly due to this change https://github.com/rust-lang/rust/issues/34537 which is causing a compile error in core-text.

A change has been made in core-text to fix this https://github.com/servo/core-text-rs/commit/6847e69397f0635746d709f8f23a561191e32cfa but it hasn't been version bumped / published yet.

If it requires a major version bump in core-text, that could take quite a while to get all deps updated. Perhaps we could disable building WR on nightly temporarily, since we really need to get this PR (and a few others) landed soon.

Thoughts @nox @jdm @kvark ?

**Comment by glennw** [comment]
https://github.com/servo/webrender/pull/1462 has landed now, which should fix the CI error here.

@bors-servo retry

**Pull request merged**
