### PR TITLE
Fix brush_blend on SandyBridge iGPU

### LINKED ISSUE #2088: ps_blend.glsl could be using a mat3 instead of a mat4
All the matrices generated in [ps_blend.glsl](https://github.com/servo/webrender/blob/master/webrender/res/ps_blend.glsl) only make use of the top left 3x3 square of the matrix. I think this matrix could use the `mat3` type instead, and the fragment shader could be doing `oFragColor = vec4(vColorMat * Cs.rgb, Cs.a)`, which should be a bit cheaper.

### PR DESCRIPTION
**Pull request by kvark**
Dividing by zero is not a good idea in GLSL.
Also fixes #2088 since we are at it.
r? @jrmuizel

Edit: wiki entry - https://github.com/servo/webrender/wiki/Driver-issues#division-by-zero-on-sandybridge-in-the-fragment-shader

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2530)

### CODE REVIEW

**Comment by kvark** [comment]
hold on, I missed one thing
@bors-servo r-

**Comment by kvark** [comment]
(was missing the filter functions changed from `vec4` to `vec3`)
@bors-servo r=jrmuizel

**Comment by kvark** [comment]
Upon checking with @mstange , it appears that having the color matrix affecting alpha is only needed for SVG color filters, and we don't quite support it in WR anyway, and we'll need way more logic to support SVG filters (not covered by brush_blend). Thus, we figured the test case that modifies the alpha via color matrix needs to be removed.
@bors-servo r=jrmuizel,mstange

**Comment by jrmuizel** [comment]
This still needs the test case removed.

**Comment by kvark** [comment]
Should be good now.
@bors-servo r=jrmuizel,mstange

**Pull request merged**
