### PR TITLE
Add appveyor config for Windows CI support.

### PR DESCRIPTION
**Pull request by frewsxcv**
Fixes https://github.com/servo/webrender/issues/246.

### CODE REVIEW

**Comment by frewsxcv** [comment]
r? @pcwalton @glennw 

cc @larsbergstrom

**Comment by larsbergstrom** [comment]
this lgtm

**Comment by jdm** [comment]
```
src/render_backend.rs:211:79: 211:89 error: mismatched types:

 expected `offscreen_gl_context::gl_context_attributes::GLContextAttributes`,

    found `offscreen_gl_context::gl_context_attributes::GLContextAttributes`

(expected struct `offscreen_gl_context::gl_context_attributes::GLContextAttributes`,

    found a different struct `offscreen_gl_context::gl_context_attributes::GLContextAttributes`) [E0308]

src/render_backend.rs:211                                 match GLContext::<NativeGLContext>::new(size, attributes, ColorAttachmentType::Texture, Some(handle)) {

                                                                                                        ^~~~~~~~~~

src/render_backend.rs:211:79: 211:89 help: run `rustc --explain E0308` to see a detailed explanation

src/render_backend.rs:211:79: 211:89 note: Perhaps two different versions of crate `offscreen_gl_context` are being used?

src/render_backend.rs:211                                 match GLContext::<NativeGLContext>::new(size, attributes, ColorAttachmentType::Texture, Some(handle)) {

                                                                                                        ^~~~~~~~~~

src/render_backend.rs:240:43: 240:46 error: mismatched types:

 expected `&offscreen_gl_context::gl_context::GLContext<_>`,

    found `&offscreen_gl_context::gl_context::GLContext<offscreen_gl_context::platform::with_glx::native_gl_context::NativeGLContext>`

(expected struct `offscreen_gl_context::gl_context::GLContext`,

    found a different struct `offscreen_gl_context::gl_context::GLContext`) [E0308]

src/render_backend.rs:240                             command.apply(ctx);

                                                                    ^~~

src/render_backend.rs:240:43: 240:46 help: run `rustc --explain E0308` to see a detailed explanation

src/render_backend.rs:240:43: 240:46 note: Perhaps two different versions of crate `offscreen_gl_context` are being used?

src/render_backend.rs:240                             command.apply(ctx);

                                                                    ^~~

src/render_backend.rs:211:79: 211:89 error: mismatched types:

 expected `offscreen_gl_context::gl_context_attributes::GLContextAttributes`,

    found `offscreen_gl_context::gl_context_attributes::GLContextAttributes`

(expected struct `offscreen_gl_context::gl_context_attributes::GLContextAttributes`,

    found a different struct `offscreen_gl_context::gl_context_attributes::GLContextAttributes`) [E0308]

src/render_backend.rs:211                                 match GLContext::<NativeGLContext>::new(size, attributes, ColorAttachmentType::Texture, Some(handle)) {

                                                                                                        ^~~~~~~~~~

src/render_backend.rs:211:79: 211:89 help: run `rustc --explain E0308` to see a detailed explanation

src/render_backend.rs:211:79: 211:89 note: Perhaps two different versions of crate `offscreen_gl_context` are being used?

src/render_backend.rs:211                                 match GLContext::<NativeGLContext>::new(size, attributes, ColorAttachmentType::Texture, Some(handle)) {

                                                                                                        ^~~~~~~~~~

src/render_backend.rs:240:43: 240:46 error: mismatched types:

 expected `&offscreen_gl_context::gl_context::GLContext<_>`,

    found `&offscreen_gl_context::gl_context::GLContext<offscreen_gl_context::platform::with_glx::native_gl_context::NativeGLContext>`

(expected struct `offscreen_gl_context::gl_context::GLContext`,

    found a different struct `offscreen_gl_context::gl_context::GLContext`) [E0308]

src/render_backend.rs:240                             command.apply(ctx);

                                                                    ^~~

src/render_backend.rs:240:43: 240:46 help: run `rustc --explain E0308` to see a detailed explanation

src/render_backend.rs:240:43: 240:46 note: Perhaps two different versions of crate `offscreen_gl_context` are being used?

src/render_backend.rs:240                             command.apply(ctx);

                                                                    ^~~

error: aborting due to 2 previous errors

Build failed, waiting for other jobs to finish...

error: aborting due to 2 previous errors

error: Could not compile `webrender`.
```

**Comment by frewsxcv** [comment]
Should I cherry pick #249?

**Comment by frewsxcv** [comment]
Cherry-picked.

**Comment by frewsxcv** [comment]
Looks like there's still an issue (fewer issues though). I don't have time to look into it right now. People can push to this branch if they want to try fixing it though.

**Comment by emilio** [comment]
@bors-servo r=gw,larsbergstrom

> gw> emiliocobos: your wr/traits PRs all look fine to me, but there appear to be some CI / dependency issues preventing stuff landing there at the moment. Will look into that today or when back from PTO if no-one else does
> emiliocobos> gw: If they look fine, frewsxcv should have just cherrypicked the last dependency problem (#249 and #250 should have passed but we had the appveyor hook configured but not running)
> gw> emiliocobos: ok, cool

**Pull request merged**
