### PR TITLE
Add memory reporters and eviction for cached textures

### PR DESCRIPTION
**Pull request by bholley**
Reviewed by Glenn in https://bugzilla.mozilla.org/show_bug.cgi?id=1493196

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/3124)

### CODE REVIEW

**Comment by bholley** [comment]
@bors-servo r=gw3583

tidy

**Comment by bholley** [comment]
On that note, how do I run tidy locally?

**Comment by gw3583** [comment]
You should be able to do something like:

```
virtualenv venv
./venv/bin/activate.sh
pip install servo-tidy PyYAML voluptuous
servo-tidy
```

Probably missing something but that should roughly work - run it from the root WR dir.

**Pull request merged**
