### PR TITLE
Store tile dirty rects in tile space.

### PR DESCRIPTION
**Pull request by nical**
Before this PR each tile stores its own dirty rect relative to the entire image. This is somewhat confusing because this field is used to track partial uploads correctly and uploads reason about dirty rects relative to the tiles so it has to do some conversions. Storing relative to the tile is also truer to the "device space" the rects are tagged with.
Last but not least the image-relative coordinates will make even less sense for tiled blob images as we start treating them as virtually infinite planes.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/3272)

### CODE REVIEW

**Comment by nical** [comment]
try looks good, r? anyone

**Comment by Gankro** [comment]
r=me with docs updated

**Comment by Gankro** [comment]
Ah, I see you delete the commented code in #3277 so should be fine..?

**Comment by staktrace** [comment]
@nical This PR is not happy-making in Gecko: https://treeherder.mozilla.org/#/jobs?repo=try&group_state=expanded&revision=f39162e828cb0a91e51504ef813201573bebd918

**Pull request merged**
