### PR TITLE
Reorder the callback setup in rawtests 

### LINKED ISSUE #2787: Intermittent rawtest failure in test_retained_blob_images_test
See https://github.com/servo/webrender/pull/2786#issuecomment-392633249 and https://github.com/servo/webrender/pull/2786/commits/2078b0739da28a056cc57cf4c65236a0016fd9ae

### PR DESCRIPTION
**Pull request by kvark**
Fixes #2787
Includes #2775

r? anyone

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2788)

### CODE REVIEW

**Comment by kvark** [comment]
Should be good now.
@bors-servo try

**Comment by staktrace** [comment]
r=me, patch makes sense

**Comment by kvark** [comment]
Looks green, let's unblock all the things
@bors-servo r=staktrace

**Pull request merged**
