### PR TITLE
Extra care of the upper bound for image tiling shader

### LINKED ISSUE #1797: Thin line visible around a transformed primitive
See #1732 for the test case image/code.
The used image is attached here:
1505936895-img-59

I can repro it on Linux/Intel.

### PR DESCRIPTION
**Pull request by kvark**
Fixes  #1797
r? @glennw

Gecko try: https://treeherder.mozilla.org/#/jobs?repo=try&revision=8a192063236587f0d93b5b85b0bf1c16108c3a6d

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1798)

### CODE REVIEW

**Comment by glennw** [comment]
Shader validation is failing on CI. Is it possible to add a reftest for this? It would be good to have test coverage for an edge case like this.

**Comment by kvark** [comment]
@glennw should be better now

**Comment by kvark** [comment]
Weird, I generated the image from `headless.py`, then cropped it, and it doesn't match O_o

**Comment by glennw** [comment]
@kvark I hate to be pedantic on this stuff - but we probably shouldn't include that image in the repo unless we know the licensing on it. Would it be possible to replace with a simple image we create that tests the issue in question?

**Comment by kvark** [comment]
@glennw sure, that would be most optimal, just going to take a bit more effort.

**Comment by kvark** [comment]
Replaced the image with a hand-generated one.
Reftest produces 1 pixel difference of value 1 when running all the reftests (with osmesa) for some reason, but not when running transform tests only.

**Comment by glennw** [comment]
Thanks!

@bors-servo r+

**Pull request merged**
