### PR TITLE
Sync changes from mozilla-central gfx/wr

### PR DESCRIPTION
**Pull request by moz-gfx**

### CODE REVIEW

**Comment by staktrace** [comment]
Lolwut github?!

On current servo/webrender master branch this commit is already merged using merge commit a237fefc "Auto merge of #4357"... and yet this PR remains open.

**Comment by staktrace** [comment]
@jrmuizel or @kvark do you have permissions to close this PR? If it sits around open it'll cause the sync job to keep stuffing commits into this, and it's never gonna get merged, because it actually already got merged.

**Comment by NateLing** [comment]
@staktrace Not in reviewers

**Comment by staktrace** [comment]
@bors-servo r=close

Didn't know this was a thing, thanks!

**Pull request closed without merging**
