### PR TITLE
Move binary recordings to a single file instead of a directory

### PR DESCRIPTION
**Pull request by vvuk**
No reason to use separate files.  In the future, we could even gzip as we stream out (on a different thread maybe). This also cleans up the recording code to just have a single unified path instead of separate detour stuff.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/765)

### CODE REVIEW

**Comment by kvark** [comment]
I read through it, looks great!
Just need to fix the CI errors.

**Comment by glennw** [comment]
Looks like there is still a compile error on CI?

**Comment by vvuk** [comment]
Yes - working on it, I think I pushed the wrong branch. Checking on laptop
shortly

**Comment by glennw** [comment]
@kvark OK, The CI errors are resolved, if you have time to re-look at this.

**Comment by kvark** [comment]
Thanks @vvuk, the code is great, and the changes are much welcome!
Please r=me after rebasing.

**Pull request merged**
