### PR TITLE
Fixed edge mask decoding in the shader

### PR DESCRIPTION
**Pull request by kvark**
Related to #1797

Apparently, the old GLSL code that I had was all-or-nothing. For some reason, it didn't show the issue before, but it started showing it when the new brush splitting has arrived.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2254)

### CODE REVIEW

**Comment by kvark** [comment]
There was already a reftest for this (rotated-clip) but it was so small in size that it went under the segment split threshold and rendered in one go, hence it didn't reveal the problem. This PR includes an updated reftest.

**Comment by glennw** [comment]
Oh, CI is failing on TC too - might be a slight discrepancy in the reftest output.

**Comment by Gankro** [comment]
Could this also be the cause/fix for https://github.com/servo/webrender/issues/2252 ?

**Comment by kvark** [comment]
@glennw agreed, was also thinking about tests with different sizes.
@Gankro the fix affects AA on edges of brush primitives, mostly segments. Not sure if it's related to #2252

**Comment by kvark** [comment]
Try looks green: https://treeherder.mozilla.org/#/jobs?repo=try&revision=68770f9175f0c8e963521ab0a775544564898f5c , if you don't mind 4 unexpected passes.

The new changes from `border.rs` are not new function but rather replicating the exact behavior of the old code for borders. Certainly something to put on the radar for future work on borders.

@bors-servo r=glennw

**Comment by kvark** [comment]
old good OSX timeout...
@bors-servo retry

**Comment by kvark** [comment]
ugh, all sorts of Travis failures... to check out the source, to wait for the completion, etc.

**Pull request merged**
