### PR TITLE
Add some basic testing for the binary record/replay infrastructure

### PR DESCRIPTION
**Pull request by jrmuizel**
This also ends up testing the png command.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1605)

### CODE REVIEW

**Comment by glennw** [comment]
This is failing on CI, that new command is not exiting cleanly.

**Comment by glennw** [comment]
Oh, I'm guessing the failure was the png command deinit fix, which has landed now...

@bors-servo r+

**Comment by kvark** [comment]
Looks like travis fails to parse our script now?
> $ if [ $BUILD_KIND = DEBUG ]; then (cd wrench && cargo run -- --save binary png reftests/text/decorations.yaml && cargo run -- replay --play wr-record.bin)

>/home/travis/.travis/job_stages: eval: line 58: syntax error: unexpected end of file

**Comment by glennw** [comment]
@jrmuizel I think this is just missing the ```fi``` at the end of the line?

**Comment by glennw** [comment]
Failed on the Linux + Debug build config:

```
Running `/home/travis/build/servo/webrender/target/debug/wrench --save binary png reftests/text/decorations.yaml`

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoBackendAvailable(XOpenDisplayFailed)', /checkout/src/libcore/result.rs:859

```

It worked on mac and Linux release though...

**Comment by glennw** [comment]
@jrmuizel The OSMesa backend is only available in release builds, I think.

We could change this to use the ```headless``` command and run on a release config. That would allow the ```png``` command to work. I'm not sure what would happen with the replay command if run under headless though?

Alternatively, we could just run this line on the mac build config, since that has a GL backend available?

**Comment by glennw** [comment]
Closing for now - please re-open when ready for re-review.

**Pull request closed without merging**
