### PR TITLE
Premultiply gradient stop colors

### PR DESCRIPTION
**Pull request by rlhunt**
CSS gradient stop colors are interpolated in premultiplied space.
Currently we assume that color stops that are passed in are
premultiplied, but because it's needed in both Servo and Gecko, it makes
sense to do the premultiplication in WebRender and expose a straight
alpha color like the rest of the API does.

The premultiplication is purposefully not done in DisplayListBuilder
to prevent it from being saved for replay and then premultiplied again
when we replay the display list.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1250)

### CODE REVIEW

**Comment by rlhunt** [comment]
r? @glennw @kvark 
cc @pyfisch

This is for #1219 

Note: this was done on the Gecko side before, but Servo needs it too, so I think it makes sense to make the API less confusing and move the work here.

**Comment by kvark** [comment]
Since we are using premultiplied alpha for gradients, shouldn't we also change the blending mode used for rendering of them?

**Comment by rlhunt** [comment]
Sorry, forgot to respond. The gradients should be using a premultiplied alpha blend mode, as before. The change here is to make the API expect unpremultiplied alpha, instead of expecting the client to premultiply the stops.

**Comment by rlhunt** [comment]
@kvark Thanks!

**Pull request merged**
