### PR TITLE
Split update_clip_task into several methods

### PR DESCRIPTION
**Pull request by mrobinson**
This will make it easier to add more complicated logic here without
making this method too long. This shouldn't change any behavior, as
it's just moving code around.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2173)

### CODE REVIEW

**Comment by mrobinson** [comment]
Gecko try here: https://treeherder.mozilla.org/#/jobs?repo=try&revision=b6a2a72c4c82a582f16b6ee9a48aef49133356a0

**Comment by glennw** [comment]
Merging manually since travis / bors seem broken. Pre-merge test passed travis.

**Pull request merged**
