### PR TITLE
Fix undefined behaviour in prim_shared.

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/989)

### CODE REVIEW

**Comment by kvark** [comment]
I think we should also clamp `d` to be in 0-1 range

**Comment by glennw** [comment]
I'm not sure I follow why we'd want to clamp ```d``` - could you explain?

**Comment by kvark** [comment]
Nvm, shipit ;)
@bors-servo r+

**Pull request merged**
