### PR TITLE
Add documentation for the current clipping API

### PR DESCRIPTION
**Pull request by mrobinson**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1095)

### CODE REVIEW

**Comment by mrobinson** [comment]
@kvark or @glennw r?

**Comment by glennw** [comment]
Awesome!

@bors-servo r+

**Comment by kvark** [comment]
I much welcome this document (thank you!), but I don't think `src` is the right place for it.

**Comment by glennw** [comment]
Yes - I didn't notice the path - can we move it to doc/ ?

**Comment by mrobinson** [comment]
Sure. PR is here: https://github.com/servo/webrender/pull/1099

**Pull request merged**
