### PR TITLE
Decompose tiled images during frame building (v3)

### PR DESCRIPTION
**Pull request by nical**
This PR implements decomposing tiled images during frame building using visibility information to avoid issues with very large blob images.
This version does not use segments, avoiding issues with the maximum contiguous gpu cache alloc size as well as a few hacks that I had to write to get repetitions to work with segments.

As a bonus the non-brush image primitive and ps_image shader are now obsolete so I removed them.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2704)

### CODE REVIEW

**Comment by nical** [comment]
Sorry about closing/recreating the PR, turns out `git push -f` and `git push -d` are very close on a qwerty keyboard.
I rebased the PR with #2644 now in master, although we still need #2664 to land before merging this.

**Comment by glennw** [comment]
There's a heap of CI tests failing too - maybe something went wrong during rebasing?

Probably around half of the reftests fail, until it crashes at:

```
REFTEST TEST-END | reftests/gradient/repeat-border-radius.yaml == reftests/gradient/repeat-border-radius.png
REFTEST reftests/image/tile-size.yaml == reftests/image/tile-size-ref.yaml
thread 'WRRenderBackend#0' panicked at 'handle not requested or allocated!', libcore/option.rs:917:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::option::expect_failed
             at libcore/option.rs:917
  10: <unknown>
             at /checkout/src/libcore/option.rs:302
             at webrender/src/gpu_cache.rs:647
             at webrender/src/batch.rs:624
Traceback (most recent call last):
  File "script/headless.py", line 75, in <module>
    subprocess.check_call(['../target/release/wrench', '--no-scissor', '-h'] + sys.argv[1:])
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../target/release/wrench', '--no-scissor', '-h', 'reftest']' returned non-zero exit status -6
[taskcluster 2018-04-27 17:07:05.232Z] === Task Finished ===
```

https://tools.taskcluster.net/groups/CfiHc6UoR4eB0t4h5N45aw/tasks/CfiHc6UoR4eB0t4h5N45aw/runs/0/logs/public%2Flogs%2Flive.log

**Comment by glennw** [comment]
Getting close!

```
REFTEST INFO | 276 passing, 2 failing
Reftests with unexpected results:
	reftests/filters/blend-clipped.yaml == reftests/filters/blend-clipped.png
	reftests/image/tile-with-spacing.yaml == reftests/image/tile-with-spacing-ref.yaml
Traceback (most recent call last):
```

**Comment by nical** [comment]
Try push https://treeherder.mozilla.org/#/jobs?repo=try&revision=c7afdfa3b826df94ff523bbbf9c2850fb8590b22

**Comment by nical** [comment]
Another try run with the fixes from #2664: https://treeherder.mozilla.org/#/jobs?repo=try&revision=f726753e0a776525670067356227edb9a7112389

**Comment by nical** [comment]
The remaining 3 failing reftests all go through the the tile decomposition code path with a large scroll offset applied. All of them render nothing on screen (they do produce tiles but I suspect these tiles are off-screen). The tests pass if I remove the scroll offset in the tests and the references which seems to imply I got this piece wrong somehow:

In prim_store.rs:
```rust
fn compute_conservative_visible_rect(
    prim_run_context: &PrimitiveRunContext,
    frame_context: &FrameBuildingContext,
    local_clip_rect: &LayoutRect,
) -> LayoutRect {
    let world_screen_rect = prim_run_context
        .clip_chain.combined_outer_screen_rect
        .to_f32() / frame_context.device_pixel_scale;

    if let Some(layer_screen_rect) = prim_run_context
        .scroll_node
        .world_content_transform
        .unapply(&world_screen_rect) {

        return local_clip_rect.intersection(&layer_screen_rect).unwrap_or(LayoutRect::zero());
    }

    *local_clip_rect
}
```

If anyone understands webrender's coordinate systems somewhat and has a vague idea of what I missed, please let me know.

**Comment by jrmuizel** [comment]
It looks like it was actually for_each_tile() that was wrong.

**Comment by jrmuizel** [comment]
This fixes it:
```diff
diff --git a/gfx/webrender/src/image.rs b/gfx/webrender/src/image.rs
index 181cb566fd1e..d1f3811b3631 100644
--- a/gfx/webrender/src/image.rs
+++ b/gfx/webrender/src/image.rs
@@ -195,22 +195,22 @@ pub fn for_each_tile(
         if y == y_count - 1 {
             row_flags |= EdgeAaSegmentMask::BOTTOM;
         }
 
         for x in 0..x_count {
             let tile_offset = t0 + vec2(x, y);
 
 
             let mut segment_rect = LayoutRect {
                 origin: LayoutPoint::new(
-                    x0 + tile_offset.x as f32 * layer_tile_size.width,
-                    y0 + tile_offset.y as f32 * layer_tile_size.height,
+                    prim_rect.origin.x + tile_offset.x as f32 * layer_tile_size.width,
+                    prim_rect.origin.y + tile_offset.y as f32 * layer_tile_size.height,
                 ),
                 size: layer_tile_size,
             };
 
             if tile_offset.x == leftover_offset.x {
                 segment_rect.size.width = leftover_layer_size.width;
             }
 
             if tile_offset.y == leftover_offset.y {
                 segment_rect.size.height = leftover_layer_size.height;
```

**Comment by kvark** [comment]
Also, the `compute_conservative_visible_rect` function shouldn't be introduced - instead we should re-use the `clip_chain_rect` already computed in `prepare_prim_runs`.

**Comment by jrmuizel** [comment]
Here's a version of this that's been rebased and should pass the tests:
https://github.com/jrmuizel/webrender/tree/tile-decomposition

**Comment by jrmuizel** [comment]
I'm going to move to a different pull request for now.

**Comment by gw3583** [comment]
Closing since tiled images v4 PR landed.

**Pull request closed without merging**
