### PR TITLE
macOS support for font loading

### PR DESCRIPTION
**Pull request by jrmuizel**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/830)

### CODE REVIEW

**Comment by glennw** [comment]
Looks like there is a compile error on Linux CI. I guess that extern crate should be mac only?

**Comment by MSleepyPanda** [comment]
Yup, looking into this

**Comment by MSleepyPanda** [comment]
@jrmuizel Can you please confirm that version "0.1.3" is working on macos? Does on my Ubuntu VM.

**Comment by jrmuizel** [comment]
@MSleepyPanda It works on macOS

**Comment by MSleepyPanda** [comment]
*sigh* please update to 0.1.4
Seriously need to setup ci for font-loader.

**Pull request merged**
