### PR TITLE
Improve wrench reftest harness output

### PR DESCRIPTION
**Pull request by rlhunt**
This PR makes the reftest ouput more verbose and compatible with the [reftest analyzer](https://hg.mozilla.org/mozilla-central/raw-file/tip/layout/tools/reftest/reftest-analyzer.xhtml) in mozilla-central. (for #810)

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/813)

### CODE REVIEW

**Comment by glennw** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[wrench/src/reftest.rs, line 32 at r1](https://reviewable.io:443/reviews/servo/webrender/813#-Kbme8iBE95dmhJcHE3l:-Kbme8iBE95dmhJcHE3m:brifvem) ([raw file](https://github.com/servo/webrender/blob/39285ac617d76b8be25b62b5b1ad9f9330ec2bce/wrench/src/reftest.rs#L32)):*
> ```Rust
> struct ReftestImage {
>     data: Vec<u8>,
>     size: (u32, u32),
> ```

Can we make this a DeviceUintSize instead of a tuple?

---

*[wrench/src/reftest.rs, line 36 at r1](https://reviewable.io:443/reviews/servo/webrender/813#-KbmeEma7lh0G2eRYwnU:-KbmeEma7lh0G2eRYwnV:b-ynv804) ([raw file](https://github.com/servo/webrender/blob/39285ac617d76b8be25b62b5b1ad9f9330ec2bce/wrench/src/reftest.rs#L36)):*
> ```Rust
> enum ReftestImageComparison {
>     Equal,
>     NotEqual(usize, usize),
> ```

These should be named fields.

---

*[wrench/src/reftest.rs, line 48 at r1](https://reviewable.io:443/reviews/servo/webrender/813#-KbmexhY5GjvLeKCM2N6:-KbmexhY5GjvLeKCM2N7:bpz7x9t) ([raw file](https://github.com/servo/webrender/blob/39285ac617d76b8be25b62b5b1ad9f9330ec2bce/wrench/src/reftest.rs#L48)):*
> ```Rust
>         let mut count = 0;
> 
>         for i in 0..pixels {
> ```

This could be written a little tidier as something like: for (p0, p1) in self.data.chunks(4).zip(other.data..chunks(4))

---

*[wrench/src/reftest.rs, line 67 at r1](https://reviewable.io:443/reviews/servo/webrender/813#-Kbmh8M3wPykkN0nIoY-:-Kbmh8M3wPykkN0nIoY0:b-6yrdss) ([raw file](https://github.com/servo/webrender/blob/39285ac617d76b8be25b62b5b1ad9f9330ec2bce/wrench/src/reftest.rs#L67)):*
> ```Rust
>                 let a = self.data[i] as isize;
>                 let b = other.data[i] as isize;
>                 max = cmp::max(max, (a - b).abs());
> ```

The max could perhaps be accumulated during the loop above.

---

*[wrench/src/reftest.rs, line 203 at r1](https://reviewable.io:443/reviews/servo/webrender/813#-KbmdyPvLMlZnDSLILe6:-KbmdyPwIOWMZNnQ7PkX:bouv07z) ([raw file](https://github.com/servo/webrender/blob/39285ac617d76b8be25b62b5b1ad9f9330ec2bce/wrench/src/reftest.rs#L203)):*
> ```Rust
>         let comparison = test.compare(&reference);
> 
>         let success = match t.op {
> ```

This might be cleaner to write as match (t.op, comparison) but it's not a big deal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/813)*

**Comment by glennw** [comment]
This is fantastic! Just a few minor comments above, it will be great to get this merged.

**Comment by rlhunt** [comment]
Review status: 3 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[wrench/src/reftest.rs, line 203 at r1](https://reviewable.io:443/reviews/servo/webrender/813#-KbmdyPvLMlZnDSLILe6:-Kbmx3DrnVh0UCmrIimb:b-ph7m34) ([raw file](https://github.com/servo/webrender/blob/39285ac617d76b8be25b62b5b1ad9f9330ec2bce/wrench/src/reftest.rs#L203)):*
<details><summary><i>Previously, glennw (Glenn Watson) wrote…</i></summary><blockquote>

This might be cleaner to write as match (t.op, comparison) but it's not a big deal.
</blockquote></details>

That made it much more cleaner! I like it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/813)*

**Comment by glennw** [comment]
@bors-servo r+

Thanks!

**Pull request merged**
