### PR TITLE
Convert NativeFontHandle to a wrapper and implement serde traits for it

### PR DESCRIPTION
**Pull request by jbg**
See https://github.com/servo/servo/issues/15607

Other related pull requests:
 * https://github.com/servo/servo/pull/15615
 * https://github.com/servo/core-graphics-rs/pull/75

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/896)

### CODE REVIEW

**Comment by nox** [comment]
Why do we need to create the font at all from the `Deserialize` trait? Can't we explicitly just receives and sends font names instead of font handles?

**Comment by glennw** [comment]
cc @jdm

**Comment by nox** [comment]
Actually, this is ok.

@jbg Could you rebase on master?

**Comment by glennw** [comment]
Closing for now due to conflicts and lack of activity. Feel free to re-open when updated.

**Pull request closed without merging**
