### PR TITLE
Better inversible transformations

### LINKED ISSUE #2911: Panic trying to unwrap a rect that could not be transformed
Filed as a followup of #2904.

The panic is because this https://github.com/servo/webrender/pull/2904/files#diff-9c1d8b23da9e37ae3377086804c5aaf2L588 used to always have Some(transformed rect) and now can have None since transforming a rect is fallible in the latest euclid, since servo/euclid#291.

cc @kvark

I suppose that in this case we could cull out entirely the rects that we can't project.

This was caught by Firefox's CI, see https://bugzilla.mozilla.org/show_bug.cgi?id=1476636#c1
Here's a sample log: https://treeherder.mozilla.org/logviewer.html#?job_id=188772693&repo=try&lineNumber=1438

### PR DESCRIPTION
**Pull request by kvark**
Hopefully addresses #2911 (how can I verify?)
r? @nical

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2913)

### CODE REVIEW

**Comment by staktrace** [comment]
I started a try push that includes #2912 and this PR: https://treeherder.mozilla.org/#/jobs?repo=try&revision=3623dff5d67e5c5a5c77fb5f7a6ed55f7f69cd06

**Comment by staktrace** [comment]
This patch appears to be insufficient, we're still getting panics (see try push above). It's hitting the `all the points are supposed to be transformable after near plane clipping` panic path.

**Comment by kvark** [comment]
@staktrace this makes sense. I'm still working (closest WR bug is  #2272) on that part of code (just switching on and off, mostly off, occasionally), and I know it's not yet entirely correct, so unwrapping does no good there (until it's fixed). How about a temporary workaround in https://github.com/servo/webrender/pull/2913/commits/14ebffbdd747bd4c941ba918ff2578bd7656de69 ?

**Comment by staktrace** [comment]
Started a new try push with that: https://treeherder.mozilla.org/#/jobs?repo=try&revision=78d838b9b1f8b0d9e014fe5f2ee05f53135aa2e9

**Comment by staktrace** [comment]
Above try push still had failures, this time from [this line](https://github.com/servo/webrender/blob/2cb682553816200bb74ce75d3851753bc122f488/webrender/src/picture.rs#L596) per my local repro on `layout/reftests/transform-3d/1035611-1.html`

**Comment by kvark** [comment]
@staktrace thanks for tracing this crash down! I updated the second commit here to somewhat work around it.

Note: the workaround is super unsound and in normal circumstances shouldn't be merged. However, the old code was essentially producing undefined values (behind the near plane) by that transformation, so defaulting to concrete ones, while still wrong, is a step forward.

**Comment by staktrace** [comment]
I did a local build with that patch (try still going [here](https://treeherder.mozilla.org/#/jobs?repo=try&revision=56f626ea3ad47e941583efde483de2c45649085a)) and it crashes still. Same test as last time, but a different spot:
```
#10 0x00007fffe95c50bc in _$LT$core..option..Option$LT$T$GT$$GT$::unwrap::h85c542007de8ef77 (self=...) at /checkout/src/libcore/macros.rs:20
#11 0x00007fffe95cab79 in webrender::batch::make_polygon::h377795bdcde61f94 (rect=..., transform=<optimized out>, anchor=<optimized out>) at gfx/webrender/src/batch.rs:1717
#12 0x00007fffe95c8c34 in webrender::batch::AlphaBatchBuilder::add_prim_to_batch::h74e57828c73cc409 (self=0x7fffc15fa300, transform_id=..., prim_index=..., ctx=<optimized out>, gpu_cache=0x7fffc15fc9b0, render_tasks=0x7fffc15fa660, task_id=..., task_address=..., deferred_resolves=0x7fffc15fa648, splitter=0x7fffc15f8170, content_origin=..., prim_headers=0x7fffc15fa748)
    at gfx/webrender/src/batch.rs:676
#13 0x00007fffe95c88cb in webrender::batch::AlphaBatchBuilder::add_run_to_batch::hfc4831300e0e33d3 (self=0x7fffc15fa300, run=<optimized out>, transform_id=..., ctx=0x7fffc15fa5d0, gpu_cache=<optimized out>, render_tasks=<optimized out>, task_id=..., task_address=..., deferred_resolves=<optimized out>, splitter=<optimized out>, content_origin=..., prim_headers=<optimized out>)
    at gfx/webrender/src/batch.rs:559
```

https://github.com/servo/webrender/blob/2cb682553816200bb74ce75d3851753bc122f488/webrender/src/batch.rs#L1717

**Comment by jrmuizel** [comment]
try push:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=716c8d9cf7f08cf51eacc169aff2165e89e5f005

**Comment by kvark** [comment]
@jrmuizel the errors in this try push appear from #2891:
> thread '<unnamed>' panicked at 'Unable to open shader file: "/builds/worker/workspace/build/src/obj-firefox/toolkit/library/x86_64-unknown-linux-gnu/release/build/webrender-fec329b250b1de8f/out/brush_solid.vert": Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
11:13:21     INFO -  PID 18099 | stack backtrace:

**Comment by jrmuizel** [comment]
How about this https://treeherder.mozilla.org/#/jobs?repo=try&revision=3e11f519b0e2b4c7fb5475904d7541d3bc37b850

**Pull request merged**
