### PR TITLE
Remove support for start/end center in radial gardients

### PR DESCRIPTION
**Pull request by mrobinson**
Though this may be necessary for SVG, it is currently unused and
blocking optimizations to the gradient shader.

This is part of #2439.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2534)

### CODE REVIEW

**Comment by mrobinson** [comment]
Here is the Gecko try job for this change: https://treeherder.mozilla.org/#/jobs?repo=try&revision=11ac2a7613418ab75dc54c23c6d33f30c1b4495b

**Comment by kvark** [comment]
I don't know whether we'll actually need it, but the removal code looks fine by me.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[webrender/res/brush_radial_gradient.glsl, line 52 at r1](https://reviewable.io:443/reviews/servo/webrender/2534#-L7jVElAx-9KsaY8ZCbt:-L7jVElAx-9KsaY8ZCbu:b4isift) ([raw file](https://github.com/servo/webrender/blob/449e329bf42a704dce507ecfc694620b24327f5d/webrender/res/brush_radial_gradient.glsl#L52)):*
> ```GLSL
>     // fragment shader can work with circles
>     float ratio_xy = gradient.ratio_xy_extend_mode.x;
>     vPos.y *= ratio_xy;
> ```

I do find it weird that we use `ratio_xy` to only scale `y`

---

*[wrench/src/yaml_frame_reader.rs, line 603 at r1](https://reviewable.io:443/reviews/servo/webrender/2534#-L7jVuLhPzkAfooy_yvd:-L7jVuLjwRir77rtOZCS:b-t4niez) ([raw file](https://github.com/servo/webrender/blob/449e329bf42a704dce507ecfc694620b24327f5d/wrench/src/yaml_frame_reader.rs#L603)):*
> ```Rust
>     fn to_radial_gradient(&mut self, dl: &mut DisplayListBuilder, item: &Yaml) -> RadialGradient {
>         if item["start-radius"].is_badvalue() {
>             let center = item["center"].as_point() .expect("radial gradient must have center");
> ```

I don't find the changed style better, and there appears to be an extra space here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/2534#-:-L7jW5OGeDbT789MDjKa:bs90jbp)*

**Comment by mrobinson** [comment]
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[webrender/res/brush_radial_gradient.glsl, line 52 at r1](https://reviewable.io:443/reviews/servo/webrender/2534#-L7jVElAx-9KsaY8ZCbt:-L7jgrQL8C6ZwMHlmak0:b-97h0rg) ([raw file](https://github.com/servo/webrender/blob/449e329bf42a704dce507ecfc694620b24327f5d/webrender/res/brush_radial_gradient.glsl#L52)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

I do find it weird that we use `ratio_xy` to only scale `y`
</blockquote></details>

I tried to modify the shader as little as possible.

---

*[wrench/src/yaml_frame_reader.rs, line 603 at r1](https://reviewable.io:443/reviews/servo/webrender/2534#-L7jVuLhPzkAfooy_yvd:-L7jgu-ayzwLQu4vDja2:b-us8g0l) ([raw file](https://github.com/servo/webrender/blob/449e329bf42a704dce507ecfc694620b24327f5d/wrench/src/yaml_frame_reader.rs#L603)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

I don't find the changed style better, and there appears to be an extra space here
</blockquote></details>

Oops. I removed the space. I try to keep things on one line if they don't exceed the 100 character limit and it isn't too horrendous. I can modify these though, if you like.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/2534)*

**Pull request merged**
