### PR TITLE
Border shader refactor

### LINKED ISSUE #1102: Rounded borders are not clipped properly
The follow wrench YAML does not show the bottom corners of the border clipped properly:

```yaml
---
root:
  items:
    - type: scroll-layer
      bounds: [0, 0, 100, 100]
      clip:
        rect: [0, 0, 100, 100]
        complex:
          - rect: [0, 0, 100, 100]
            radius:
              top-left: [0, 0]
              top-right: [0, 0]
              bottom-right: [30, 30]
              bottom-left: [30, 30]
      items:
        - type: border
          bounds: [0, 0, 100, 100]
          width: [5, 5, 5, 5]
          border-type: normal
          style: [solid, solid, solid, solid]
          color: [blue, blue, blue, blue]
          radius:
            top-left: [30, 30]
            top-right: [30, 30]
            bottom-right: [0, 0]
            bottom-left: [0, 0]
```

This seems to be an issue with the radius itself. Removing the radius on the border causes the corners to be clipped properly.

### PR DESCRIPTION
**Pull request by kvark**
Fixes #1102 
r? @glennw or @mrobinson

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1104)

### CODE REVIEW

**Comment by jrmuizel** [comment]
Are the corners supposed to be thinner than the sides?

**Comment by kvark** [comment]
@jrmuizel I agree this doesn't look right, but this PR is unrelated.

**Comment by glennw** [comment]
@jrmuizel @kvark BTW I'm working on refactoring the border code, including a fix for the corners being thinner. But those changes won't conflict with this, so we can get this merged - I'll test it against the Servo WPT suite today.

**Comment by glennw** [comment]
Actually, this seems straight forward enough from looking at it :)

@bors-servo r+

**Pull request merged**
