### PR TITLE
Use the glBlendColor approach for all subpixel text (except the WithBgColor case)

### PR DESCRIPTION
**Pull request by mstange**
We can use the glBlendColor approach even if we have transparent text and even if we have a clip or a mask. The math works out correctly.

The clip can be viewed as something that gets applied to the text mask before we use the text mask for blending.

r? @kvark or @glennw

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2009)

### CODE REVIEW

**Comment by glennw** [comment]
If the math for this works out, great (I didn't do the math myself to check)!

There are a few reftest failures though - they might be very small differences that just need a new reference generated?

**Comment by mstange** [comment]
Both reftest failures only have a max difference of 1, so I'll fuzz them.

**Comment by glennw** [comment]
Since they are PNG references, I think it's better to regenerate the images.

**Comment by mstange** [comment]
Oops, you're right, I missed that they were PNG references.

**Comment by mstange** [comment]
Updated the images. r? @glennw

**Comment by glennw** [comment]
@mstange Could you crop the reference images? Sadly, the auto-crop fails here since the PNG name doesn't match the test name (due to the same test being run once in subpx mode and once in alpha mode). Sorry!

**Comment by glennw** [comment]
I should make the auto-crop a bit smarter in that regard...

**Comment by mstange** [comment]
Sure, will crop.

**Comment by mstange** [comment]
Done.

**Comment by glennw** [comment]
Thank you!

@bors-servo r+

**Pull request merged**
