### PR TITLE
allow scrolling past child layer, when a new scroll starts at the end of child layer

### PR DESCRIPTION
**Pull request by gterzian**
WIP for https://github.com/servo/servo/issues/13249

---

This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/465)

### CODE REVIEW

**Comment by gterzian** [comment]
FYI I just rebased off master, and I think because of the version bump to 0.7 I'm currently having troubles building it with servo, so haven't actually tested it since the rebase, will do once I get a chance to look at the build issues(related to overriding the crate locally). If it happens to be broken now, please bear with me 😄

**Comment by gterzian** [comment]
To summarize what was discussed in https://github.com/servo/servo/issues/13249
*  "If a new scroll gesture starts while you're already scrolled all the way to the edge of the scrollable element under the mouse, then the scroll will be handed off to the next outer scrollable element which is actually scrollable in that direction" https://github.com/servo/servo/issues/13249#issuecomment-253023617
* "If you scroll a long page, and somewhere on that page is a smaller scrollable element, you don't want that element to swallow the rest of your scroll gesture if it suddenly happens to move under your mouse. You want the current scroll gesture to keep scrolling the outer page." https://github.com/servo/servo/issues/13249#issuecomment-253095424

**Comment by pcwalton** [comment]
Is this ready for review and ready to go?

**Comment by gterzian** [comment]
@pcwalton yes it is, thank you for your time.

**Comment by gterzian** [comment]
@pcwalton since from the issue itself it might not be clear what the goal of this PR is, there are two:

1. When a child layer has scrolled to it's end, and a new scroll gesture is started, start scrolling the nearest parent layer. 
2. When on is scrolling a layer, and one encounters a scrollable child layer, one should keep scrolling the currently scrolling parent layer. 

See the comments above for links to the discussions around this within the issue.

**Comment by gterzian** [comment]
@pcwalton @glennw Since there was quite a big change in the `scroll` function, I am currently looking if my changes are necessary at all, and if so, how to re-implement based on the latest... I'll let you know when that is done...

**Comment by mrobinson** [comment]
@gterzian Let me know if you need my input for that. I'm sorry that my change stomped on yours!

**Comment by gterzian** [comment]
@mrobinson thanks for your offer of input, and no problem at all! 😄 

Let me get a better look at the changes, and test the latest behaviour, then I'll get back to you...

**Comment by gterzian** [comment]
@pcwalton @glennw ok from my initial testing it seems that the behavior suggested in https://github.com/servo/webrender/pull/465#issuecomment-258081873 is still something that needs to be implemented. 

@mrobinson perhaps it's best if I wait until the servo part of you work has been merged, and then use that as a basis for exploring how to re-implement my changes?

**Comment by gterzian** [comment]
closing, in favor of https://github.com/servo/webrender/pull/533

**Pull request closed without merging**
