### PR TITLE
RON writer integration

### PR DESCRIPTION
**Pull request by kvark**
Rusty Object Notation:
- project: https://github.com/ron-rs/ron
- spec: https://github.com/ron-rs/ron/wiki/Specification

The integration doesn't add a whole lot of code, and the dependency is lightweight.
If JSON output is useful, so is RON. I think it's somewhat nicer to look at (comparing to YAML) because you don't need to trust the serializer as much (serde FTW). If not useful, we can remove both.

cc @jrmuizel 

Example output (from showing `transforms/image-rotated-clip.yaml`):
```yaml
[
    {
        "item": (
            item: PushStackingContext((
                stacking_context: (
                    scroll_policy: Scrollable,
                    transform: None,
                    transform_style: Flat,
                    perspective: None,
                    mix_blend_mode: Normal,
                ),
            )),
            clip_and_scroll: (
                scroll_node_id: Clip(0, (0, 0)),
                clip_node_id: None,
            ),
            info: (
                rect: ((0, 0), (1920, 1080)),
                local_clip: Rect(((0, 0), (1920, 1080))),
                is_backface_visible: true,
                tag: None,
            ),
        ),
        "filters": [
        ],
    },
    {
        "item": (
            item: Clip((
                id: ClipExternalId(1, (0, 0)),
                parent_id: Clip(0, (0, 0)),
                image_mask: None,
            )),
            clip_and_scroll: (
                scroll_node_id: Clip(0, (0, 0)),
                clip_node_id: None,
            ),
            info: (
                rect: ((18, 18), (400, 400)),
                local_clip: Rect(((18, 18), (400, 400))),
                is_backface_visible: true,
                tag: None,
            ),
        ),
    },
    {
        "item": (
            item: PushStackingContext((
                stacking_context: (
                    scroll_policy: Scrollable,
                    transform: Some(Value((0.7071067690849304, 0.7071067690849304, 0, 0, -0.7071067690849304, 0.7071067690849304, 0, 0, 0, 0, 1, 0, 218, -64.84271240234375, 0, 1))),
                    transform_style: Flat,
                    perspective: None,
                    mix_blend_mode: Normal,
                ),
            )),
            clip_and_scroll: (
                scroll_node_id: ClipExternalId(1, (0, 0)),
                clip_node_id: None,
            ),
            info: (
                rect: ((0, 0), (0, 0)),
                local_clip: Rect(((0, 0), (0, 0))),
                is_backface_visible: true,
                tag: None,
            ),
        ),
        "filters": [
        ],
    },
    {
        "item": (
            item: Image((
                image_key: ((1), 1),
                stretch_size: (400, 400),
                tile_spacing: (0, 0),
                image_rendering: Auto,
            )),
            clip_and_scroll: (
                scroll_node_id: ClipExternalId(1, (0, 0)),
                clip_node_id: None,
            ),
            info: (
                rect: ((0, 0), (400, 400)),
                local_clip: Rect(((0, 0), (400, 400))),
                is_backface_visible: true,
                tag: None,
            ),
        ),
    },
    {
        "item": (
            item: PopStackingContext,
            clip_and_scroll: (
                scroll_node_id: ClipExternalId(1, (0, 0)),
                clip_node_id: None,
            ),
            info: (
                rect: ((0, 0), (0, 0)),
                local_clip: Rect(((0, 0), (0, 0))),
                is_backface_visible: true,
                tag: None,
            ),
        ),
    },
    {
        "item": (
            item: PopStackingContext,
            clip_and_scroll: (
                scroll_node_id: Clip(0, (0, 0)),
                clip_node_id: None,
            ),
            info: (
                rect: ((0, 0), (0, 0)),
                local_clip: Rect(((0, 0), (0, 0))),
                is_backface_visible: true,
                tag: None,
            ),
        ),
    },
]
```

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1829)

### CODE REVIEW

**Comment by jrmuizel** [comment]
Can you post the json for the same thing?

**Comment by kvark** [comment]
Build fails because RON apparently requires Rust 1.20. Marking the PR as blocked until WR's rust version is bumped.

@jrmuizel JSON is about 3x larger, so I'm only posting a fraction of it here:
```json
[
  {
    "item": {
      "item": {
        "PushStackingContext": {
          "stacking_context": {
            "scroll_policy": "Scrollable",
            "transform": null,
            "transform_style": "Flat",
            "perspective": null,
            "mix_blend_mode": "Normal"
          }
        }
      },
      "clip_and_scroll": {
        "scroll_node_id": {
          "Clip": [
            0,
            [
              0,
              0
            ]
          ]
        },
        "clip_node_id": null
      },
      "info": {
        "rect": [
          [
            0.0,
            0.0
          ],
          [
            1920.0,
            1080.0
          ]
        ],
        "local_clip": {
          "Rect": [
            [
              0.0,
              0.0
            ],
            [
              1920.0,
              1080.0
            ]
          ]
        },
        "is_backface_visible": true,
        "tag": null
      }
    },
    "filters": []
  },
  {
    "item": {
      "item": {
        "Clip": {
          "id": {
            "ClipExternalId": [
              1,
              [
                0,
                0
              ]
            ]
          },
          "parent_id": {
            "Clip": [
              0,
              [
                0,
                0
              ]
            ]
          },
          "image_mask": null
        }
      },
      "clip_and_scroll": {
        "scroll_node_id": {
          "Clip": [
            0,
            [
              0,
              0
            ]
          ]
        },
        "clip_node_id": null
      },
      "info": {
        "rect": [
          [
            18.0,
            18.0
          ],
          [
            400.0,
            400.0
          ]
        ],
        "local_clip": {
          "Rect": [
            [
              18.0,
              18.0
            ],
            [
              400.0,
              400.0
            ]
          ]
        },
        "is_backface_visible": true,
        "tag": null
      }
    }
  }
]
```

**Comment by glennw** [comment]
I'm fine with merging this, and it looks like the rustc update has landed - but there are some unrelated CI errors that need to be resolved first.

**Comment by kvark** [comment]
Rebased, fixed servo tidy, and raised the CI rust requirements to 1.20, which is safe according to this comment: https://bugzilla.mozilla.org/show_bug.cgi?id=1396884#c11

**Comment by kvark** [comment]
Looks like CI is happy, minus the minor annoyance:
> The job exceeded the maximum time limit for jobs, and has been terminated.

Waiting for r+ on this.

**Pull request merged**
