### PR TITLE
Revert Revert Rectangle Snapping

### PR DESCRIPTION
**Pull request by Gankro**
I got 5 stable builds of Servo here: https://github.com/servo/servo/pull/17297 (all the failures are unrelated or before I applied the updated test expectations).

Should probably wait for Euclid refactoring stuff to clear up before merging this.

r?glennw,kvark

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1375)

### CODE REVIEW

**Comment by Gankro** [comment]
Sqaushed pre @kvark's request. Here's the new commit message:

------

Revert "Revert the snap rect changes"
    
    This reverts #1339, which just reverted #1292 and #1319.
    
    The original changes seem to behaving well now. It's unclear what was happening,
    but whatever it was, it seems fine now!
    
    Here is the full list of reverts:
    
    Revert "Manually re-apply ANGLE workaround in 3debb5781551243aed45f7cf065518ea80932d24."
    This reverts commit 9143f1d565f20086b1b00c9ee132cfbe30c658da.
    
    Revert "Revert "Full rectangular pixel snapping""
    This reverts commit de7e944df90ee5e882393f196f7ec6c410b4d3a1.
    
    Revert "Revert "Snapping transformed primitives""
    This reverts commit dae62c55a0036f60831442a85a8c2abf7a043135.
    
    Revert "Revert "Snapping ref tests""
    This reverts commit d6f03ba0a3e6f9f97a40fff4f09a06e3ddcd13e4.
    
    Revert "Revert "Ensure that subpixel sized snap rects are at least 1 device pixel.""
    This reverts commit d396a7ed6d5f384c75f4beeb5206682f24dade8f.
    
    Revert "Revert "clamp_rect Angle workaround""
    This reverts commit ef24b789ad67faeed7692ab7f3299858366e48c3.
    
    Revert "Revert "Don't apply local clip rect to snap rectangle calculation.""
    This reverts commit 406b102518cbb6e62021311d64f652dd93e4148b.

**Comment by glennw** [comment]
I think we should hold off on this until the serde 1.0 bump lands (should be tomorrow), to make sure that goes through. Once that lands, let's get this merged and updated into Servo.

**Comment by kvark** [comment]
Thanks!
Looking forward to "Revert Revert Revert Rectangle Snapping" ;)

**Comment by staktrace** [comment]
@Gankro I believe this patch is giving a shader compilation failure on ANGLE: [link](https://treeherder.mozilla.org/#/jobs?repo=try&revision=39493995248c66aa70d3d24c9a040566cdd9ae61&selectedJob=108235249)

I haven't verified it was this PR but I recall we ran into this before and it was fixed when the original landing was reverted, so I assume it came back because of this re-landing.

```
09:02:58    ERROR - thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Link("cs_clip_image", "C:\\fakepath(1116,24-94): error X3067: \'_intersect_rect\': ambiguous function call\n\nWarning: D3D shader compilation failed with default flags. (vs_5_0)\n Retrying with skip validation\nC:\\fakepath(1116,24-94): error X3067: \'_intersect_rect\': ambiguous function call\n\nWarning: D3D shader compilation failed with skip validation flags. (vs_5_0)\n Retrying with skip optimization\nC:\\fakepath(1116,24-94): error X3067: \'_intersect_rect\': ambiguous function call\n\nWarning: D3D shader compilation failed with skip optimization flags. (vs_5_0)\n\n\n\nFailed to create D3D shaders.\n")', src\libcore\result.rs:859
09:02:59     INFO - stack backtrace:
09:02:59     INFO -    0: <unknown>
09:02:59     INFO -    1: <unknown>
09:02:59     INFO -    2: <unknown>
09:02:59     INFO -    3: <unknown>
09:02:59     INFO -    4: <unknown>
09:02:59     INFO -    5: <unknown>
09:02:59     INFO -    6: <unknown>
09:02:59     INFO -    7: <unknown>
09:02:59     INFO -    8: mozilla_dump_image
09:02:59     INFO -    9: mozilla_dump_image
09:02:59     INFO -   10: mozilla_dump_image
09:02:59     INFO -   11: mozilla_dump_image
09:02:59     INFO -   12: <unknown>
09:02:59     INFO -   13: <unknown>
09:02:59     INFO -   14: <unknown>
09:02:59     INFO -   15: <unknown>
09:02:59     INFO -   16: <unknown>
09:02:59     INFO -   17: <unknown>
09:02:59     INFO -   18: <unknown>
09:02:59     INFO -   19: <unknown>
09:02:59     INFO -   20: BaseThreadInitThunk
```

**Comment by staktrace** [comment]
This also causes the gecko reftest at layout/reftests/pixel-rounding/iframe-1.html to fail. There are other reftest differences but those appear to just be fuzziness changes. The iframe-1.html failure looks like an actual bug.

[Try push without this PR](https://treeherder.mozilla.org/#/jobs?repo=try&revision=1bbe717d1c0ada18502d6e302ea576495552e6e5)
[Try push with this PR](https://treeherder.mozilla.org/#/jobs?repo=try&revision=013cfea91b2f5c7e84a12f0fa7f494c53ee207c3)

[Reftest analyzer for iframe-1.html failure](https://hg.mozilla.org/mozilla-central/raw-file/tip/layout/tools/reftest/reftest-analyzer.xhtml#logurl=https://queue.taskcluster.net/v1/task/A_nVgdxHT566sk0QUOcX5g/runs/0/artifacts/public/logs/live_backing.log&only_show_unexpected=1)

**Comment by Gankro** [comment]
Shader failure should be fixed by https://github.com/servo/webrender/pull/1401

**Pull request merged**
