### PR TITLE
Fix merging text shadow primitives during batch merging.

### LINKED ISSUE #2508: some text-shadows don't show up
Seems this has been happening for a month, and I don't see any consistent pattern.

The following reftest doesn't render the red shadow. Removing the black shadow makes the red one show up.

```
--- # A simple example of two shadows
root:
  items:
        -
          type: "shadow"
          bounds: [14, 18, 205, 35]
          blur-radius: 2
          offset: [-2, -2]
          color: [255, 0, 0, 1]
        -
          type: "shadow"
          bounds: [14, 18, 205, 35]
          blur-radius: 2
          offset: [2, 2]
          color: [0, 0, 0, 1]
        -
          bounds: [14, 18, 205, 35]
          glyphs: [55, 75, 76, 86, 3, 76, 86, 3, 87, 75, 72, 3, 69, 72, 86, 87]
          offsets: [16, 43, 35.533333, 43, 51.533333, 43, 60.4, 43, 72.833336, 43, 80.833336, 43, 89.7, 43, 102.13333, 43, 110.13333, 43, 119, 43, 135, 43, 149.2, 43, 157.2, 43, 173.2, 43, 187.4, 43, 196.26666, 43]
          size: 18
          color: [0, 0, 0, 1]
          font: "VeraBd.ttf"
        -
          type: "pop-all-shadows"
```

The test that should notice this, shadow-many, is only !='d so this slipped through. Also sometimes shadows do show up, so some other tests pass fine??

[Bugzilled](https://bugzilla.mozilla.org/show_bug.cgi?id=1444985)

### PR DESCRIPTION
**Pull request by glennw**
Fixes #2508.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2515)

### CODE REVIEW

**Comment by glennw** [comment]
r? @Gankro or anyone

I expect this to fail on CI - for some reason my machine generates different text layout that CI, which I haven't looked into yet. I'll pull the CI generated reftest image from this CI run and use that.

**Comment by Gankro** [comment]
r=me with the test image fixed

**Pull request merged**
