### PR TITLE
Remove outset property of nine-patch-border

### PR DESCRIPTION
**Pull request by pyfisch**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/3076)

### CODE REVIEW

**Comment by mrobinson** [comment]
@pyfisch Are you also working on the Gecko side of this change?

**Comment by pyfisch** [comment]
No. I will only update servo.

Martin Robinson <notifications@github.com> schrieb am Di., 18. Sep. 2018,
13:30:

**Comment by kvark** [comment]
@jrmuizel ^?

**Comment by gw3583** [comment]
@jrmuizel @nical Any issues with removing this in WR? Does Gecko use it?

**Comment by nical** [comment]
Gecko currently [uses it](https://searchfox.org/mozilla-central/rev/924e3d96d81a40d2f0eec1db5f74fc6594337128/layout/painting/nsCSSRenderingBorders.cpp#3880). I don't have any issue with removing the property as long as the corresponding gecko functionality is adapted beforehand.

**Comment by mstange** [comment]
> Gecko currently [uses it](https://searchfox.org/mozilla-central/rev/924e3d96d81a40d2f0eec1db5f74fc6594337128/layout/painting/nsCSSRenderingBorders.cpp#3880).

But note that this code [isn't actually being run at the moment](https://searchfox.org/mozilla-central/rev/7f7c353e969e61a6a85201cc8ad3c3de12ac30d8/layout/painting/nsCSSRendering.cpp#796-797,801-803) ([bug 1408690](https://bugzilla.mozilla.org/show_bug.cgi?id=1408690) tracks fixing and re-enabling it).

**Pull request closed without merging**
