### PR TITLE
remove vestigial .travis.yml

### PR DESCRIPTION
**Pull request by Gankro**
this PR is just checking to see what happens if I do this

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/3263)

### CODE REVIEW

**Comment by kvark** [comment]
@Gankro what's the motivation?

**Comment by staktrace** [comment]
Came out of this: https://mozilla.logbot.info/gfx/20181101#c15554510

It's obsoleted by the Taskcluster CI so there's not much point keeping it any more.

**Comment by Gankro** [comment]
Deleting dead code is good, especially when there's a decent chance we need to migrate our testing infra to gecko.

**Comment by kvark** [comment]
Congratulations, we saved 60 lines of code, and now everyone needs to understand how Taskcluster is configured in case we have any issues with CI.

**Comment by Gankro** [comment]
@kvark I don't understand, we literally don't run travis ever, what are you imagining?

**Comment by kvark** [comment]
@Gankro indeed. For some reason I thought we aren't running MacOS travis, but still got linux.

**Pull request merged**
