### PR TITLE
Switch android to use GLESv3.

### PR DESCRIPTION
**Pull request by glennw**

### CODE REVIEW

**Comment by larsbergstrom** [comment]
The purely administrative bits look good to me, but there are some constant changes in there that I'd like for @pcwalton to take a quick look at, if possible.

Thanks for doing this, @glennw! This is huge for all the people clamoring for Android support for Servo+WR in master.

**Comment by larsbergstrom** [comment]
From Travis:

```
/home/travis/.cargo/git/checkouts/webrender_traits-e24a580db67dabe6/master/src/webgl.rs:295:17: 295:38 error: unresolved name `gl::copy_tex_image_2d` [E0425]

/home/travis/.cargo/git/checkouts/webrender_traits-e24a580db67dabe6/master/src/webgl.rs:295                 gl::copy_tex_image_2d(target, level, internal_format, x, y, width, height, border),

                                                                                                            ^~~~~~~~~~~~~~~~~~~~~

/home/travis/.cargo/git/checkouts/webrender_traits-e24a580db67dabe6/master/src/webgl.rs:295:17: 295:38 help: run `rustc --explain E0425` to see a detailed explanation

error: aborting due to previous error

error: Could not compile `webrender_traits`.
```

**Comment by larsbergstrom** [comment]
@pcwalton Could you please take a look at these changes (assuming gw can fix the build failure)? This work is blocking Android. Thanks!

**Comment by larsbergstrom** [comment]
@pcwalton Can you please look at this PR this week? Thanks!

**Comment by glennw** [comment]
@larsbergstrom I'm not sure what was up with travis - I retried the PR on travis this morning and it is green now.

**Pull request merged**
