### PR TITLE
Move processing of frame messages to before call to build_scene

### LINKED ISSUE #2820: First call to set_output_document has no effect
The frame output example stopped working some time ago. 

The issue seems to be that frame messages (which contain `EnableFrameOutput` are processed after the call to `build_scene` resulting in an empty list of `output_pipelines` getting passed to the `FrameBuilder`.

Moving the processing of frame messages to before the call to `build_scene` fixes the issue. There is a separate issue where nothing is rendered in the example.

### PR DESCRIPTION
**Pull request by hgallagher1993**
Fixes #2820

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2866)

### CODE REVIEW

**Comment by staktrace** [comment]
This is going to break APZ in gecko, because the sampler callback will produce incorrect values

**Comment by staktrace** [comment]
#2820 could also be fixed by moving the enable_frame_output into a separate transaction that is submitted before the transaction that has the display list.

**Comment by hgallagher1993** [comment]
:+1: Just an FYI as well I'll be gone from this evening until probably Sunday so it'll be a good few days before I get back to this

**Comment by nc4rrillo** [comment]
So if we can just move `enable_frame_output` to a separate transaction it may be enough to just update the frame output sample.

**Comment by hgallagher1993** [comment]
Sorry about the delay with this, my home directory got wiped last week so I've just been busy trying to restore everything (like all the opensource projects I had downloaded) so I'll try and get this finished in the next day or 2

**Pull request closed without merging**
