### PR TITLE
Strong DevicePixelScale

### PR DESCRIPTION
**Pull request by kvark**
Pending gecko try: https://treeherder.mozilla.org/#/jobs?repo=try&revision=d946335ccf31266d011248c7300df511ad10c70b

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2246)

### CODE REVIEW

**Comment by kvark** [comment]
Try looks green, this is ready for review.

**Comment by glennw** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/2246)*

**Comment by glennw** [comment]
Looks good to me!

**Pull request merged**
