### PR TITLE
Use the core-text-rs feature to ensure OS X 10.7 build compatibility,…

### PR DESCRIPTION
**Pull request by staktrace**
… as mozilla-central requires this

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1409)

### CODE REVIEW

**Comment by kvark** [comment]
I disagree on the way `core-text` was patched (see https://github.com/servo/core-text-rs/pull/61#issuecomment-309853548)
Merging though, given the urgency.
@bors-servo r+

**Comment by staktrace** [comment]
Not actually that urgent right now, since I cherry-picked this change into m-c directly. If you want to do it differently we can abort this and do it better.

**Comment by staktrace** [comment]
Updated the PR to pull core-text 6.0.0 with default-features=false, so that it excludes the 10.8+ APIs. Note that wrench uses font-loader which still uses core-text 5.0 so now the lockfile has both 5.0.1 and 6.0.0. I can submit a PR to font-loader to bump their version if that's something we care about. Since we don't pull wrench into gecko it isn't an issue for mozilla-central.

**Comment by staktrace** [comment]
Looks like the servo-tidy doesn't like having both versions of core-text in the lockfile. I'll submit a PR for font-loader.

**Comment by staktrace** [comment]
@kvark updated patch seems to be passing tests now. Not sure if you need to r+ again or maybe homu/bors need a kick?

**Comment by kvark** [comment]
Thanks!
@bors-servo r+

**Pull request merged**
