### PR TITLE
Sync changes from mozilla-central gfx/wr

### PR DESCRIPTION
**Pull request by moz-gfx**

### CODE REVIEW

**Comment by staktrace** [comment]
@gw3583 @lsalzman 

```
REFTEST TEST-UNEXPECTED-FAIL | reftests/text/shadow-transforms.yaml == reftests/text/shadow-transforms.png | image comparison, max difference: 2, number of differing pixels: 144 | 144 differences > 0 and <= 2 (allowed 135); 
```

Any idea which patch caused it? I'm guessing there's some subtle environment differences between this CI and Firefox CI.

**Comment by staktrace** [comment]
Difference is 169 pixels on release job.

**Comment by gw3583** [comment]
The recent change to use 2d textures instead of texture arrays causes this. It also causes an intermittent on m-c, but with less fuzziness - I've included fuzziness for this amount in https://phabricator.services.mozilla.com/D99825.

**Pull request merged**
