### PR TITLE
Sync changes from mozilla-central gfx/wr

### PR DESCRIPTION
**Pull request by moz-gfx**

### CODE REVIEW

**Comment by staktrace** [comment]
@jdm do you know if the appveyor plan for the servo account changed? i thought the build time allowed was 100 minutes but now it seems to be 60 minutes causing failures.

**Comment by jdm** [comment]
Yes, there was a discussion in #gfx-firefox about how we reverted to the free plan and Appveyor should be turned off on this repo if that caused any issues.

**Comment by jdm** [comment]
See https://chat.mozilla.org/#/room/#gfx:mozilla.org/$IwPMtoja7ldOPVgDCXZl41bl2B2nVmiTrv5MSxUEz1k.

**Comment by staktrace** [comment]
Ok, thanks. I'll remove the appveyor.yml file then.

**Pull request merged**
