### PR TITLE
Make sure no PBO is bound on texture deletion

### PR DESCRIPTION
**Pull request by kvark**
Attempt to fix https://bugzilla.mozilla.org/show_bug.cgi?id=1395327
r? @glennw

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1639)

### CODE REVIEW

**Comment by glennw** [comment]
Looks sane, thanks!

@bors-servo r+

**Comment by jrmuizel** [comment]
FWIW, I still get crashes with this manually applied.

**Comment by kvark** [comment]
@jrmuizel thanks for testing this!
Perhaps, you could also try changing the width/height/depth we pass to `tex_image_3d` in `free_texture_storage`? E.g. pass 1s instead of 0s.

**Comment by glennw** [comment]
@jrmuizel Are you able to test with the integrated GPU force enabled? It sounds like it may be an issue in the nvidia driver.

**Comment by Gankro** [comment]
I applied the tip of this branch on top of @staktrace's latest WR update (https://hg.mozilla.org/try 8117e084974a) and can no longer reproduce the crashes.

**Comment by jrmuizel** [comment]
Do we have any idea what code paths would've triggered this so that we can get a test in the webrender repo?

**Comment by Gankro** [comment]
Scratch that, reproduced reliably this morning. Guess I got lucky last night. 😖

**Comment by kvark** [comment]
@jrmuizel my hypothesis (for this PR) was `TextureUpdateOp::Update` followed by `TextureUpdateOp::Free`, which was trying to deallocate texture space while a PBO is bound.
Now that you confirmed it's not fixing the bug for you, we are back to square one.

**Pull request merged**
