### PR TITLE
Update core-graphics and core-text for building on 10.12

### PR DESCRIPTION
**Pull request by jrmuizel**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2922)

### CODE REVIEW

**Comment by mstange** [comment]
```
./Cargo.lock:1: duplicate versions for package `core-text`
	The following packages depend on version 10.0.0 from 'crates.io':
		font-loader
		pathfinder_font_renderer
	The following packages depend on version 11.0.0 from 'crates.io':
		webrender
./Cargo.lock:1: duplicate versions for package `core-graphics`
	The following packages depend on version 0.14.0 from 'crates.io':
		cocoa
		core-text
		glutin
		pathfinder_font_renderer
		winit
	The following packages depend on version 0.16.0 from 'crates.io':
		core-text
		webrender
		webrender_api
		wrench

```

**Comment by nox** [comment]
Why weren't the packages deduplicated? The breaking bump should have been propagated through all the dependencies.

**Pull request merged**
