### PR TITLE
Print list of unexpected test results after refest run

### PR DESCRIPTION
**Pull request by mrobinson**
It's really difficult to see what tests failed with the amount of
base64 encoded images. Since the reftests don't consistently pass on
most systems, it can be difficult to use wrench when working on changes.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1414)

### CODE REVIEW

**Comment by kvark** [comment]
Nice!
@bors-servo r+

**Comment by kvark** [comment]
> ./wrench/src/reftest.rs:60: missing space before {

**Comment by mrobinson** [comment]
Sorry about the tidy failure. It should be fixed now.

**Comment by kvark** [comment]
@mrobinson looks like you forgot to push the changes?

**Comment by mrobinson** [comment]
@kvark You're right. I think I've pushed it successfully now.

**Comment by kvark** [comment]
Waiting for #1417 to land in order to make Travis happy

**Pull request merged**
