### PR TITLE
Switch to a serial osmesa build to fix mac CI issues

### PR DESCRIPTION
**Pull request by jrmuizel**
Something like this worked for me on my last update to #2635

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2639)

### CODE REVIEW

**Comment by glennw** [comment]
What does a serial build change / mean?

**Comment by jrmuizel** [comment]
We build osmesa with -j1. (I really could have been clearer :))

**Comment by jrmuizel** [comment]
This seems to have worked on this PR as well. I suggest we take this for now and try to figure out why it doesn't work anymore after.

**Comment by glennw** [comment]
@jrmuizel Sounds good, thanks!

I'm still not entirely clear on what has changed recently that could cause this?

@bors-servo r+

**Pull request merged**
