### PR TITLE
Renderer coverage profiling

### PR DESCRIPTION
**Pull request by kvark**
Computes the fraction of screen getting covered by the opaque/transparent passes.
Also hides `renderer` module from the public eyes (breaking change).
r? @glennw

~~WIP until the FF patch is ready~~
[wr-profile.diff.zip](https://github.com/servo/webrender/files/1240226/wr-profile.diff.zip)

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1594)

### CODE REVIEW

**Comment by glennw** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/1594)*

**Comment by kvark** [comment]
@glennw thanks!
I agree that GL queries would be more universal to implement and useful as a metric. Will look into it.

**Comment by glennw** [comment]
@kvark Cool, sounds good. ```GL_SAMPLES_PASSED``` should give us what we want, I think.

**Comment by kvark** [comment]
@glennw please take another look

wr-sampler-profile

**Comment by glennw** [comment]
Reviewed 4 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/webrender/1594)*

**Comment by glennw** [comment]
Nice, this looks great! Could you just confirm that the reported compositor CPU time with this change is the same as without. I couldn't see anything that would introduce a stall, but the CPU compositor time in that screenshot seems very high (although maybe that's caused by the screenshot tool or something?).

Otherwise, r=me.

**Comment by kvark** [comment]
@glennw thanks for taking a look!
Good point about compositor timing. I'll compare and get back here.

**Comment by glennw** [comment]
Once this is all in and working, these would be good counters to add to the values tracked on the perf dashboard.

**Comment by kvark** [comment]
@glennw both master and this PR code show equal numbers for CPU compositor timing on that sample:
  - debug: ~7ms
  - release: ~14ms

**Comment by glennw** [comment]
@kvark Interesting - I guess you're running with vsync on, perhaps? The reported time in CPU for that test on my machine is ~0.2 ms with vsync off.

@bors-servo r+

**Comment by kvark** [comment]
FF patch
```diff
diff --git a/gfx/webrender_bindings/src/bindings.rs b/gfx/webrender_bindings/src/bindings.rs
index 758e8945bf71..e2f41dccc1b6 100644
--- a/gfx/webrender_bindings/src/bindings.rs
+++ b/gfx/webrender_bindings/src/bindings.rs
@@ -7,9 +7,9 @@ use std::os::raw::{c_void, c_char, c_float};
 use gleam::gl;
 
 use webrender_api::*;
-use webrender::renderer::{ReadPixelsFormat, Renderer, RendererOptions};
-use webrender::renderer::{ExternalImage, ExternalImageHandler, ExternalImageSource};
-use webrender::renderer::DebugFlags;
+use webrender::{ReadPixelsFormat, Renderer, RendererOptions};
+use webrender::{ExternalImage, ExternalImageHandler, ExternalImageSource};
+use webrender::DebugFlags;
 use webrender::{ApiRecordingReceiver, BinaryRecorder};
 use thread_profiler::register_thread_with_profiler;
 use moz2d_renderer::Moz2dImageRenderer;
```

**Pull request merged**
