### PR TITLE
Support external image for yuv format.

### PR DESCRIPTION
**Pull request by JerryShih**
#936 
@nical @kvark @glennw 
This is the straightforward implementation for external yuv format image. When WR has the external images for some specific yuv channels, it will put that images into a deferred_resolves list. Then, resolve the image content and uv coordinate at renderer.
The yuv_image() interface is not changed here.

But I would like to have a single external image id for a yuv image:
```
1. add new interface yuv_image() in api
yuv_key = api.add_yuv_image(...., y_buffer, ...., u_buffer, ...., v_buffer)
2. update yuv_image() interface in frame_builder
builder.add_yuv_image(...., yuv_key, ...)
```

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/952)

### CODE REVIEW

**Comment by glennw** [comment]
This approach works, but I don't think it's ideal to be patching the general gpu_data64 array from the renderer. This could complicate things in the future once we're doing incremental updates.

As an alternative approach, could we port the external image code to store the UVs for the images in the resource_rects structure (like normal images do)? This could even be done as an initial step and landed independently of this work.

I *think* that will simplify this patch quite a lot - by making the deferred resolve in the renderer consistent (so it only ever needs to operate on the resource_rects patching).

Does that sound reasonable?

**Comment by JerryShih** [comment]
Thanks, I will check how to use resource_rects for yuv_image first.

**Comment by JerryShih** [comment]
@glennw @kvark 
This update is base on #970(use gpu_resource_rects for yuv image).

**Comment by JerryShih** [comment]
rebase for #970

**Comment by glennw** [comment]
@bors-servo r+

@JerryShih Nice one, this worked out really well!

**Pull request merged**
