### PR TITLE
Debug tracking of display items

### PR DESCRIPTION
**Pull request by kvark**
This is a different take on #2710

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2725)

### CODE REVIEW

**Comment by glennw** [comment]
Looks fine to me - will need a rebase though. Do you have a preference for this version or the other?

**Comment by gw3583** [comment]
@kvark Did we want to get this one merged?

**Comment by kvark** [comment]
Eh, unfortunately this looks way more verbose than the fresh new `?` I put just recently. Leaving the code for a few other picky eyes to glance over.

**Comment by gw3583** [comment]
@kvark What's the status of this and #2710 ? Should we close one of them?

**Comment by kvark** [comment]
I'm not super happy about the code structure here, but keeping it rebased isn't optimal either.
@bors-servo r=gw3583

**Pull request merged**
