### PR TITLE
Handle image keys in display lists that calling code has deleted.

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/1576)

### CODE REVIEW

**Comment by glennw** [comment]
r? @kvark 

This is mostly indentation changes.

**Comment by jdm** [comment]
https://github.com/servo/webrender/pull/1576/files?w=1

**Comment by kvark** [comment]
Thank you for taking care of those crashes!
@bors-servo r+

**Comment by jrmuizel** [comment]
Why do we want to warn instead of panic here? Isn't this basically a malicious client?

**Comment by glennw** [comment]
This situation occurs if, for example, the client submits a display list referencing an image key, then deletes the image key, and then calls generate frame.

**Comment by jrmuizel** [comment]
What's the use case for supporting that sequence and why would consumer want to draw the display list with the images missing? (that's what the patch does right?)

**Comment by glennw** [comment]
Right now, at least Servo (and perhaps Gecko) don't correctly use transactions to ensure atomically updating image keys vs. display lists. Certainly, once that happens, we could consider making this a panic condition again.

**Pull request merged**
