### PR TITLE
Android fixes

### LINKED ISSUE #786: Port wrench to run on android.

### PR DESCRIPTION
**Pull request by kvark**
likely fixes #786, although I was only running wr_sample

r? @glennw

---
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/820)

### CODE REVIEW

**Comment by kvark** [comment]
Heh, Travis errors seem weird. Everything passes but the exit code is 1.

**Comment by jrmuizel** [comment]
Isn't that because of:
```$ servo-tidy
Checking the config file...
Checking files for tidiness...
./sample/src/main.rs:42: missing space before =
./sample/src/main.rs:42: missing space after =
./sample/src/main.rs:47: missing space before =
./sample/src/main.rs:47: missing space after =
./sample/src/main.rs:78: missing space before =
./sample/src/main.rs:78: missing space after =
Running the dependency licensing lint...
The command "servo-tidy" exited with 1.
```

**Comment by kvark** [comment]
@jrmuizel thanks! should be fixed now

**Comment by kvark** [comment]
Failed to load OsMesa? hmm

**Pull request merged**
