### PR TITLE
Temporarily disable servo-tidy - new published version breaks WR.

### PR DESCRIPTION
**Pull request by glennw**
This change is [Reviewable](https://reviewable.io/reviews/servo/webrender/2522)

### CODE REVIEW

**Comment by glennw** [comment]
Testing as a potential fix for travis being broken

**Comment by glennw** [comment]
The newly published ```servo-tidy``` script appears to be breaking WR builds, in a number of ways.

* The requirements seem incorrect - I had to add PyYAML and voluptuous and manual dependencies, they aren't installed by pip.

* Once that is fixed, the servo-tidy script fails with a heap of errors. Those errors are (probably) all valid, but we can't fix them all right now.

```
2.42s$ servo-tidy
Checking the config file...
Checking directories for correct file extensions...
Checking files for tidiness...
./Cargo.lock:1: duplicate versions for package `gdi32-sys`
	The following packages depend on version 0.1.2 from 'crates.io':
		glutin
	The following packages depend on version 0.2.0 from 'crates.io':
		dwrote
		font-loader
./Cargo.lock:1: duplicate versions for package `winapi`
	The following packages depend on version 0.2.8 from 'crates.io':
		atty
		dwmapi-sys
		dwrote
		font-loader
		gdi32-sys
		gdi32-sys
		glutin
		iovec
		kernel32-sys
		libloading
		mio
		miow
		net2
		shell32-sys
		tempfile
		time
		user32-sys
		user32-sys
		ws2_32-sys
	The following packages depend on version 0.3.4 from 'crates.io':
		direct-composition
		memmap
		wincolor
		winit
./Cargo.lock:1: duplicate versions for package `gl_generator`
	The following packages depend on version 0.7.0 from 'crates.io':
		glutin
	The following packages depend on version 0.9.0 from 'crates.io':
		gleam
		mozangle
./Cargo.lock:1: duplicate versions for package `log`
	The following packages depend on version 0.3.6 from 'crates.io':
		gl_generator
		mio
		ws
	The following packages depend on version 0.4.1 from 'crates.io':
		env_logger
		gl_generator
		plane-split
		webrender
		wrench
./Cargo.lock:1: duplicate versions for package `core-foundation`
	The following packages depend on version 0.4.6 from 'crates.io':
		core-graphics
		glutin
		winit
	The following packages depend on version 0.5.1 from 'crates.io':
		core-graphics
		core-text
		font-loader
		webrender
		webrender_api
		wrench
./Cargo.lock:1: duplicate versions for package `core-foundation-sys`
	The following packages depend on version 0.4.6 from 'crates.io':
		core-foundation
	The following packages depend on version 0.5.1 from 'crates.io':
		core-foundation
./Cargo.lock:1: duplicate versions for package `yaml-rust`
	The following packages depend on version 0.3.4 from 'https://github.com/vvuk/yaml-rust':
		wrench
	The following packages depend on version 0.3.5 from 'crates.io':
		clap
./Cargo.lock:1: duplicate versions for package `user32-sys`
	The following packages depend on version 0.1.3 from 'crates.io':
		glutin
	The following packages depend on version 0.2.0 from 'crates.io':
		font-loader
./Cargo.lock:1: duplicate versions for package `lazy_static`
	The following packages depend on version 0.2.11 from 'crates.io':
		crossbeam-epoch
		dwrote
		ipc-channel
		shared_library
		thread_profiler
	The following packages depend on version 1.0.0 from 'crates.io':
		glutin
		libloading
		mozangle
		rayon-core
		wayland-kbd
		wayland-sys
		webrender
		winit
		wrench
		x11-dl
./Cargo.lock:1: duplicate versions for package `core-graphics`
	The following packages depend on version 0.12.4 from 'crates.io':
		cocoa
		glutin
		winit
	The following packages depend on version 0.13.0 from 'crates.io':
		core-text
		webrender
		webrender_api
		wrench
./direct-composition/src/com.rs:35: derivable traits list is not in alphabetical order
	expected: Debug, PartialEq
	found: PartialEq, Debug
./webrender_api/src/api.rs:12: use statement is not in alphabetical order
	expected: std::u32
	found: {BuiltDisplayList, BuiltDisplayListDescriptor, ColorF, DeviceIntPoint, DeviceUintRect}
./webrender_api/src/api.rs:652: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize
	found: Clone, Copy, Debug, Eq, PartialEq, Hash, Ord, PartialOrd, Deserialize, Serialize
./webrender_api/src/api.rs:1005: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, Serialize
	found: Clone, Copy, Serialize, Deserialize, Debug
./webrender_api/src/api.rs:1020: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, Eq, Hash, PartialEq, Serialize
	found: Clone, Copy, Debug, Deserialize, PartialEq, Serialize, Eq, Hash
./webrender_api/src/api.rs:1091: derivable traits list is not in alphabetical order
	expected: Clone, Debug, Deserialize, Serialize
	found: Clone, Deserialize, Serialize, Debug
./webrender_api/src/channel_ipc.rs:10: use statement is not in alphabetical order
	expected: std::thread
	found: std::{error, io}
./webrender_api/src/color.rs:96: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize
	found: Clone, Copy, Hash, Eq, Debug, Deserialize, PartialEq, PartialOrd, Ord, Serialize
./webrender_api/src/display_item.rs:9: use statement is not in alphabetical order
	expected: std::ops::Not
	found: {ColorF, FontInstanceKey, GlyphOptions, ImageKey, LayerPixel, LayoutPixel, LayoutPoint}
./webrender_api/src/display_item.rs:268: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, PartialEq, Serialize
	found: Debug, Copy, Clone, PartialEq, Serialize, Deserialize
./webrender_api/src/display_item.rs:396: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize
	found: Debug, Copy, Clone, Hash, Eq, PartialEq, Serialize, Deserialize, Ord, PartialOrd
./webrender_api/src/display_item.rs:496: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, PartialEq, Serialize
	found: Clone, Copy, Debug, PartialEq, Deserialize, Serialize
./webrender_api/src/display_item.rs:671: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, PartialEq, Serialize
	found: Copy, Clone, Debug, PartialEq, Serialize, Deserialize[0m
./webrender_api/src/display_list.rs:11: use statement is not in alphabetical order
	expected: serde::ser::{Serializer, SerializeSeq}
	found: serde::{Deserialize, Serialize}
./webrender_api/src/display_list.rs:14: use statement is not in alphabetical order
	expected: std::marker::PhantomData
	found: std::{io, mem, ptr, slice}
./webrender_api/src/display_list.rs:16: use statement is not in alphabetical order
	expected: time::precise_time_ns
	found: {AlphaType, BorderDetails, BorderDisplayItem, BorderRadius, BorderWidths, BoxShadowClipMode}
./webrender_api/src/display_list.rs:73: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Default, Deserialize, Serialize
	found: Copy, Clone, Default, Deserialize, Serialize
./webrender_api/src/display_list.rs:501: use statement is not in alphabetical order
	expected: display_item::CompletelySpecificDisplayItem::*
	found: display_item::{CompletelySpecificDisplayItem, GenericDisplayItem}
./webrender_api/src/font.rs:18: use statement is not in alphabetical order
	expected: std::sync::Arc
	found: {ColorU, IdNamespace, LayoutPoint}
./webrender_api/src/font.rs:22: derivable traits list is not in alphabetical order
	expected: Clone, Debug, Deserialize, Serialize
	found: Clone, Debug, Serialize, Deserialize
./webrender_api/src/font.rs:63: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, Serialize
	found: Copy, Clone, Deserialize, Serialize, Debug
./webrender_api/src/font.rs:73: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize
	found: Clone, Copy, Debug, Deserialize, Eq, Hash, PartialEq, Serialize, Ord, PartialOrd
./webrender_api/src/font.rs:90: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize
	found: Debug, Copy, Clone, Hash, Eq, PartialEq, Serialize, Deserialize, Ord, PartialOrd
./webrender_api/src/font.rs:98: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize
	found: Copy, Clone, Hash, PartialEq, Eq, Debug, Deserialize, Serialize, Ord, PartialOrd
./webrender_api/src/font.rs:148: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize
	found: Hash, Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd, Serialize, Deserialize
./webrender_api/src/font.rs:168: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, PartialOrd, Serialize
	found: Clone, Copy, Debug, PartialOrd, Deserialize, Serialize
./webrender_api/src/font.rs:198: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize
	found: Clone, Copy, Debug, Deserialize, Hash, Eq, PartialEq, PartialOrd, Ord, Serialize
./webrender_api/src/font.rs:258: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize
	found: Clone, Copy, Debug, Deserialize, Hash, Eq, PartialEq, PartialOrd, Ord, Serialize
./webrender_api/src/font.rs:282: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize
	found: Clone, Copy, Debug, Deserialize, Hash, Eq, PartialEq, PartialOrd, Ord, Serialize
./webrender_api/src/font.rs:298: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize
	found: Clone, Copy, Debug, Deserialize, Hash, Eq, PartialEq, PartialOrd, Ord, Serialize
./webrender_api/src/font.rs:314: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize
	found: Clone, Copy, Debug, Deserialize, Eq, Hash, PartialEq, PartialOrd, Ord, Serialize
./webrender_api/src/font.rs:324: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize
	found: Clone, Copy, Debug, Deserialize, Eq, Hash, PartialEq, PartialOrd, Ord, Serialize
./webrender_api/src/font.rs:335: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize
	found: Clone, Copy, Debug, Deserialize, Hash, Eq, PartialEq, PartialOrd, Ord, Serialize
./webrender_api/src/font.rs:352: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize
	found: Clone, Copy, Debug, Deserialize, Eq, Hash, PartialEq, Serialize, Ord, PartialOrd
./webrender_api/src/font.rs:361: derivable traits list is not in alphabetical order
	expected: Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize
	found: Clone, Hash, PartialEq, Eq, Debug, Deserialize, Serialize, Ord, PartialOrd
./webrender_api/src/image.rs:7: use statement is not in alphabetical order
	expected: std::sync::Arc
	found: {DevicePoint, DeviceUintRect, IdNamespace, TileOffset, TileSize}
./webrender_api/src/image.rs:25: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, Eq, Hash, PartialEq, Serialize
	found: Copy, Clone, Debug, Eq, PartialEq, Hash, Serialize, Deserialize
./webrender_api/src/image.rs:28: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, Eq, Hash, PartialEq, Serialize
	found: Copy, Clone, Debug, Eq, Hash, PartialEq, Serialize, Deserialize
./webrender_api/src/image.rs:37: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, Eq, Hash, PartialEq, Serialize
	found: Debug, Copy, Clone, Eq, Hash, PartialEq, Serialize, Deserialize
./webrender_api/src/image.rs:44: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, Eq, Hash, PartialEq, Serialize
	found: Debug, Copy, Clone, Eq, Hash, PartialEq, Serialize, Deserialize
./webrender_api/src/image.rs:71: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, PartialEq, Serialize
	found: Copy, Clone, Debug, Deserialize, PartialEq, Serialize
./webrender_api/src/image.rs:103: derivable traits list is not in alphabetical order
	expected: Clone, Debug, Deserialize, Serialize
	found: Clone, Debug, Serialize, Deserialize
./webrender_api/src/image.rs:176: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug
	found: Copy, Clone, Debug
./webrender_api/src/image.rs:198: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Eq, Hash, PartialEq
	found: Copy, Clone, Debug, PartialEq, Eq, Hash
./webrender_api/src/units.rs:21: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd
	found: Hash, Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd
./webrender_api/src/units.rs:50: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize
	found: Hash, Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Deserialize, Serialize
./webrender_api/src/units.rs:67: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd
	found: Hash, Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd
./webrender_api/src/units.rs:76: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd
	found: Hash, Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd
./webrender_api/src/units.rs:87: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd
	found: Hash, Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd
./webrender_api/src/units.rs:123: derivable traits list is not in alphabetical order
	expected: Clone, Copy, Debug, Deserialize, Serialize
	found: Copy, Clone, Debug, Serialize, Deserialize
./wrench/src/binary_frame_reader.rs:12: use statement is not in alphabetical order
	expected: std::path::{Path, PathBuf}
	found: std::{mem, process}
./wrench/src/cgfont_to_data.rs:32: extra space after while
./wrench/src/json_frame_writer.rs:16: use statement is not in alphabetical order
	expected: std::path::{Path, PathBuf}
	found: std::{fmt, fs}
./wrench/src/perf.rs:73: derivable traits list is not in alphabetical order
	expected: Clone, Deserialize, Serialize
	found: Clone, Serialize, Deserialize
./wrench/src/perf.rs:82: derivable traits list is not in alphabetical order
	expected: Deserialize, Serialize
	found: Serialize, Deserialize
./wrench/src/png.rs:7: use statement is not in alphabetical order
	expected: image::png::PNGEncoder
	found: image::{self, ColorType, GenericImage}
./wrench/src/reftest.rs:9: use statement is not in alphabetical order
	expected: image::png::PNGEncoder
	found: image::{ColorType, ImageFormat}
./wrench/src/ron_frame_writer.rs:9: use statement is not in alphabetical order
	expected: std::path::{Path, PathBuf}
	found: std::{fmt, fs}
./wrench/src/wrench.rs:22: use statement is not in alphabetical order
	expected: webrender::api::*
	found: webrender::{DebugFlags, RendererStats}
./wrench/src/wrench.rs:24: use statement is not in alphabetical order
	expected: yaml_frame_writer::YamlFrameWriterReceiver
	found: {WindowWrapper, BLACK_COLOR, WHITE_COLOR}
94m./wrench/src/wrench.rs:29: derivable traits list is not in alphabetical order
	expected: Clone, Debug, Eq, Hash, PartialEq
	found: Debug, Clone, Hash, PartialEq, Eq
./wrench/src/yaml_frame_reader.rs:20: use statement is not in alphabetical order
	expected: yaml_rust::{Yaml, YamlLoader}
	found: {BLACK_COLOR, PLATFORM_DEFAULT_FACE_NAME, WHITE_COLOR}
./wrench/src/yaml_frame_writer.rs:15: use statement is not in alphabetical order
	expected: std::path::{Path, PathBuf}
	found: std::{fmt, fs}
  Progress: 100% (693/693)
Running the dependency licensing lint...
The command "servo-tidy" exited with 1.
```

**Comment by glennw** [comment]
Alternatively, can we pin to an older version of the ```servo-tidy``` script perhaps?

**Comment by glennw** [comment]
cc @nical 

r? anyone

**Comment by glennw** [comment]
@nical @kvark FYI - we'll need to get this merged (or a different PR that pins the servo-tidy script to a previous version) in order to get the CI queue moving again.

**Comment by nical** [comment]
A number of the failures are the alphabetical order checks which we can now disable. For the rest I suspect wrench is adding some dependency duplication which ideally we shouldn't have to care about too much. I think that gecko has a similar duplicated dependency check so I assume WebRender itself is clean.

> Alternatively, can we pin to an older version of the servo-tidy script perhaps?

I hope not. I don't know what else servo-tidy is useful for, but it's been more harm than good in my opinion, I'd rather stop using it than be stuck with the quirks of the older version.
Or maybe you meant fork an older version on top of which we can add/remove stuff that gets in the way.

**Comment by Eijebong** [comment]
I'll have a look at the duplications later today if nobody gets to it before

**Comment by staktrace** [comment]
Note that for the taskcluster CI runs we effectively have servo-tidy pinned to some ancient version, because it was installed when I created the docker image (for Linux CI) and manually on the macOS worker, and doesn't get updated unless we do it manually.

**Pull request merged**
